### ISSUE TITLE
Spectating on infinity

### ISSUE THREAD

**Issue by KingMascotte** [Blumlaut/EasyAdmin#153]
On OneSync infinity you need to actually press spectate twice for it to work as clicking it the first time sets the spectate on the source player while the second time, it spectates the intended person

**Comment by Blumlaut** [comment]
Hmm, that shouldn't normally happen, can you add a `print(tostring(enable))` here: https://github.com/Blumlaut/EasyAdmin/blob/5.4/admin_client.lua#L144

and see what the ingame console outputs when you spectate the first and 2nd time?

**Comment by KingMascotte** [comment]
Sorry for the late response. I'll get the results back to you soon!

**Comment by Blumlaut** [comment]
there have been a number of changes to the spectate features recently, since there was no response here anymore i assume this issue has been fixed.
