### ISSUE TITLE
Please Developer

### ISSUE THREAD

**Issue by johnsoul777** [Blumlaut/EasyAdmin#160]
I would like to suggest that the superadmin be added, since if your staff team is large, it is better to remove certain options for the admin, for example the anonymous mode, I also take the opportunity to suggest that the player can also be revived

Thanks!

**Comment by johnsoul777** [comment]
If possible, I would also like to suggest that life and shield can be restored

**Comment by Blumlaut** [comment]
> I would like to suggest that the superadmin be added, since if your staff team is large, it is better to remove certain options for the admin, for example the anonymous mode, I also take the opportunity to suggest that the player can also be revived

That has always been possible, take a look at the [Wiki](https://github.com/Blumlaut/EasyAdmin/wiki/2.-Configuring-Permissions)

**Comment by johnsoul777** [comment]
@Blumlaut Thanks for your answer, you will see I have configured the permissions for mod, admin and superadmin, but when I connect to the server (I am superadmin) I can only see the sections that I have configured for the admin team, and although I authorize the superadmin full control, I can't see all the sections in the EasyAdmin menu, what am I doing wrong then?

this are my permissions

### Permisos de Easy Admin ###

# Permisos Moderadores #

add_ace group.moderator easyadmin.kick allow                # allow kicking
add_ace group.moderator easyadmin.mute deny                 # allow chat mute
add_ace group.moderator easyadmin.spectate allow            # allow spectating
add_ace group.moderator easyadmin.teleport.player allow     # allow teleportation player
add_ace group.moderator easyadmin.teleport.everyone deny    # allow teleportation all players
add_ace group.moderator easyadmin.slap deny                 # allow slapping
add_ace group.moderator easyadmin.freeze allow              # allow freezing
add_ace group.moderator easyadmin.manageserver deny         # allow manage server
add_ace group.moderator easyadmin.anon deny                 # allow anon management admin

# Permisos Administradores #

add_ace group.admin easyadmin.kick allow                    # allow kicking
add_ace group.admin easyadmin.mute deny                     # allow chat mute
add_ace group.admin easyadmin.spectate allow                # allow spectating
add_ace group.admin easyadmin.teleport.player allow         # allow teleportation
add_ace group.admin easyadmin.teleport.everyone deny        # allow teleportation all players
add_ace group.admin easyadmin.slap allow                    # allow slapping
add_ace group.admin easyadmin.freeze allow                  # allow freezing
add_ace group.admin easyadmin.manageserver deny             # allow manage server
add_ace group.admin easyadmin.anon deny                     # allow anon management admin
add_ace group.admin easyadmin.ban allow                     # allow ban
add_ace group.admin easyadmin.unban allow                   # allow unban

# Permisos Superadmin #

add_ace group.superadmin easyadmin allow                    # allow total permision

**Comment by Blumlaut** [comment]
you are most likely giving yourself "admin", instead of superadmin permissions, otherwise this should work fine.

**Comment by johnsoul777** [comment]
> you are most likely giving yourself "admin", instead of superadmin permissions, otherwise this should work fine.

I have this in my cfg

# Add system admins
add_ace group.admin command allow # allow all commands
add_ace group.admin command.quit deny # but don't allow quit

add_principal identifier.fivem:(MYIDFIVEM) group.superadmin # Fundador | John Wick
add_principal identifier.steam:(MYIDSTEAM) group.superadmin 

add_principal group.admin group.user
add_ace resource.es_extended command.add_ace allow
add_ace resource.es_extended command.add_principal allow
add_ace resource.es_extended command.remove_principal allow
add_ace resource.es_extended command.stop allow
add_ace resource.essentialmode command.sets allow
add_ace resource.essentialmode command.add_principal allow
add_ace resource.essentialmode command.add_ace allow
add_ace resource.opendoor_madrazo command allow

------
after exec my easyadmin.cfg
------

# Configuración #

setr ea_LanguageName "es"                # cambio de idioma
setr ea_MenuButton "344"			     # establecer el botón de menú en F2. por defecto en: "289"
setr ea_alwaysShowButtons "false"	     # no queremos ver botones a los que ni siquiera podemos acceder, ¿verdad? defecto: "false"
set ea_moderationNotification "false"    # esto puede ser "false" o una dirección de webhook de discord, esto enviará un mensaje de discordia si un administrador toma medidas contra un jugador (como banear y kickear)
set ea_custombanlist "false"             # lea los documentos para esto, no lo toque
set ea_enableCallAdminCommand "false"    # activa "calladmin" comando a través de webhook
set ea_enableReportCommand "false"       # activa "report" comando, consulte la página Wiki de configuración para obtener más información https://github.com/Blumlaut/EasyAdmin/wiki

### Permisos de Easy Admin ###

# Permisos Moderadores #

add_ace group.moderator easyadmin.kick allow                # allow kicking
add_ace group.moderator easyadmin.mute deny                 # allow chat mute
add_ace group.moderator easyadmin.spectate allow            # allow spectating
add_ace group.moderator easyadmin.teleport.player allow     # allow teleportation player
add_ace group.moderator easyadmin.teleport.everyone deny    # allow teleportation all players
add_ace group.moderator easyadmin.slap deny                 # allow slapping
add_ace group.moderator easyadmin.freeze allow              # allow freezing
add_ace group.moderator easyadmin.manageserver deny         # allow manage server
add_ace group.moderator easyadmin.anon deny                 # allow anon management admin

# Permisos Administradores #

add_ace group.admin easyadmin.kick allow                    # allow kicking
add_ace group.admin easyadmin.mute deny                     # allow chat mute
add_ace group.admin easyadmin.spectate allow                # allow spectating
add_ace group.admin easyadmin.teleport.player allow         # allow teleportation
add_ace group.admin easyadmin.teleport.everyone deny        # allow teleportation all players
add_ace group.admin easyadmin.slap allow                    # allow slapping
add_ace group.admin easyadmin.freeze allow                  # allow freezing
add_ace group.admin easyadmin.manageserver deny             # allow manage server
add_ace group.admin easyadmin.anon deny                     # allow anon management admin
add_ace group.admin easyadmin.ban allow                     # allow ban
add_ace group.admin easyadmin.unban allow                   # allow unban

# Permisos Superadmin #

add_ace group.superadmin easyadmin allow                    # allow total permision

----
 and in my database in the user table, i has superadmin

![image](https://user-images.githubusercontent.com/72218928/97116984-4a118380-1701-11eb-952e-dd1af707daac.png)

I don't understand what I'm doing wrong :(

thank for you answer :)

**Comment by Blumlaut** [comment]
I would recommend uploading your server.cfg in our discord server instead, as we have a dedicated bot for permission problems there, issues aren't the place to check these kind of things, sorry!
