### ISSUE TITLE
Specate infinity

### ISSUE THREAD

**Issue by kFxDaKing** [Blumlaut/EasyAdmin#161]
Hello, specate is not working on onesync infinity.

Teleports works okay.
Specate works just in the "bubble" outside bubble it doesnt work.

Player Squizer Requested Spectate to kFxDaKing
And nothing happends, no errors.

**Comment by Blumlaut** [comment]
That usually would indicate that this check fails:
https://github.com/Blumlaut/EasyAdmin/blob/master/admin_server.lua#L288

What does `print(tgtCoords.x, tgtCoords.y, tgtCoords.z)` show?

**Comment by czsquizer** [comment]
This is, how I solved it:
`AddEventHandler('EasyAdmin:requestSpectate', function(playerId, tgtCoords)
	local oldCoords = GetEntityCoords(PlayerPedId())
	SetEntityCoords(PlayerPedId(), tgtCoords.x, tgtCoords.y, tgtCoords.z - 10.0, 0, 0, 0, false)
	Wait(1000)
	local playerId = GetPlayerFromServerId(playerId)
	if not tgtCoords or tgtCoords.z == 0 then tgtCoords = GetEntityCoords(GetPlayerPed(playerId)) end
	if GetPlayerPed(playerId) == PlayerPedId() then return end
	frozen = true
	SetEntityCoords(PlayerPedId(), tgtCoords.x, tgtCoords.y, tgtCoords.z - 10.0, 0, 0, 0, false)
	Wait(500)
	local adminPed = PlayerPedId()
	spectatePlayer(GetPlayerPed(playerId),playerId,GetPlayerName(playerId))
	Wait(500)
	SetEntityCoords(PlayerPedId(), oldCoords.x, oldCoords.y, oldCoords.z, 0, 0, 0, false)
end)`

**Comment by Blumlaut** [comment]
That is not a solution to this issue, please provide the informations i requested.

**Comment by czsquizer** [comment]
> That usually would indicate that this check fails:
> https://github.com/Blumlaut/EasyAdmin/blob/master/admin_server.lua#L288
> 
> What does `print(tgtCoords.x, tgtCoords.y, tgtCoords.z)` under that line show?

It prints correct player coords.

**Comment by Blumlaut** [comment]
Interesting, i would assume that sending the vector3 to the client side has some issues then...

**Comment by kFxDaKing** [comment]
squziers pull request fixed that for us.

**Comment by Blumlaut** [comment]
how often do i have to repeat myself? its **not** a solution to this issue, its a hacky workaround that doesn't fix the actual issue, since there is seemingly no actual interest in solving the issue im locking this pull issue for further discussion.

**Comment by Blumlaut** [comment]
Update, this issue has been fixed _properly_ in:
https://github.com/Blumlaut/EasyAdmin/releases/tag/5.503

With a proper repro this would've been resolved months ago, since i had to set up a seperate machine to test this.
