### ISSUE TITLE
How to rebind the open key?

### ISSUE THREAD

**Issue by FakeItalianMan** [Blumlaut/EasyAdmin#168]
Is there a way to permanently re-keybind the open menu key for EasyAdmin seems kind of a pain to have to set it through the console command every time I restart my server.

**Comment by Blumlaut** [comment]
https://github.com/Blumlaut/EasyAdmin/wiki/1.-Configuring-EasyAdmin


```
Configuration of EasyAdmin is done via convars, these can be set via your server config file or by typing it as a command inside your servers' console ( this method may not always work with EasyAdmin and the settings will reset after the server has been restarted. )
```

?
