### ISSUE TITLE
spectate and mumble voice

### ISSUE THREAD

**Issue by BerkieB** [Blumlaut/EasyAdmin#173]
I'm using mumble voip on my server with onesync (legacy) and when I spectate someone I can't hear them, any fixes for this or is there something else that I'm doing wrong?
I'm running on EasyAdmin 5.502.

**Comment by Blumlaut** [comment]
EasyAdmin isn't "adapted" to work with mumble-voip and probably will never be to keep the the "talk" it does to outside resources to a minimum. if there is a lot of interest i can see whats possible.

**Comment by Blumlaut** [comment]
due to the sheer amount of voice chat implementations(besides mumble-voip), this is currently not feasable without support to extend easyadmin code.
