### ISSUE TITLE
Fivem | Console Error

### ISSUE THREAD

**Issue by mrawsky** [Blumlaut/EasyAdmin#174]
When i add 'banCheater' to anticheat i get this error:
![image](https://user-images.githubusercontent.com/73143552/100911289-50003e80-34cf-11eb-90db-113cc7d7c954.png)

**Comment by Blumlaut** [comment]
you are most likely using the event incorrectly, show code.

**Comment by Blumlaut** [comment]
OP has asked in support both in Discord and here, has not followed up, closing this issue, please reopen if you can provide further infos.
