### ISSUE TITLE
Spectating does not work on Onesync enabled 64 player server

### ISSUE THREAD

**Issue by pdamir** [Blumlaut/EasyAdmin#176]
I've setup the latest version of EasyAdmin on our live server but still have issues with spectating. On our dev server spectating worked 7/10 times, but now it never works. Both are onesync enabled.
Basically it spectating puts me under ground, underneath the player so I can't see anything, and also doesn't move as the player moves. Also, when I quit spectating by pressing E, it just lets the player fall under the map.

https://streamable.com/zfudi0

**Comment by pdamir** [comment]
Unfortunately that commit helped with just one issue. It fixed bug when stopping spectating left me under ground instead of returning to starting position.

I've recorded the video of my issue which includes logs you've added
https://streamable.com/vnih53

**Comment by Blumlaut** [comment]
Sadly i cant seem to reproduce your issue at all, on any configuration, only thing i could think of is another resource interfering, some anticheat maybe?

**Comment by pdamir** [comment]
Yes we figured that this issue is specific to our server and there is probably some conflict. 
Thank you for debugging it though and trying to help! Much appreciated.

We are gonna do a server cleanup and for sure use EA in future. Cheers!
