### ISSUE TITLE
¿For what?

### ISSUE THREAD

**Issue by johnsoul777** [Blumlaut/EasyAdmin#178]
Hi Blu!

I was thinking, why does a script as good as this still use ace permissions? Wouldn't it be easier to put an xPlayer call? and create a configuration file to activate and deactivate the permissions for mod, admin and superadmin, I for example recoded an old script that used essentialmode and ace permissions to teleport with / gc commands. I leave you an example, maybe it will help you great to see this in easy admin.

Example:

`RegisterCommand('gc', function(source, args, user)
	local xPlayer = ESX.GetPlayerFromId(source)

	local x = tonumber
	local y = tonumber
	local z = tonumber
	local heading = tonumber
	
	if x and y and z and heading then
		TriggerClientEvent('esx:teleport', source, {
			x = 213.73, y = -809.04, z = 33.92, heading = 157.53
		})
	end

	if xPlayer.getGroup() == 'admin' or xPlayer.getGroup() == 'superadmin' then
		print(('^2¡Te has teletransportado a Garaje Central %s!^0'):format(GetPlayerName(source)))
	end	

end, true)`

**Comment by Blumlaut** [comment]
> why does a script as good as this still use ace permissions? Wouldn't it be easier to put an xPlayer call?  

Because im not clinically insane.
