### ISSUE TITLE
Spectate stop Bug

### ISSUE THREAD

**Issue by Tidolop** [Blumlaut/EasyAdmin#181]
Hello,
when i spectate a player and when i am ready and press e to stop stop spectating, i automatically spectate another player and cant quit that. Only with the vMenu i can help myself to get my player back. Of couse when i relog i also get my player back.

Its a FiveM Gameserver hostet at Zap-Hosting with ESX and 3 additional admin scripts: EasyAdmin (the newest version), vMenu and esx_adminmode.
I use the Anticheat "Anticheese".

Here is a video where i show the bug.
https://user-images.githubusercontent.com/49469363/105921289-f46ab100-6038-11eb-892e-c1dceb1ee566.mp4

Sorry for my bad english but i tried my best :)

**Comment by Blumlaut** [comment]
Hi! 

Thanks for creating this issue, however, we already have an issue open about this particular bug, you can see it here:
https://github.com/Blumlaut/EasyAdmin/issues/180

I will add your Video to the original issue for future reference and close this issue.
