### ISSUE TITLE
Screenshot-Basic Integration

### ISSUE THREAD

**Issue by LukeM03** [Blumlaut/EasyAdmin#187]
Screenshot Basic and Easy Admin 
Screenshot. When there is a screenshot is taken through the EasyAdmin Menu it prints all the details to the Webhook and server and parts of the cfg to the client chat. I fixed this by just copying a bunch of text and on screenshot just printing it thru a trigger. This may be an issue because it exposes your webhook.

**Comment by Blumlaut** [comment]
Can you send a log or screenshot of what exactly gets printed? also knowing which uploader you are using would be useful.

**Comment by LukeM03** [comment]
Yeah. When the issue occurred we were using the default upload in the server.cfg gimme a sec to get the SC.

**Comment by LukeM03** [comment]
![image](https://user-images.githubusercontent.com/72722699/109173991-6c201e80-7752-11eb-9351-e990b4fa3b13.png)
 
That is the Easy Admin menu, (Had one of the Mods take a screen shot of themselves)

![image](https://user-images.githubusercontent.com/72722699/109173935-60345c80-7752-11eb-9fd7-ffc42eb62c62.png)

**Comment by LukeM03** [comment]
the second one is the client

**Comment by Blumlaut** [comment]
please check if this commit fixes it:
https://github.com/Blumlaut/EasyAdmin/commit/c72479a28e0c54ae9e783fcce9328c8c5c03c5f3

**Comment by LukeM03** [comment]
will do

**Comment by LukeM03** [comment]
what line is that in?

**Comment by Blumlaut** [comment]
it shows both the file and the lines, you can also just clone master if you dont mind using a prerelease

**Comment by LukeM03** [comment]
i am literally dumb as shit

**Comment by LukeM03** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/72722699/109225738-b2de3a80-778b-11eb-9fb8-f0b3e8687491.png)

**Comment by LukeM03** [comment]
it should look like that. Right?

**Comment by Blumlaut** [comment]
like it looks in the commit.

**Comment by LukeM03** [comment]
alright I also noticed that on line 781 and 782 its adding a client chat message.

**Comment by Blumlaut** [comment]
if you don't quite understand how git commits work i recommend just cloning master and using the master branch, it should be fairly stable currently so you should not run into any issues.

**Comment by LukeM03** [comment]
that commit didn't seem to work.

**Comment by LukeM03** [comment]
![image](https://user-images.githubusercontent.com/72722699/109308520-20cc4580-7810-11eb-8c4f-7ffb6b49e628.png)
so it is taking the photo however its saying failed

**Comment by LukeM03** [comment]
but it isn't exposing our thing

**Comment by zap-fivem** [comment]
check the server console for errors, screenshot should not fail because of that.

**Comment by Blumlaut** [comment]
check the server console for errors, it should not fail because of that commit

**Comment by LukeM03** [comment]
The photos seems to be taking, just printing an error. No errors in the Server console or client Log.

**Comment by Blumlaut** [comment]
does it also get uploaded to discord? the "screenshot failed" message happens if screenshot-basic doesnt call back to confirm the screenshot was taken.

**Comment by xrtw** [comment]
> does it also get uploaded to discord? the "screenshot failed" message happens if screenshot-basic doesnt call back to confirm the screenshot was taken.

photos upload to discord, but not for admin discord channel and not showing screenshot in the game

**Comment by Blumlaut** [comment]
I've added another commit that should address the "attachments" error, please test @xrtw @LukeM03 https://github.com/Blumlaut/EasyAdmin/commit/2718278250ecc871891ab5b5ad3dcd8dcfbb9ace

**Comment by LukeM03** [comment]
ok. I will add.

**Comment by xrtw** [comment]
> I've added another commit that should address the "attachments" error, please test @xrtw @LukeM03 [2718278](https://github.com/Blumlaut/EasyAdmin/commit/2718278250ecc871891ab5b5ad3dcd8dcfbb9ace)

thank you, works great!

**Comment by Blumlaut** [comment]
assuming this is fixed for now, please re-open if this is still an issue.
