### ISSUE TITLE
players ban

### ISSUE THREAD

**Issue by xrtw** [Blumlaut/EasyAdmin#190]
hello, a lot of people can't play. after easyadmin update, seems its adding new bans automatically to new players
`["steam:110000117af8cfe","license:4c049a319fcf839ea02cbac4dbe0953e3937499d","xbl:2535407785982906","live:914798119455461","discord:802590754102575124","license2:4c049a319fcf839ea02cbac4dbe0953e3937499d","ip:10.131.33.30","4:6692eb7c187201b08f92b0d7e769882b97c713f9515e52cd997c3d9b951822a5","1:eb36119e65dbe2736e3c9140352d10de5b1ab3fdbf985539918f3996093e23c5","4:e7793ddedd519f6d8b3f7831162ca906d251379829a56cd60d39adcdf344cc46","4:aafff27312f744e8034952928d656fa7f4c8e3c01659ff7c13cba82f2abb3ec1","4:771e65a62614a15d2cfa046a82503a09133867e89a58b57353d9042fa0d7db40","4:a94a6ea1dc7349e59678d79da22dbab503308525b7f177ca9a28dc8289cd9c38","4:08621f33e59c61d90ed8d4165ca7ea9c33a112dc773bf197ec03dec0c5efa8d3","4:e7efcc9b2eb83b563ce1c3de07c1b1ecbdf59bd9dea0abbc6896e42d3248cb7f","4:1eeb989f03b4c642a44e5f7f5d7fd35e30d5cc79e9101b5b9836401065f970e1","4:8d18a48e2eaafb4e4ae0601a0708fc6840c9347afbdb1df0d172b6e4fea9122d","3:64b28237f2f60992107bb310e85b2af5fce13dca53253f59f3dc75ddfb934107","2:6771780160e8a03f314908c7724128fb89efd777162d083ed5995bf3a49c08ba","4:fc9381cb1035bb808decb258ff494d1f07b110927e70c7d2b133263c150f2f83","4:0504a62a84e54886d59d4fc42afbcb99ca765d3dcf6ddff89278186c6737f285","4:e78d089b08da5d0d110b794ef32044c5a8a52a8c7256b4bba08e3a980f4987a2","4:e66fd5903032224ac7ab2d5e355e0d5569a7701b4a5c2e080aadceb4fedb67e3","4:ebf33ba548ee94d181801c4c23d41d4117443431dd548ba40cd8bedb32042210"]` (one of banned player)

**Comment by Blumlaut** [comment]
easyadmin will add new identifiers and tokens to a ban if a player that is banned joins, you can try increasing [ea_minidentifiermatches](https://github.com/Blumlaut/EasyAdmin/wiki/1.-Configuring-EasyAdmin#set-ea_minidentifiermatches-2) if your Server is behind a Reverse Proxy, for example.

**Comment by xrtw** [comment]
> easyadmin will add new identifiers and tokens to a ban if a player that is banned joins, you can try increasing [ea_minidentifiermatches](https://github.com/Blumlaut/EasyAdmin/wiki/1.-Configuring-EasyAdmin#set-ea_minidentifiermatches-2) if your Server is behind a Reverse Proxy, for example.

thank you for reply. my ea_minidentifiermatches is already set 2.

**Comment by Blumlaut** [comment]
in this case some other identifier matches, enable debugging and then check the console output if a player who is "apparently" banned joins the server

**Comment by xrtw** [comment]
> easyadmin will add new identifiers and tokens to a ban if a player that is banned joins, you can try increasing [ea_minidentifiermatches](https://github.com/Blumlaut/EasyAdmin/wiki/1.-Configuring-EasyAdmin#set-ea_minidentifiermatches-2) if your Server is behind a Reverse Proxy, for example.
sorry, its not an issue... probably he tried to join a server with changing his rockstar license.
