### ISSUE TITLE
EasyAdmin BUG

### ISSUE THREAD

**Issue by KingCaleb-1** [Blumlaut/EasyAdmin#193]
I have tried everything to fix my problem, I've re installed, asked reddit, etc. My problem is that non of our fivem server staff can teleport because when we do, it puts us under the map. Any suggestions?

**Comment by Blumlaut** [comment]
I would need some more infos about this.

- Which EasyAdmin Version are you running?
- Are you using Onesync Infinity? Legacy?
- Which FXServer Artifact?
- Has this always happened or just recently started?

**Comment by KingCaleb-1** [comment]
@Blumlaut We are using the EasyAdmin that comes with ZapHost and we have tried all sorts of things. Its been like this since we first got the server up a few days ago. EasyAdmin works great, the ONLY thing that doesn't work, is the teleportation. We have asked everybody for help and nobody knows. When we hit "teleport to player" It just puts us under the map in Los Santos.

**Comment by KingCaleb-1** [comment]
Its in our actual server. Our zap hosting server. Its fine though, we can
just use vMenu to teleport.

**Comment by Smokiiee** [comment]
> I would need some more infos about this.
> 
> * Which EasyAdmin Version are you running?-----Latest that zap-hosting have-
> * Are you using Onesync Infinity? Legacy?----- no.
> * Which FXServer Artifact? ----think its the latest. zap is not telling me what version they are using
> * Has this always happened or just recently started? have been like this when i install it on the server 

have the same problem.

**Comment by Smokiiee** [comment]
@Blumlaut

**Comment by Blumlaut** [comment]
please test https://github.com/Blumlaut/EasyAdmin/archive/refs/heads/master.zip, i have done some changes to how teleporting is handled, may help.

@Smokiiee @KingCaleb-1

**Comment by Blumlaut** [comment]
closing as stale, please reopen if issue is still ongoing with the above branch
