### ISSUE TITLE
Options appear, but member management does not work

### ISSUE THREAD

**Issue by Nathant995** [Blumlaut/EasyAdmin#198]
Options appear in the game UI. Features such as SLAP & mute work but kick & ban does not.

**Comment by Nathant995** [comment]
This issue seems specific to RedM

**Comment by Blumlaut** [comment]
Which artifact version are you using? Also, make sure that you are not attempting to kick/ban yourself, easyadmin has an `immune` permission which prevents people with that permission from getting kicked, banned and such.

**Comment by Nathant995** [comment]
Ahh it might be the immune system, didn’t think of that. I’ll do some more testing. And I forget the build version but it was released like last week

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Blumlaut** [comment]
Assuming this issue has been resolved, please re-open if the issue is still ongoin.

**Comment by Nathant995** [comment]
Oh yes, Apologies! Thanks for the assistance
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
