### ISSUE TITLE
Certain Webhook messages do not have bold names

### ISSUE THREAD

**Issue by zRxnx** [Blumlaut/EasyAdmin#219]
There is no **TEXT** for these: 
![image](https://user-images.githubusercontent.com/74078713/121784858-b8368800-cbb6-11eb-8535-49f3450f3436.png)

**Comment by Blumlaut** [comment]
..What?

**Comment by zRxnx** [comment]
Falls du Deutsch kannst, ich meine das der Steamname und die Steamid nicht Dick geschrieben ist. Sprich es sollte so sein: "**TEST**" es ist aber so "TEST"

**Comment by Blumlaut** [comment]
fixed in https://github.com/Blumlaut/EasyAdmin/commit/10ee19d7114afd472177d8dca5a98e9954f514f1
