### ISSUE TITLE
im run the game from FIVEM APP

### ISSUE THREAD

**Issue by afekio** [Blumlaut/EasyAdmin#224]
i dont have steam ver of GTA how to add myself as admin?

**Comment by Noobspielt** [comment]
Just let steam open. Then you have a steam ID

**Comment by Blumlaut** [comment]
> i dont have steam ver of GTA how to add myself as admin?

You can use any identifier, steam is just the one used in the example, also see what Noobspielt commented, this is correct.

**Comment by therealknight** [comment]
> Just let steam open. Then you have a steam ID

That's all well and good, but when he comes to trying to use it with a Steam HexID, he's going to need a Steam WebAPIKey and those cannot be generated by new created accounts who havent spent at least £/$5 on the Steam Store.

**Comment by Blumlaut** [comment]
but you dont have to use it with a steam identifier at all? like i said, ANY identifier works.

**Comment by therealknight** [comment]
> but you dont have to use it with a steam identifier at all? like i said, ANY identifier works.

I understand that, just pointing out if he chooses to do that method he's gonna run into issues very easily.
