### ISSUE TITLE
Menu Orientation

### ISSUE THREAD

**Issue by ITKewai** [Blumlaut/EasyAdmin#230]
Missing "Right" option in Menu Orientation

**Comment by Blumlaut** [comment]
this was done on purpose, see https://github.com/Blumlaut/EasyAdmin/commit/cb0270cb984bdd6d7d4e4ac3fb41a0fe2b693a2d

**Comment by ITKewai** [comment]
and for people that have chat on right?

**Comment by Blumlaut** [comment]
They can use "center", which is also set as default from 6.2 RC1 and onwards, the right orientation always clipped past screen border so it just could not be used properly anymore.
