### ISSUE TITLE
IP ban

### ISSUE THREAD

**Issue by Dejvi1** [Blumlaut/EasyAdmin#233]
Hi i got issue with banning as i ban someone next 3 players PM that they got ban aswell due to same IP.. those are random guys.. so i want to ask if i can disable IP from identifiers ?
Thank you very much for help..

**Comment by Blumlaut** [comment]
This has been asked every day for the past 3 days, No, you cannot, and should not, disable IP Identifiers, if you use some proxying then you should increase `ea_minIdentifierMatches` by the amount of Proxy IPs you use.
see the wiki for more infos:
https://github.com/Blumlaut/EasyAdmin/wiki/1.-Configuring-EasyAdmin
