### ISSUE TITLE
Config Editor fails loading vMenu config if vMenu is running

### ISSUE THREAD

**Issue by buadla** [Blumlaut/EasyAdmin#236]
dear 

i have problem with new version 6.2 on console give me error 

[    script:EasyAdmin] SCRIPT ERROR: @EasyAdmin/admin_server.lua:1296: attempt to index a nil value (local 'file')
[    script:EasyAdmin] > readAcePermissions (@EasyAdmin/admin_server.lua:1196)
[    script:EasyAdmin] > userCallback (@EasyAdmin/admin_server.lua:2003)

thanks

**Comment by Blumlaut** [comment]
Thats odd - can you do `setr ea_logLevel 4` and watch the console output before that error happens? Sounds like its trying to read some config file which doesnt exist.

**Comment by buadla** [comment]
[    script:EasyAdmin] EasyAdmin: Version check returned 200, Local Version: 6.2, Remote Version: 6.2
[    script:EasyAdmin] EasyAdmin: screenshot-basic is not installed, screenshots unavailable
[    script:EasyAdmin] EasyAdmin: reading server.cfg
[    script:EasyAdmin] EasyAdmin: parsed ace group.admin command allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace group.admin command.quit deny in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace resource.es_extended command.add_ace allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace resource.es_extended command.add_principal allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace resource.es_extended command.remove_principal allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace resource.es_extended command.stop allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace group.admin command allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace group.admin command.quit deny in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace resource.essentialmode command.sets allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace resource.essentialmode command.add_principal allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace resource.essentialmode command.add_ace allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace group.admin easyadmin allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace group.admin "vMenu.Everything" allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace resource.EasyAdmin command.add_ace allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace resource.EasyAdmin command.remove_ace allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace resource.EasyAdmin command.add_principal allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed ace resource.EasyAdmin command.remove_principal allow in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed principal identifier.steam:11000011a97b61f group.admin in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed exec resources/vMenu/config/permissions.cfg in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: parsed exec easyadmin_permissions.cfg in server.cfg
[    script:EasyAdmin] 
[    script:EasyAdmin] EasyAdmin: reading resources/vMenu/config/permissions.cfg
[    script:EasyAdmin] SCRIPT ERROR: @EasyAdmin/admin_server.lua:1296: attempt to index a nil value (local 'file')
[    script:EasyAdmin] > readAcePermissions (@EasyAdmin/admin_server.lua:1196)
[    script:EasyAdmin] > userCallback (@EasyAdmin/admin_server.lua:2003)

**Comment by Blumlaut** [comment]
is your `resources/vMenu/config/permissions.cfg` file read or write protected? Or does it exist in the first placeß I couldn't reproduce this on my end, it always bailed before erroring:
![image](https://user-images.githubusercontent.com/13604413/128415257-88dae83f-9059-417e-9bee-8121e33831f3.png)

**Comment by buadla** [comment]
![image](https://user-images.githubusercontent.com/57746615/128415496-3e2d2116-4ad5-4ca0-8ef9-901b16331e3f.png)

**Comment by buadla** [comment]
i try to disable the vMenu and its work normally without error

**Comment by Blumlaut** [comment]
Did you disable the vMenu _resource_ or remove the "exec" line from the config? Unless vMenu opens the file itself it shouldnt change anything..

**Comment by buadla** [comment]
disable vMenu resource, 
but FYI it work normally both inside the server but it show error in console

**Comment by Blumlaut** [comment]
I cant reproduce this error at all from my end, there must be something wrong with your Permissions.
