### ISSUE TITLE
Open Key Button Issue

### ISSUE THREAD

**Issue by Rxven77** [Blumlaut/EasyAdmin#244]
When i press the button which i selected in the server.cfg, it doesn't open the menu. I can only open the menu when press "F5" or with the command /easyadmin | And but the problem is i choosed the button "F10"

Cfg Code:
setr ea_MenuButton "F10"

And when i press "F10" it doesn't open.

Can someone help me pls?

**Comment by Blumlaut** [comment]
Intentional behaviour, read:
https://github.com/Blumlaut/EasyAdmin/wiki/Update-Instructions#fivem-keybinds
