### ISSUE TITLE
newest commit (79e5e30) causing an error

### ISSUE THREAD

**Issue by Hamy-os** [Blumlaut/EasyAdmin#254]
Hello the following commit (#253 / 79e5e30 ) is now causing this error:

[    script:EasyAdmin] Error parsing script @EasyAdmin/admin_server.lua in resource EasyAdmin: @EasyAdmin/admin_server.lua:561: ')' expected near 'function'
[    c-scripting-core] Failed to load script admin_server.lua.

**Comment by Blumlaut** [comment]
ignore the regression label, i didnt know github adds it when creating one :p

**Comment by Blumlaut** [comment]
fixed in https://github.com/Blumlaut/EasyAdmin/commit/776ac8f3898182e5c075d533bbd89e92efa017e9

**Comment by Hamy-os** [comment]
wow, fast response! Thank you!

**Comment by Jaccosf** [comment]
Thank you both for reporting the error and fixing it, should have checked it better before making the PR😅
