### ISSUE TITLE
When in the reporter page backspace closes easyadmin

### ISSUE THREAD

**Issue by nickmacwiz** [Blumlaut/EasyAdmin#256]
Can it be fixed so that after you click on a call admin and you click reporter. If you press backspace it currently exits the the EasyAdmin instead of taking you back to the report to close it.

**Comment by Blumlaut** [comment]
This is apparently a regression from when the following issue was fixed:
https://github.com/Blumlaut/EasyAdmin/commit/94bd93eefa7468556805ebea63c30b1156bb4b17

**Comment by Blumlaut** [comment]
https://github.com/Blumlaut/EasyAdmin/commit/49c9dd11a4436b4600c8dce43d9ac00156920870 
should fix it.

**Comment by nickmacwiz** [comment]
Thank you very much 👍
