### ISSUE TITLE
Long time to open

### ISSUE THREAD

**Issue by Dennis-NL** [Blumlaut/EasyAdmin#308]
EasyAdmin takes a very long time to open.
When you press the key to open i takes about 5sec for EasyAdmin to open. Same goes for the command

This happens when i have above 100 players, 280 is much worse.

Previous version wasn't as bad as this one

**Comment by Blumlaut** [comment]
> My previous version was 6.201
> Anything changed between that version and the newest one?

https://github.com/Blumlaut/EasyAdmin/compare/6.201...6.402

> Server is not hitching

There were in total, 2 reports of an exact issue like this, it is EXTREMELY likely that your server is hitching.

Have you even checked the profiler?

**Comment by Dennis-NL** [comment]
Yes i have. For some reason profiler on the server side is broken, so i cant send a screenshot of that. Probably need a server restart
But i have one for the client sid
![Screenshot_2](https://user-images.githubusercontent.com/43215753/149207718-2890bccc-860c-4fc8-a5de-9b34f0a655ff.png)
![Screenshot_1](https://user-images.githubusercontent.com/43215753/149207724-67fa4632-8b6c-4644-a3d3-492c6226a1d2.png)
e

**Comment by Blumlaut** [comment]
client profiler is irrelevant.

**Comment by Dennis-NL** [comment]
Got it working again. This is with around 250 players

![Screenshot_6](https://user-images.githubusercontent.com/43215753/149208926-c562e7c7-ffc0-4173-a4a0-7d767a043015.png)
![Screenshot_7](https://user-images.githubusercontent.com/43215753/149208934-099c3aae-a209-4bcf-8103-a19a160bda06.png)

**Comment by Blumlaut** [comment]
provide full screenshots of the profiler, the section you posted just says that GetInfinityPlayerList took ~3ms to complete, which is expected behaviour, EasyAdmin uses asynchronous latent events which dont actively halt execution

**Comment by Dennis-NL** [comment]
I cannot send you a full screenshot right now, i will send you one tommorrow because the profiler is broken right now..

This is a screenshot of the network event log when opening EasyAdmin
![Screenshot_8](https://user-images.githubusercontent.com/43215753/149209913-26110bdb-afdc-43da-8dfc-208ef43f6a43.png)

**Comment by Blumlaut** [comment]
that would _still_ only clock in at about 2,1 seconds load time, transfer speeds are limited at 200000bps

**Comment by Dennis-NL** [comment]
Opening time is around 5 seconds

**Comment by Blumlaut** [comment]
With how many players is that? It would probably be smarter to rewrite the system to only fetch necesarry infos to display userdata, and fetch the rest on select then.

**Comment by Blumlaut** [comment]
https://github.com/Blumlaut/EasyAdmin/commit/60b94eb9d9a64442f54adc00ee93143b07cbd226

see if this improves it.
