### ISSUE TITLE
cleanup & split up code

### ISSUE THREAD

**Issue by Blumlaut** [Blumlaut/EasyAdmin#317]
should probably consider properly sorting the code, having everything in a few dedicated files is not that clean anymore with the current codebase

propsal:

```
EasyAdmin
- src
- - server
- - - permission_editor.lua
```

not sure if splitting up events and functions is a good idea, also not sure about `src` folder? i'm not sure how clean would be having code scattered across all other folders.

we should also consider adding a quick function that deletes the old script files automatically, we do the same for __resource.lua already, should be no biggie

**Comment by Blumlaut** [comment]
this would probably require a code freeze before starting to implement.

**Comment by Jaccosf** [comment]
Well in my opinion you should indeed clean it up by seperating it to client, server and such, but I'm not sure if throwing the code into a src folder is going to fix anything. I doubt if people who even change the source code will stop when it is in `src` and I think it would be 'less' clean in github to see.

**Comment by Blumlaut** [comment]
the main concern is just random idiots seeing "server" and "client" and thinking its something they can/should edit, although you might be right that its more of a hassle

**Comment by Blumlaut** [comment]
Here is how it would look when just using server/client stuffs:
![image](https://user-images.githubusercontent.com/13604413/154626074-aae89a30-1c19-47e3-abe9-08ecec266d07.png)

vs when using "src" folder:
![image](https://user-images.githubusercontent.com/13604413/154626101-236cc2d9-d747-4672-b1d7-eddba2e8048d.png)

**Comment by Blumlaut** [comment]
Closing as implemented in bot branch
