### ISSUE TITLE
Question: GUI for Admin Calls

### ISSUE THREAD

**Issue by ViolentMinds** [Blumlaut/EasyAdmin#318]
1) Is there a way to also have the admin calls pop up in the chat window too. As well as the regular pop up. 

2) Is it possible to increase the time with which the notification of the call coming in stays on screen. It disappears too fast I barely have time to read it! heh. I'm old ok.

Thanks!

**Comment by Blumlaut** [comment]
> 1. Is there a way to also have the admin calls pop up in the chat window too. As well as the regular pop up.

yes, but this was intentionally removed as custom chat resources often didn't respect the chat's API, you can write a plugin to still show it.

>  Is it possible to increase the time with which the notification of the call coming in stays on screen. It disappears too fast I barely have time to read it! heh. I'm old ok.

that depends on the notification system in use
