### ISSUE TITLE
unstable Version?

### ISSUE THREAD

**Issue by Sunny084** [Blumlaut/EasyAdmin#322]
I downloaded and installed the latest version of EasyAdmin and my Server Console says me EasyAdmin has an unstable Version
How to fix that?

**Comment by Blumlaut** [comment]
Do what the error message tells you to do?

**Comment by Sunny084** [comment]
It tells me that i should download the latest Version, ive done that and i get the error message again

**Comment by Blumlaut** [comment]
thats not what it tells you, it tells you to download the latest _release_, which you didnt do.

**Comment by Sunny084** [comment]
ok thanks for the help i will try
