### ISSUE TITLE
easyadmin esx

### ISSUE THREAD

**Issue by ynjn1** [Blumlaut/EasyAdmin#323]
i have a problem with easy admin not working on my esx server its giving this error 

[    c-scripting-core] Creating script environments for EasyAdmin
[ citizen-server-impl] Started resource EasyAdmin
cfx> [    c-resources-core] Could not find dependency webadmin for resource webadmin-lua.

ive looked around and cant seem to find the webadmin dep

**Comment by ynjn1** [comment]
i got the easyadmin from the github

**Comment by ynjn1** [comment]
[    c-resources-core] Could not find dependency webadmin for resource webadmin-lua.
[    c-resources-core] Could not find dependency webadmin for resource webadmin-lua.
[    c-resources-core] Could not start dependency webadmin-lua for resource wap-settings.
[    script:EasyAdmin] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export getFactory in resource webadmin-lua
[    script:EasyAdmin] EasyAdmin Version Check failed!

**Comment by Blumlaut** [comment]
no you didn't, your easyadmin is years out of date.

**Comment by ynjn1** [comment]
i just downloaded the newest version and same error pops up

**Comment by ynjn1** [comment]
![Screenshot 2022-02-11 055041](https://user-images.githubusercontent.com/96897966/153578970-33c6496c-0bd8-471c-9bfb-d793eb8e8b52.jpg)

**Comment by Blumlaut** [comment]
upload your full server log to pastebin.com and post it here, you are definetely NOT running the latest easyadmin version, webadmin has been removed years ago.

**Comment by ynjn1** [comment]
i am sorry for wasting your time there was a dup copy of a older version in this server setup i removed it and it started working  didnt know it was there until i checked
