### ISSUE TITLE
Discord Bot thing 6,6 release i thing

### ISSUE THREAD

**Issue by AlphaTheDev** [Blumlaut/EasyAdmin#331]
[    c-scripting-core] Creating script environments for EasyAdmin
[    script:EasyAdmin] 
[    script:EasyAdmin]  _______ _______ _______ __   __ _______ ______  _______ _____ __   _
[    script:EasyAdmin]  |______ |_____| |______   \_/   |_____| |     \ |  |  |   |   | \  |
[    script:EasyAdmin]  |______ |     | ______|    |    |     | |_____/ |  |  | __|__ |  \_|
[    script:EasyAdmin]                            Version 6.5 (UNSTABLE PRE-RELEASE!)
[    script:EasyAdmin] Error loading script server/bot/bot.js in resource EasyAdmin: Error: Cannot find module 'discord.js'
[    script:EasyAdmin] Require stack:
[    script:EasyAdmin] - C:/Users/Micas/Downloads/[ESX-Scripts]/[ESX-Filer]/Lagacy/esx-by-a1pha/resources//EasyAdmin/dummy.js
[    script:EasyAdmin] stack:
[    script:EasyAdmin] Error: Cannot find module 'discord.js'
[    script:EasyAdmin] Require stack:
[    script:EasyAdmin] - C:/Users/Micas/Downloads/[ESX-Scripts]/[ESX-Filer]/Lagacy/esx-by-a1pha/resources//EasyAdmin/dummy.js
[    script:EasyAdmin]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[    script:EasyAdmin]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[    script:EasyAdmin]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[    script:EasyAdmin]     at require (node:internal/modules/cjs/helpers:94:18)
[    script:EasyAdmin]     at @EasyAdmin/server/bot/bot.js:9:11
[    c-scripting-core] Failed to load script server/bot/bot.js.
[    script:EasyAdmin] Error loading script server/bot/functions.js in resource EasyAdmin: Error: Cannot find module 'discord.js'
[    script:EasyAdmin] Require stack:
[    script:EasyAdmin] - C:/Users/Micas/Downloads/[ESX-Scripts]/[ESX-Filer]/Lagacy/esx-by-a1pha/resources//EasyAdmin/dummy.js
[    script:EasyAdmin] stack:
[    script:EasyAdmin] Error: Cannot find module 'discord.js'
[    script:EasyAdmin] Require stack:
[    script:EasyAdmin] - C:/Users/Micas/Downloads/[ESX-Scripts]/[ESX-Filer]/Lagacy/esx-by-a1pha/resources//EasyAdmin/dummy.js
[    script:EasyAdmin]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[    script:EasyAdmin]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[    script:EasyAdmin]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[    script:EasyAdmin]     at require (node:internal/modules/cjs/helpers:94:18)
[    script:EasyAdmin]     at @EasyAdmin/server/bot/functions.js:3:19
[    c-scripting-core] Failed to load script server/bot/functions.js.
[ citizen-server-impl] Started resource EasyAdmin
[    script:EasyAdmin] EasyAdmin: You are using an unstable version of EasyAdmin, if this was not your intention, please download the latest stable version from https://github.com/Blumlaut/EasyAdmin/releases/tag/6.5

 this happends when i try to run easyadmin

**Comment by Blumlaut** [comment]
Are you missing yarn or webpack?
