### ISSUE TITLE
investigate discord claiming bot relogged too often

### ISSUE THREAD

**Issue by Blumlaut** [Blumlaut/EasyAdmin#332]
apparently this also happens for normal users while the bot is apparently running normally, not sure yet.

**Comment by Blumlaut** [comment]
might be fixed

**Comment by Blumlaut** [comment]
everyone that reported this issue decided to just disspear/ghost my follow ups so im assuming this is fixed.

**Comment by Blumlaut** [comment]
reopening this, this was apparently fixed in DJS but is pending a release.

**Comment by GrandpaRex** [comment]
Went into the discord.js discord and they said it is available in the dev release and will be in the v14 release

**Comment by Blumlaut** [comment]
> Went into the discord.js discord and they said it is available in the dev release and will be in the v14 release

we dont really want to install a dev release due possible bugs and not having any upgrading docs at this time

**Comment by Blumlaut** [comment]
If 14 takes a while to release I'll look into it, but I really don't want it to sit between 2 versions for any extended period of time

**Comment by Blumlaut** [comment]
https://github.com/Blumlaut/EasyAdmin/pull/339
