### ISSUE TITLE
Bot Status

### ISSUE THREAD

**Issue by Destructor** [Blumlaut/EasyAdmin#344]
![image](https://user-images.githubusercontent.com/1570770/158034528-761bc4e2-46f5-40a9-bc94-e207142f6de5.png)
![image](https://user-images.githubusercontent.com/1570770/158034535-201ae07e-27d0-4f50-8f78-66237faa5fba.png)
![image](https://user-images.githubusercontent.com/1570770/158034543-0d9eb952-e504-4476-94f7-72810f4e16b6.png)
![image](https://user-images.githubusercontent.com/1570770/158034548-264cea4a-172e-4c16-bc13-ecd556f522f5.png)

My bot have all perm

**Comment by Blumlaut** [comment]
You are likely missing intents, please refer to the docs.

**Comment by Destructor** [comment]
![image](https://user-images.githubusercontent.com/1570770/158034906-b0f45ea3-7476-4aa0-bbe7-423f8ef51c0c.png)
I just report the error the status works as same with the error displayed above

**Comment by Blumlaut** [comment]
> I just report the error the status works as same with the error displayed above

what?

**Comment by Destructor** [comment]
![image](https://user-images.githubusercontent.com/1570770/158035032-1eb5cbff-0319-4b05-95b8-5cfbf350bbcf.png)
I have this error but status work ^^

**Comment by Jaccosf** [comment]
> ![image](https://user-images.githubusercontent.com/1570770/158035032-1eb5cbff-0319-4b05-95b8-5cfbf350bbcf.png) I have this error but status work ^^

Litteraly this error means you need to do what @Blumlaut said...

**Comment by Destructor** [comment]
![image](https://user-images.githubusercontent.com/1570770/158035184-eb66905e-93ed-4619-bfac-b99c918eea5d.png)
All perm it's correct ....

**Comment by Jaccosf** [comment]
Use the link in https://easyadmin.readthedocs.io/en/latest/discordbot/#creating-the-bot-user and try again

**Comment by Destructor** [comment]
Humm ok tks

**Comment by Noobspielt** [comment]
in the URL are permissions that you need to run the bot right.  There are Permissions that you can't configure in the User/Role settings of your Discord Server
