### ISSUE TITLE
bug with  new  update 

### ISSUE THREAD

**Issue by ynjn1** [Blumlaut/EasyAdmin#346]
script:EasyAdmin] Error: S[50001]: Missing Access
[    script:EasyAdmin]     at Q.runRequest (/home/container/resources/[Scripts]/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:7:581)
[    script:EasyAdmin]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[    script:EasyAdmin]     at async Q.queueRequest (/home/container/resources/[Scripts]/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:5:2942)

**Comment by Blumlaut** [comment]
there is no "bug", read the docs.
https://easyadmin.readthedocs.io/en/latest/discordbot/
