### ISSUE TITLE
discord.js > updated it > new error present after 6.601 to 6.602

### ISSUE THREAD

**Issue by ViolentMinds** [Blumlaut/EasyAdmin#349]
6.602 gave me the outdated discord.js module so I updated it via npm in cmd. That was successful (so I thought) but now I am getting a new error:

`
[    script:EasyAdmin]                            Version 6.602
[    script:EasyAdmin] Error loading script server/bot/bot.js in resource EasyAdmin: TypeError: Class extends value undefined is not a constructor or null
[    script:EasyAdmin] stack:
[    script:EasyAdmin] TypeError: Class extends value undefined is not a constructor or null
[    script:EasyAdmin]     at Object.<anonymous> (C:\FXServer\txData\CFXDefault_184FBE.base\resources\[Admin]\EasyAdmin\node_modules\discord.js\src\structures\ActionRowBuilder.js:6:32)
[    script:EasyAdmin]     at Module._compile (node:internal/modules/cjs/loader:1101:14)
[    script:EasyAdmin]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[    script:EasyAdmin]     at Module.load (node:internal/modules/cjs/loader:981:32)
[    script:EasyAdmin]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[    script:EasyAdmin]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[    script:EasyAdmin]     at require (node:internal/modules/cjs/helpers:94:18)
[    script:EasyAdmin]     at Object.<anonymous> (C:\FXServer\txData\CFXDefault_184FBE.base\resources\[Admin]\EasyAdmin\node_modules\discord.js\src\index.js:74:28)
[    script:EasyAdmin]     at Module._compile (node:internal/modules/cjs/loader:1101:14)
[    script:EasyAdmin]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[    c-scripting-core] Failed to load script server/bot/bot.js.
[    script:EasyAdmin] Error loading script server/bot/chat_bridge.js in resource EasyAdmin: ReferenceError: client is not defined
[    script:EasyAdmin] stack:
[    script:EasyAdmin] ReferenceError: client is not defined
[    script:EasyAdmin]     at @EasyAdmin/server/bot/chat_bridge.js:64:5
[    c-scripting-core] Failed to load script server/bot/chat_bridge.js.
[    script:EasyAdmin] Error loading script server/bot/roles.js in resource EasyAdmin: ReferenceError: client is not defined
[    script:EasyAdmin] stack:
[    script:EasyAdmin] ReferenceError: client is not defined
[    script:EasyAdmin]     at @EasyAdmin/server/bot/roles.js:25:5
[    c-scripting-core] Failed to load script server/bot/roles.js.
[    script:EasyAdmin] Error loading script server/bot/server_status.js in resource EasyAdmin: ReferenceError: client is not defined
[    script:EasyAdmin] stack:
[    script:EasyAdmin] ReferenceError: client is not defined
[    script:EasyAdmin]     at @EasyAdmin/server/bot/server_status.js:118:5
[    c-scripting-core] Failed to load script server/bot/server_status.js.`

These items were defined via convars in server.cfg. 6.601 was actually working for me but now I cannot do much else. Not sure if its a known bug or not thus I am reporting it just in case.

Should I manually define these items in those files if it cannot read it from convars?

**Comment by Blumlaut** [comment]
you shouldn't install discordjs manually, delete your node modules, yarn lock and yarn installed file and restart the server.
