### ISSUE TITLE
Status Message

### ISSUE THREAD

**Issue by Dark3581** [Blumlaut/EasyAdmin#350]
Hello, I am here to report an issue where EasyAdmin indefinitely try to Fetch Server info but is not fetching it
![image](https://user-images.githubusercontent.com/67527731/158477326-494d9c33-d4fc-44ea-987a-c830f4d089bc.png)

**Comment by Blumlaut** [comment]
Can you check the server console for errors? Make sure you are **at least** on 6.603

**Comment by Dark3581** [comment]
This is what console says, from the looks no erros
![image](https://user-images.githubusercontent.com/67527731/158477482-e1a4953d-01fe-4a6f-9f49-2a7e67f80241.png)

**Comment by Blumlaut** [comment]
What easyadmin version are you on?

**Comment by Dark3581** [comment]
6.603

**Comment by Blumlaut** [comment]
can you upload the entire log to something like pastebin.com?

**Comment by Dark3581** [comment]
Yeah sure just give me a second

**Comment by Dark3581** [comment]
Okay well, I don't know what I did but I just set up txAdmin on this specific server and it started working, I am guessing this server status fetches from tx admin then?

**Comment by Blumlaut** [comment]
> I am guessing this server status fetches from tx admin then?

no

**Comment by Dark3581** [comment]
So strange then lol

**Comment by Dark3581** [comment]
Thanks though c:
