### ISSUE TITLE
EasyAdmin offline ban

### ISSUE THREAD

**Issue by Link2366** [Blumlaut/EasyAdmin#356]
Offline bans sometimes doesn't work. So when someone LTAP (Leaves to avoid punishment) 95% of the time it doesn't seem to even ban them

**Comment by Blumlaut** [comment]
> Offline bans sometimes doesn't work

again with the "sometimes", repro?



> 95% of the time it doesn't seem to even ban them

ok... repro? any infos? errors? these reports are useless if you just say "sometimes this happens" and we cant reproduce it.
