### ISSUE TITLE
error with cache

### ISSUE THREAD

**Issue by Hurstzy** [Blumlaut/EasyAdmin#359]
[    script:EasyAdmin] Error: failed to fetch member roles, despite having fetched the member, please report the following stack trace to https://github.com/Blumlaut/EasyAdmin/issues
[    script:EasyAdmin] Error: member: <@859923687029211157>,<@776934906755416104>,<@610258921592193024>,<@!851925969269686303>,<@646269898791714816>,<@!245386022265815041>,<@714535231788548098>,<@792164602463911937>,<@937116053614518292>,<@661952374457237528>,<@943470630030962708>,<@852998301446832148>,<@233788020891844609>,<@954290288015331388>,<@953127019951050854>,<@939463886514573344>,<@908804689397698640>,<@514922866400034858>,<@949474635928444948>,<@954215416127979610>,<@954505318581276722>,<@947301777957589052>,<@913104444412031036>,<@352699395382181898>,<@843209246987649044>,<@887988990324637718>,<@797292321329774612>,<@483787947070586880>,<@159985870458322944>,<@702242096077340773>,<@738770040651776104>,<@522182178918891521>,<@704055709788143658>,<@952260246129234014>,<@763098292488896553>,<@954864885433516093>,<@469336125836886017>,<@948247419685052496>,<@834176877068419082>,<@801567287768514580>,<@950501569013633135>,<@278676072659288064>,<@954241209134633020>,<@726308955000799252>,<@!457248129352204310>,<@947218146547339345>,<@947758297417670667>,<@805166218737745991>,<@475129458613813248>,<@954593864092622918>,<@610630966657941504>,<@946638460779913236>,<@781395718010437652>,<@844109158764249128>,<@902014758377623605>,<@472218052793204736>,<@954851466437328916>,<@912201072645373982>,<@498791247998222346>,<@954193720843075584>,<@926675965545947136>,<@954520530675986572>,<@!764589462143238175>,<@580153614740226058>,<@881705135888289832>,<@!773376937318023168>,<@945196572768084028>,<@!543187726082637824>,<@938173294975258715>,<@759973818671824937>,<@557628352828014614>,<@900240860468359190>,<@671683698411962369>,<@798206924587794502>,<@695664615534755850>,<@799286659819634730>,<@891783853931380776>,<@347444963031646211>,<@790647773606707240>,<@946635509940244510>,<@!547706848686637061>,<@368105370532577280>,<@944845444150870047>,<@744598439622606929>,<@349615144537554954>,<@573860799639060490>,<@954570485935530036>,<@944857084749574186>,<@715686542504624159>,<@889227180763144262>,<@743284418344386641>,<@827083496551874562>,<@702024024322080880>,<@933120263158128660>,<@795501847237623808>,<@612413110929588225>,<@939214545459740682>,<@889323681753468929>,<@383718488310677504>,<@855242003218300949>,<@825183958575611914>,<@950857117835853894>,<@948130382103085106>,<@521828547384573965>,<@576330163558678542>,<@696102296387584042>,<@557417409531609088>,<@411252081404411908>,<@723357239687118939>,<@954204299859206184>,<@!639862123593334784>,<@830737409276510238>,<@664535555475898428>,<@437433759323914241>,<@954134944240775168>,<@353101775852535809>,<@896123113933271070>,<@!710177925852299354>,<@844813973538603039>,<@635047070968971274>,<@945122369280835634>,<@948686692611674182>,<@954432065254862879>,<@711452073794994209>,<@703786863583952896>,<@793947095542530089>,<@759336470132817921>,<@924009567891914802>,<@254059424560185346>,<@942627882180702279>,<@792446502176817152>,<@897703043326443540>,<@!721851850910859324>,<@794754571541020693>,<@954865083438223390>,<@844820170106470400>,<@!668232138239246336>,<@637357860904501248>,<@769744984681218058>,<@954210949257121864>,<@741723398912344136>,<@755477859572646029>,<@827188727192616961>,<@913642496804929586>,<@638274393424003084>,<@693946259005898772>,<@686365227100536843>,<@!204221589883977728>,<@948414313096425483>,<@310267682526330880>,<@783785704386986005>,<@947328489130962984>,<@953683961450754158>,<@677168836998332437>,<@652240082048122896>,<@!640084042603167750>,<@396200397217202176>,<@954555156182212638>,<@308301740439109632>,<@439174808366874625>,<@842453453049692170>,<@378037884856434689>,<@778638421815591012>,<@574161159805075477>,<@941132440121004053>,<@949139827398434817>,<@665351230863835136>,<@832532301476266014>,<@656003068126560296>,<@894613373931638815>,<@594917697381203982>,<@950866668966510602>,<@714282799078572093>,<@569861576035926028>,<@692087974443352104>,<@706638162939609121>,<@950597397279567872>,<@417096318306222092>,<@797515903411552306>,<@909216294191136798>,<@711493566756814850>,<@819625649257185301>,<@911087900748312616>,<@894022756763594772>,<@451041720210292756>,<@793977221094047796>,<@768850687383044106>,<@315215266604777474>,<@594709657948258315>,<@927572708856844298>,<@766677525488861195>,<@945534322746740746>,<@933264290188767232>,<@359495054898757632>,<@!438002942663065610>,<@876131460887748699>,<@425615733511421962>,<@951838000919240794>,<@696859667501940778>,<@645662531305603080>,<@!911810157980311603>,<@711811011249963029>,<@675859246826520587>,<@954411547432722463>,<@894697994669158421>,<@699340688151674970>,<@640894318923743242>,<@833823776525254758>,<@760884384789561424>,<@667575907569106979>,<@954273994121568286>,<@806081619731283989>,<@772277566522392606>,<@895789002429448194>,<@794801460172030012>,<@798942869549219860>,<@926371087007232040>,<@675460627384238089>,<@!754009338967883846>,<@773875735672520704>,<@899810798686339083>,<@775394238502142012>,<@954519453566107669>,<@812444197508481047>,<@448299546343374860>,<@256982535643332619>,<@655864964317184001>,<@265571003894071296>,<@536284318729764874>,<@!445688950363914240>,<@!730047364177330226>,<@!950237198249263144>,<@936721104167374928>,<@717362627994583062>,<@774051890358648874>,<@806041752166465576>,<@938441476751392798>,<@917922865641312276>,<@892355711529529344>,<@721546032084942908>,<@949308615917969448>,<@402882914976661505>,<@798269028899618816>,<@345850518876192779>,<@442680283414659074>,<@927363930588864514>,<@502507272384020500>,<@694533326647722084>,<@915551905969733683>,<@953456025372094524>,<@835427312899588116>,<@401736908427755531>,<@770113420963348510>,<@572139492329390081>,<@787618592514244658>,<@!746092090802307154>,<@451379187031343104>,<@361955617168031746>,<@850077448325431346>,<@867826574190968892>,<@928818978292371506>,<@898691262583013466>,<@685355650183594047>,<@718692274598445116>,<@491769129318088714>,<@862751983113994261>,<@481198598919290881>,<@841514557612621874>,<@517127861631582208>,<@598464551222247425>,<@795685959030407188>,<@953532579787714571>,<@852768952001888316>,<@897219228439031858>,<@629319877311594496>,<@839338360240603148>,<@551497029143232531>,<@!730274039750197372>,<@947314501689176167>,<@944859391050518548>,<@309313962925621251>,<@932075574514548846>,<@429361517410910208>,<@820952135743176724>,<@268500281510199298>,<@339860752011755522>,<@812701152646004787>,<@808889891990798406>,<@920722250527834214>,<@450774946667429918>,<@432256478989123617>,<@361704922451804162>,<@924421464994754571>,<@869323860078641223>,<@954152390670565436>,<@881596272585363516>,<@954099354778632202>,<@534878523891122176>,<@933156639480094830>,<@312256025690374147>,<@!696064266549198978>,<@527317599164432394>,<@924362826473160744>,<@911768424600969246>,<@929556428270764063>,<@954678785645633586>,<@949429136450015233>,<@!531270030357430323>,<@!471431952809852928>,<@954849034928021624>,<@799185255839039488>,<@!752111967208079360>,<@943471418232934401>,<@753840324740382761>,<@!792131963733016607>,<@692135374427914280>,<@679026398089838611>,<@940487872740483093>
[    script:EasyAdmin] Error: TypeError: Cannot read properties of undefined (reading 'cache')
[    script:EasyAdmin]     at Object.syncDiscordRoles [as callback] (@EasyAdmin/server/bot/roles.js:19:40)
[    script:EasyAdmin]     at runMicrotasks (<anonymous>)
[    script:EasyAdmin]     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Blumlaut** [comment]
please update to the latest version before reporting bugs, this was fixed in 6.404.
