### ISSUE TITLE
failed to fetch member roles.

### ISSUE THREAD

**Issue by V3SC** [Blumlaut/EasyAdmin#361]
https://prnt.sc/1G_ualfOSdw8
https://prnt.sc/r8I7Fo0WkLDT

i don't know that's that mean but I just wanted to report.

**Comment by Blumlaut** [comment]
Update your EasyAdmin to 6.604.

**Comment by V3SC** [comment]
> Update your EasyAdmin to 6.604.

I updated yesterday.

**Comment by Blumlaut** [comment]
> > Update your EasyAdmin to 6.604.
> 
> I updated yesterday.

and yet, the error you reported cannot happen like this, how about that?
