### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Shadowre123** [Blumlaut/EasyAdmin#365]
Hi! i have a issue with the discord bot, i put here the code error.
[ script:EasyAdmin] Logged in as EasyAdmin#7476!
[ script:EasyAdmin] Bot is in beta! Please report any bugs at https://github.com/Blumlaut/EasyAdmin/issues
[ script:EasyAdmin] Error: Failed to set bot commands, you likely didn't invite the bot correctly, please kick the bot and re-invite with the link here:
[ script:EasyAdmin] https://easyadmin.readthedocs.io/en/latest/discordbot/#inviting-the-bot
[ script:EasyAdmin]
[ script:EasyAdmin]
[ script:EasyAdmin] Error: S[20012]: You are not authorized to perform this action on this application
[ script:EasyAdmin] at Q.runRequest (/home/zap901248/g465681/gta5-fivem/server-data/resources/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:7:581)
[ script:EasyAdmin] at processTicksAndRejections (node:internal/process/task_queues:96:5)
[ script:EasyAdmin] at async Q.queueRequest (/home/zap901248/g465681/gta5-fivem/server-data/resources/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:5:2942)

**Comment by Blumlaut** [comment]
do what the error message tells you?
```
[ script:EasyAdmin] Error: Failed to set bot commands, you likely didn't invite the bot correctly, please kick the bot and re-invite with the link here:
[ script:EasyAdmin] https://easyadmin.readthedocs.io/en/latest/discordbot/#inviting-the-bot
```
