### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by 13LuckyBack** [Blumlaut/EasyAdmin#368]
Hello,
I am trying to get the webhooks working but it is not working.
I placed it in my cfg file like in the docs
set ea_reportNotification "https://discord.com/api/webhooks/957606638989217822/OVMjFoiX6C46ymH9yKRa50uCvCwzEDNHPjJgmDUT83JMNxy0FJEC4xyCWhbI8ldUrq24"

But this is not working tho
How can i fix this?

**Comment by Blumlaut** [comment]
you already created a post in discord.
