### ISSUE TITLE
Feature additions for ATG AntiCheat

### ISSUE THREAD

**Issue by LenineStudio50490** [Blumlaut/EasyAdmin#369]
Feature additions for ATG AntiCheat

Hello, 
I wanted to know if they were possible to make your script work with ATG I know that the version 5 yes but not the rest Thank you in advance for your answer 
Sincerely

**Comment by Noobspielt** [comment]
aren't there exports that u can use?

**Comment by Blumlaut** [comment]
... what? there is nothing we can even do about this, easyadmin has an api which resources can freely use, this is not something for us to implement.

**Comment by Noobspielt** [comment]
Why should be work done on easyadmin be compatible with other software lol.

**Comment by LenineStudio50490** [comment]
I do not understand your reticence on this subject.

I understand well that the developers only take care of their script and give APIs to me to change the mind of the creator of ATG if I understand well your statement.
