### ISSUE TITLE
widescreen issue

### ISSUE THREAD

**Issue by ZuidLimburg** [Blumlaut/EasyAdmin#372]
I had a issue with widescreens, the menu did show half on screen so we changed something in client.lua line 30

function handleOrientation(orientation)
   	if orientation == "right" then
		local ScreenW, ScreenH = GetScreenResolution()
		local MenuSize = 200
		local MenuOffset = ScreenW - (MenuSize / 2)
		return MenuOffset
	elseif orientation == "middle" then
		return 730
	elseif orientation == "left" then
		return 0
	end
end

**Comment by Blumlaut** [comment]
...what? is this a bug report, a pull request? If its a pull request, why did you randomly paste code here?

**Comment by ZuidLimburg** [comment]
lel sorry didn't know where to paste it
