### ISSUE TITLE
Announce cmd

### ISSUE THREAD

**Issue by matiasdelbulla** [Blumlaut/EasyAdmin#378]
the announce command does not have validation of permissions, I leave the record so that those who use the script know it, I do not leave the code of the (admin_server.lua) solved since I am on the cell phone, tomorrow I will attach the fixed error

**Comment by matiasdelbulla** [comment]
RegisterCommand("announce", function(source, args, rawCommand)
		local reason = table.concat(args, " ")
if DoesPlayerHavePermission(source, "server.announce") then
		announce(reason)
End
	end, false)

I leave the cmd with permissions, this is more to say that they need to add the "server.announce" permission to use the cmd but all users no longer have access to the command

**Comment by Blumlaut** [comment]
who the fuck added that there anyway, @Jaccosf?

**Comment by Blumlaut** [comment]
thanks for the report, i'm rushing a new release now, i have no idea why this was even added, there should not be an announce command at all.
