### ISSUE TITLE
Discord ban info command?

### ISSUE THREAD

**Issue by V3SC** [Blumlaut/EasyAdmin#379]
A command that we can use in Discord and get information about the ban.

/baninfo {banid}

Ban ID : x
Reason : x
Player Name : x
Banner: x
Expire : x

**Comment by Blumlaut** [comment]
will be part of 6.7, the picture displayed is the discord avatar of the banned user.
![image](https://user-images.githubusercontent.com/13604413/168804182-dfe65cab-9247-4dec-a603-7b78f44287b9.png)
