### ISSUE TITLE
Sudden error after 6.608 update from 6.607

### ISSUE THREAD

**Issue by ViolentMinds** [Blumlaut/EasyAdmin#384]
Just updated from 6.607 > 6.608 now I'm getting this error. Not sure how to fix it?

[      script:oxmysql] Database server connection established!
> restart EasyAdmin
[ citizen-server-impl] Stopping resource EasyAdmin
[    c-scripting-core] Creating script environments for EasyAdmin
[    script:EasyAdmin] 
[    script:EasyAdmin]  _______ _______ _______ __   __ _______ ______  _______ _____ __   _
[    script:EasyAdmin]  |______ |_____| |______   \_/   |_____| |     \ |  |  |   |   | \  |
[    script:EasyAdmin]  |______ |     | ______|    |    |     | |_____/ |  |  | __|__ |  \_|
[    script:EasyAdmin]                            Version 6.608
[ citizen-server-impl] Started resource EasyAdmin
[ citizen-server-impl] server thread hitch warning: timer interval of 799 milliseconds
[    script:EasyAdmin] SCRIPT ERROR in promise (unhandled): Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
[    script:EasyAdmin] > WebSocketManager.createShards (C:\FXServer\txData\CFXDefault_184FBE.base\resources\[Admin]\EasyAdmin\node_modules\discord.js\src\client\websocket\WebSocketManager.js:254)
[    script:EasyAdmin] > async Client.login (C:\FXServer\txData\CFXDefault_184FBE.base\resources\[Admin]\EasyAdmin\node_modules\discord.js\src\client\Client.js:231)
[    script:EasyAdmin] 
[    script:EasyAdmin] SCRIPT ERROR in promise (unhandled): Error: Expected token to be set for this request, but none was present
[    script:EasyAdmin] > V.resolveRequest (C:\FXServer\txData\CFXDefault_184FBE.base\resources\[Admin]\EasyAdmin\node_modules\discord.js\node_modules\@discordjs\rest\dist\index.js:7)
[    script:EasyAdmin] > V.queueRequest (C:\FXServer\txData\CFXDefault_184FBE.base\resources\[Admin]\EasyAdmin\node_modules\discord.js\node_modules\@discordjs\rest\dist\index.js:7)
[    script:EasyAdmin] > Y.request (C:\FXServer\txData\CFXDefault_184FBE.base\resources\[Admin]\EasyAdmin\node_modules\discord.js\node_modules\@discordjs\rest\dist\index.js:7)
[    script:EasyAdmin] > Y.get (C:\FXServer\txData\CFXDefault_184FBE.base\resources\[Admin]\EasyAdmin\node_modules\discord.js\node_modules\@discordjs\rest\dist\index.js:7)
[    script:EasyAdmin] > ChannelManager.fetch (C:\FXServer\txData\CFXDefault_184FBE.base\resources\[Admin]\EasyAdmin\node_modules\discord.js\src\managers\ChannelManager.js:117)
[    script:EasyAdmin] > updateServerStatus (@EasyAdmin/server/bot/server_status.js:97)
[    script:EasyAdmin]

**Comment by V3SC** [comment]
Happened to me too today.  I created a new bot.
