### ISSUE TITLE
add: Spamming with notification of unclaimed reports like every 1min/5min

### ISSUE THREAD

**Issue by KamCio401** [Blumlaut/EasyAdmin#397]
Woud be nice to see this feature : Spamming with notification of unclaimed reports like every 1min/5min

**Comment by Blumlaut** [comment]
...what?

can you use proper sentences and maybe an example to describe what you want added

> Woud be nice to see this feature

.. do you also write emails like this?

**Comment by Blumlaut** [comment]
since this wasnt fixed, issue closed, write a proper description.
