### ISSUE TITLE
Getting errors when setting bot but then it dont make sense to me how to set it up.. a video would be great not little clips.. 

### ISSUE THREAD

**Issue by k13ran2021** [Blumlaut/EasyAdmin#401]
[    script:EasyAdmin] SCRIPT ERROR in promise (unhandled): Error: Expected token to be set for this request, but none was present
[    script:EasyAdmin] > _RequestManager.resolveRequest (/home/zap782835/g423719/gta5-fivem-txadmin/PlumeESXLegacy_B40180.base/resources/EasyAdmin/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:798)
[    script:EasyAdmin] > _RequestManager.queueRequest (/home/zap782835/g423719/gta5-fivem-txadmin/PlumeESXLegacy_B40180.base/resources/EasyAdmin/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:770)
[    script:EasyAdmin] > REST.request (/home/zap782835/g423719/gta5-fivem-txadmin/PlumeESXLegacy_B40180.base/resources/EasyAdmin/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:907)
[    script:EasyAdmin] > REST.get (/home/zap782835/g423719/gta5-fivem-txadmin/PlumeESXLegacy_B40180.base/resources/EasyAdmin/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:892)
[    script:EasyAdmin] > ChannelManager.fetch (/home/zap782835/g423719/gta5-fivem-txadmin/PlumeESXLegacy_B40180.base/resources/EasyAdmin/node_modules/discord.js/src/managers/ChannelManager.js:117)
[    script:EasyAdmin] > updateServerStatus (@EasyAdmin/server/bot/server_status.js:97)
[    script:EasyAdmin]

**Comment by Blumlaut** [comment]
you did not configure the bot token.
