### ISSUE TITLE
getting these errors after updating easyadmin

### ISSUE THREAD

**Issue by k13ran2021** [Blumlaut/EasyAdmin#402]
[    script:EasyAdmin] 
[    script:EasyAdmin]  _______ _______ _______ __   __ _______ ______  _______ _____ __   _
[    script:EasyAdmin]  |______ |_____| |______   \_/   |_____| |     \ |  |  |   |   | \  |
[    script:EasyAdmin]  |______ |     | ______|    |    |     | |_____/ |  |  | __|__ |  \_|
[    script:EasyAdmin]                            Version 6.608
[    script:EasyAdmin] Error loading script server/bot/bot.js in resource EasyAdmin: Error: Cannot find module 'ascii-table'
[    script:EasyAdmin] Require stack:
[    script:EasyAdmin] - /home/zap782835/g423719/gta5-fivem-txadmin/PlumeESXLegacy_B40180.base/resources//EasyAdmin/dummy.js
[    script:EasyAdmin] stack:
[    script:EasyAdmin] Error: Cannot find module 'ascii-table'
[    script:EasyAdmin] Require stack:
[    script:EasyAdmin] - /home/zap782835/g423719/gta5-fivem-txadmin/PlumeESXLegacy_B40180.base/resources//EasyAdmin/dummy.js
[    script:EasyAdmin]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[    script:EasyAdmin]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[    script:EasyAdmin]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[    script:EasyAdmin]     at require (node:internal/modules/cjs/helpers:94:18)
[    script:EasyAdmin]     at @EasyAdmin/server/bot/bot.js:9:14
[    c-scripting-core] Failed to load script server/bot/bot.js.
[    script:EasyAdmin] Error loading script server/bot/chat_bridge.js in resource EasyAdmin: ReferenceError: client is not defined
[    script:EasyAdmin] stack:
[    script:EasyAdmin] ReferenceError: client is not defined
[    script:EasyAdmin]     at @EasyAdmin/server/bot/chat_bridge.js:67:1
[    c-scripting-core] Failed to load script server/bot/chat_bridge.js.
[    script:EasyAdmin] Error loading script server/bot/server_status.js in resource EasyAdmin: ReferenceError: client is not defined
[    script:EasyAdmin] stack:
[    script:EasyAdmin] ReferenceError: client is not defined
[    script:EasyAdmin]     at @EasyAdmin/server/bot/server_status.js:132:1
[    c-scripting-core] Failed to load script server/bot/server_status.js.

**Comment by Blumlaut** [comment]
delete yarn.installed and yarn.lock files inside easyadmin folder.
