### ISSUE TITLE
Bot: Identifier fallback 

### ISSUE THREAD

**Issue by Noobspielt** [Blumlaut/EasyAdmin#405]
Currently if a User doesn't have steam running, the bot will print ~No Identifier~.
I think it would be better if the the bot had some fallback identifier like discord or the license

**Comment by Blumlaut** [comment]
this would probably best to have a fallback list like

```
set ea_logIdentifier "discord,steam,license"
```

**Comment by Blumlaut** [comment]
used this as an excercise for GitHub Copilot, see for yourself, neat, huh?
