### ISSUE TITLE
Teleport me back issue.

### ISSUE THREAD

**Issue by Fusiixns** [Blumlaut/EasyAdmin#408]
So I have moderator roles within a RP server that I play, we use EasyAdmin for reports. teleporting and ban's/kicks but the only issue I have with it is that when I press teleport me back (after teleporting to a issue thats been reported) it just put's me back to where I teleported to, not where I teleported from. Does anyone else have the same issue or possibly have a fix for it? Thanks.

**Comment by Blumlaut** [comment]
the teleport back option is kinda weird at this point, theres probably some weird bug in there which i cant really test on my own.
can you try this commit:
https://github.com/Blumlaut/EasyAdmin/commit/2e8e468da3339e5d033be091723b315d31fd0aa0

**Comment by Blumlaut** [comment]
Bump, could you test this please?

**Comment by Blumlaut** [comment]
Bump, once more, please dont abandon issues you create @Fusiixns if there's no reply i'll close this issue and revert the change.

**Comment by Fusiixns** [comment]
My bad bud! I’ve been on holiday. I’m unable to check on this issue anymore as I am no longer a staff member in the server that had the issue. I can try and get a local server running with a friend to see if it works or if it was just an issue with that one server.

**Comment by Blumlaut** [comment]
closing this since if you're not going to test the commit, theres no point keeping this issue, commit has been reverted.
