### ISSUE TITLE
Problem EasyAdmin 6.7

### ISSUE THREAD

**Issue by krasser88** [Blumlaut/EasyAdmin#421]
![Screenshot_38](https://user-images.githubusercontent.com/77132832/173859853-15e4f7bb-cd22-43ab-9ee5-9a92c801568f.png)

when I restart server it says it can't find the resource... I'm using Server Version: 10.3.34-MariaDB-0+deb10u1 - Debian 10 Esx Legacy I'm using please help

[ citizen-server-impl] Couldn't start resource EasyAdmin.
[ citizen-server-impl] server thread hitch warning: timer interval of 187 milliseconds
yarn install v1.21.0
info No lockfile found.
[1/4] Resolving packages...
warning discord.js@14.0.0-dev.1649505803-3c0bbac: no longer supported
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Ignored scripts due to flag.
success Saved lockfile.
Done in 4.93s.

fx server v4.14.1 atop FXServer 5589
esyadmin6.7
![Screenshot_38](https://user-images.githubusercontent.com/77132832/173859563-73a0d38d-9be1-4d58-b324-e79148dacc55.png)

**Comment by Blumlaut** [comment]
> when I restart server it says it can't find the resource
nowhere does it say that.

> 10.3.34-MariaDB
???

Fill in the template, and provide a full log.

**Comment by krasser88** [comment]
![Screenshot_38](https://user-images.githubusercontent.com/77132832/173862672-c1d21c8e-537b-4849-8f6a-46217435e476.png)
sorry my english is not so good

**Comment by krasser88** [comment]
[fxserver_1655305929.log](https://github.com/Blumlaut/EasyAdmin/files/8910691/fxserver_1655305929.log)
[esx.pack.zip](https://github.com/Blumlaut/EasyAdmin/files/8910692/esx.pack.zip)
[trainer.pack.zip](https://github.com/Blumlaut/EasyAdmin/files/8910693/trainer.pack.zip)
[smalltrainer.pack (2).zip](https://github.com/Blumlaut/EasyAdmin/files/8910694/smalltrainer.pack.2.zip)
[smalltrainer.pack (1).zip](https://github.com/Blumlaut/EasyAdmin/files/8910695/smalltrainer.pack.1.zip)
[MintyAC.pack.zip](https://github.com/Blumlaut/EasyAdmin/files/8910696/MintyAC.pack.zip)
[hito_hud (2).zip](https://github.com/Blumlaut/EasyAdmin/files/8910697/hito_hud.2.zip)

**Comment by krasser88** [comment]
sorry my english is not so good

**Comment by Blumlaut** [comment]
locked for leaking paid resources, you are no longer eligable for support here.
