### ISSUE TITLE
Ids Above Head

### ISSUE THREAD

**Issue by nizmogr** [Blumlaut/EasyAdmin#423]
It would be very helpfull to have an option to be able to watch Ids above head all the time so that staff could see every players ID to be able to find them in logs, easyadmins menu etc. and also it would be usefull to find cheaters easier. I have seen this in servers and you can even see IDs even when cheaters are using noclip.

**Comment by Blumlaut** [comment]
Please use the template:

```
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

```

it exists for a reason.
