### ISSUE TITLE
Perm ban and temp ban permissions

### ISSUE THREAD

**Issue by Bissen569** [Blumlaut/EasyAdmin#43]
Would it be possible to have permisions specificly for perm and temp ban, so that you can set moderators to only be able to temp ban and admins can temp and perm ban ?

**Comment by Bluethefurry** [comment]
banning is one single permission, however i might be able to split it up, i'll add it to the "far away" milestone for now.

**Comment by Bluethefurry** [comment]
also: since technically, permanent bans are also "temporary", this is would require ban times having special flags too.

**Comment by jefff1111111111111** [comment]
how do i unban

**Comment by Blumlaut** [comment]
this will never happen
