### ISSUE TITLE
Moving notifications box for /reports

### ISSUE THREAD

**Issue by 43streak** [Blumlaut/EasyAdmin#430]
**Describe the issue**
I've looked so much into the script but cannot find anywhere to change the location where the easyadmin reports/calladmins are coming up. It is overlapping our HUD and we cannot see it. I'm just wondering if anyone knows the location of where to change this or if it's possible or not?

**Attempted Solutions**
I've gone through every file and idk if I'm just blind but I can't find any place to move the location of it.

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

**Server Infos (please complete the following information):**
 - OS: Windows Server 2019
 - FXServer Version = 2545
 - EasyAdmin Version = most recent

**Additional context**

**Comment by Blumlaut** [comment]
> most recent

this is not an actual version number.

> reports/calladmins are coming up. It is overlapping our HUD and we cannot see it. 

They are using the native GTA V Notifications, if you install either pNotify, t-notify or mythic-notify, then EasyAdmin will use those automatically.
