### ISSUE TITLE
Everyone is immune

### ISSUE THREAD

**Issue by asciidude** [Blumlaut/EasyAdmin#434]
**Describe the issue**
Hi again! Everyone is immune with EasyAdmin (unsure if members are too).

**Attempted Solutions**
Changing permissions, removing group inheritance, etc. I can't even kick trial moderators lol

**Server Infos (please complete the following information):**
 - OS: [e.g. Windows Server 2019, Debian 10..] Ubuntu 20.04
 - FXServer Version [e.g. 5123]: latest
 - EasyAdmin Version: latest

**Comment by Blumlaut** [comment]
> FXServer Version [e.g. 5123]: latest
> EasyAdmin Version: latest

... no? 

also, you are likely giving them the `easyadmin.immune` permission.

**Comment by asciidude** [comment]
Oof you're right.. 
![image](https://user-images.githubusercontent.com/39356292/179605283-879c870e-3227-4681-9b15-cc4171fc4dec.png)

Dumb mistake of mine 😂
