### ISSUE TITLE
[BUG] Teleport to Player does not work

### ISSUE THREAD

**Issue by NoobSpielt** [Blumlaut/EasyAdmin#439]
**Describe the bug**
If you try to teleport to a player and he is not near you it won't teleport you. It will just teleport you a little bit higher but you are still in the same place as before.

**To Reproduce**
1. Go far away from the target player. (e.g you are in Los Santos and the target player is in Sandy Shores)
3. Teleport yourself to the player

**Expected behavior**
I get teleportet to the target player

**Screenshots/Logs**
No Error logs (client/server).

**Server Infos (please complete the following information):**
 - OS: Red Hat Enterprise Linux release 8.6 (Ootpa)
 - FXServer Version 5715
 - EasyAdmin Version 6.8

**Additional context**
Teleport Player to me is working completely fine

**Comment by NoobSpielt** [comment]
Info: This bug just happening sometimes. After some ressource start/restarts its working and sometimes not.
I am trying to collect more Infos. Will post here if I find some more

**Comment by Blumlaut** [comment]
this function always uses `EasyAdmin:TeleportAdminToPlayer` if onesync is on:
https://github.com/Blumlaut/EasyAdmin/blob/master/server/admin_server.lua#L413

make sure you have onesync set to _on_, not legacy.

**Comment by NoobSpielt** [comment]
Already checked when the error occured the first time. OneSync was on.

I had also tried the teleport player to me function. It worked without a error (I assume you need Onesync for it to).

**Comment by NoobSpielt** [comment]
This seems like a one time error. I can't reproduce the error to.  It happened only one time so I don't  think this is related to EA.

I think it would be better to close this issue for now and reopen / open a new one if the error happens again.
