### ISSUE TITLE
[BUG] Spectating

### ISSUE THREAD

**Issue by iSentrie** [Blumlaut/EasyAdmin#448]
**Describe the bug**
Tried spectate a player and he disconnected EasyAdmin broke and couldn't open menu anymore.

**To Reproduce**
1. Spectate player
2. Switch on player who will disconnect
3. Script breaks

**Expected behavior**
Continue to work and spectate other players.

**Logs**
```
EasyAdmin^7: ESX didn't provide any Infos for Player ID 293, they might not be loaded in yet, or your ESX is broken. Please check your Server Console.^7
SCRIPT ERROR: @EasyAdmin/client/gui_c.lua:790: attempt to index a nil value (field '?')^7
```

**Server Infos:**
 - OS: Windows 11 x64
 - FXServer Version: 5687
 - EasyAdmin Version: 6.81

**Comment by Blumlaut** [comment]
Thanks for the report!
this is very odd indeed, the error you sent seems to happen during menu generation for some reason, instead of being in the spectate code.

will try and reproduce this myself in a bit.
