### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by johnsmith600** [Blumlaut/EasyAdmin#449]
**Describe the bug**
each time i refresh the server list it comes up with this 
[    c-resources-core] Resource loading for EasyAdmin failed:
[    c-resources-core] Could not open resource metadata file - no such file.

**To Reproduce**
1. Go to 'refresh the resource list'
2. Click on 'N/A'
3. Scroll down to 'the bottom of the live console'

**Expected behavior**
i expected the script to be able to start but all i get is 
[    c-resources-core] Resource loading for EasyAdmin failed:
[    c-resources-core] Could not open resource metadata file - no such file.
and it doesnt pickup that easyadmin is in the server.

**Screenshots/Logs**
![Screenshot 2022-07-25 220717](https://user-images.githubusercontent.com/105131296/180774147-78ca1267-76f8-4630-8c6f-772f04316155.png)

**Server Infos (please complete the following information):**
 -txadmin: we use txadmin as the source of running the server zap hosting to put it on the list
 - FXServer Version [newest]
 - EasyAdmin Version: 6.81

**Comment by Blumlaut** [comment]
you didnt install EasyAdmin correctly if the manifest is missing, not a bug.

**Comment by johnsmith600** [comment]
i did the manifest is there

**Comment by johnsmith600** [comment]
i reinstalled it 4 times and it said the exact same thing

**Comment by tristencommunity** [comment]
Then you're doing something wrong when installing it. There are tutorials you can read and/or watch that help you with the entire installation of EasyAdmin on YouTube and the cfx.re forums.

**Comment by johnsmith600** [comment]
i litteraly just reinstalled it and its saying the exact same thing
i also just dragged the fxmanifest into it and the same thing

**Comment by johnsmith600** [comment]
just happened

**Comment by johnsmith600** [comment]
ive installed it before and no issues but this time it isnt working

**Comment by johnsmith600** [comment]
just watched a video on it and its exactly what i did @Blumlaut

**Comment by johnsmith600** [comment]
[fxmanifest.txt](https://github.com/Blumlaut/EasyAdmin/files/9182550/fxmanifest.txt)
had to rename it to txt to upload it here

**Comment by tristencommunity** [comment]
if it was exactly what you did, it wouldnt be having issues.

what i recommend doing is figuring out what you changed that broke easyadmin because you've stated before it was working fine.

**Comment by johnsmith600** [comment]
im going to open a test server see what happens then then try on the main server

**Comment by johnsmith600** [comment]
it worked on the test server

**Comment by johnsmith600** [comment]
yeah or the server artifacts might not be upto its requirements the test server is running the latest artifact and i did the same thing to what i did with the main server

**Comment by NoobSpielt** [comment]
> yeah or the server artifacts might not be upto its requirements the test server is running the latest artifact and i did the same thing to what i did with the main server

If you are running it under zap the artifact Version should be enough + it would drop a other error

**Comment by johnsmith600** [comment]
yeah i might need to set the ftp permission

**Comment by johnsmith600** [comment]
anyway ill figure it out

**Comment by NoobSpielt** [comment]
> yeah i might need to set the ftp permission

as I already said here:



> 2 possible Errors:
> 
> 1. Installed Easyadmin wrong in the ressource folder.
> 2. The User under that the FX server runs don't have enough permission to read the fxmanifest
