### ISSUE TITLE
Identifiers showing

### ISSUE THREAD

**Issue by CheekSplitter** [Blumlaut/EasyAdmin#454]
Player identifiers shows in reports and makes it look bulky i need a way to make it so the identifiers dont show
![unknown](https://user-images.githubusercontent.com/79209045/181685612-726df280-8715-492f-8a2a-7329b29b8dff.png)

**Comment by Blumlaut** [comment]
apparently this behaviour was already changed in a recent update, please update your easyadmin before creating github issues about things that were already done...
