### ISSUE TITLE
Issues with the teleport back to and teleport player back to

### ISSUE THREAD

**Issue by nymtrashexe** [Blumlaut/EasyAdmin#458]
**Describe the bug**
Half of the teleport function is not working, aka "teleport me back" and "teleport player back" 

**To Reproduce**
Steps to reproduce the behaviour:
not sure really

**Expected behaviour**
Simply put, we expect to be teleported back to the player we just teleported to or to teleport the player we brought to us back to their previous location as the menu would state it. The player does a little "bounce" as if they're teleporting but don't actually go anywhere, almost as if the previous location is registered after the teleport and not prior to. 

**Screenshots/Logs**
No screenshots or errors to add as it doesn't seem to be posting anything currently. There are no errors on client or server side pertaining to easyadmin and also nothing additional on start-up. This is the function:

![image](https://user-images.githubusercontent.com/91373385/182127679-ac438585-314b-4295-a41f-16ffe049b87e.png)

**Server Infos (please complete the following information):**
 - OS: Windows Server 2019
 - FXServer Version 5562
 - EasyAdmin Version 6.81

**Additional context**
~~

**Comment by robbybaseplate** [comment]
Are you using Onesync Infinity?

**Comment by nymtrashexe** [comment]
yes we have it on

**Comment by Blumlaut** [comment]
locked due to stale/no repro steps

**Comment by ChickenDipper1** [comment]
Same issue, steps to repro are just try to tp a player back after tping them somewhere. Not sure what else you are looking for here?
