### ISSUE TITLE
[BUG] Script Error - bad argument

### ISSUE THREAD

**Issue by ViolentMinds** [Blumlaut/EasyAdmin#459]
**Describe the bug**

Just noticed this in my client log

```
[    430672] [b2612_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @EasyAdmin/client/gui_c.lua:1225: bad argument #1 to 'for iterator' (table expected, got nil)^7
[    505391] [b2612_GTAProce]             MainThrd/ NETWORK_GET_NETWORK_ID_FROM_ENTITY: no such entity
```

Not sure if its important or not but wanted to report it anyways.

**Server Infos (please complete the following information):**
 - OS: Windows Server 2019
 - FXServer Version 5777
 - EasyAdmin Version 6.7

**Comment by Blumlaut** [comment]
please update your easyadmin before filing bug reports, only the latest version is ever supported.
