### ISSUE TITLE
Feature Request: Add events for accepting, completing reports

### ISSUE THREAD

**Issue by mcNuggets1** [Blumlaut/EasyAdmin#461]
**Is your feature request related to a problem? Please describe.**
I wanna track how many reports our admins are doing, so we can take a look at whos the most active.
But sadly there doesn't seem to be an event related to that.

**Describe the solution you'd like**
Add events for accepting, completing reports with the given adminID and reportID as arguments

**Describe alternatives you've considered**

**Additional context**

**Comment by Blumlaut** [comment]
I believe there are the `EasyAdmin:reportAdded`, `EasyAdmin:reportClaimed` and `EasyAdmin:reportRemoved` events, which would be what you are asking for, no?

check https://github.com/Blumlaut/EasyAdmin/blob/master/server/bot/reports.js for usage

**Comment by mcNuggets1** [comment]
Are these callable from Lua?

**Comment by Blumlaut** [comment]
they're not callable at all, they're events you register in your script.

**Comment by mcNuggets1** [comment]
Good, should work fine, if they are able to be registered with AddEventHandler.
Sorry, im rather new to the whole FiveM scene ^^
But yeah, if thats it, thanks.

Maybe document it some day, because I didn't find it sadly.

**Comment by Blumlaut** [comment]
They are documented:
https://easyadmin.readthedocs.io/en/latest/plugins/#internal-events
