### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SPKReality** [Blumlaut/EasyAdmin#464]
**Describe the bug**
So when starting the easyadmin script it shows a error ( shown below ) it has only started since i upgraded txadmin version to the latest, Also the discord bot doesnt start.

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**
If applicable, add screenshots or logs to
![unknown](https://user-images.githubusercontent.com/103054717/183771552-b3ddd7ce-a1ef-4098-9e05-d78afe1ffbcc.png)
 help explain your [problem.]

**Server Infos (please complete the following information):**
 - OS: [e.g. Windows Server 2019, Debian 10..] - 4.19.0-13-amd64
 - FXServer Version [e.g. 5123] - Versions: v4.15.1
 - EasyAdmin Version - Version 6.81

**Additional context**

**Comment by Blumlaut** [comment]
incomplete template, this is also not a bug report.
