### ISSUE TITLE
Screenshot URL (Discord upload)

### ISSUE THREAD

**Issue by zRxnx** [Blumlaut/EasyAdmin#470]
**Is your feature request related to a problem? Please describe.**
Yes, it could fix the screenshot url revealing issue.

**Describe the solution you'd like**
The bot can recognise that a Discord upload is used for `ea_screenshoturl`. After each server boot, the old webhook is deleted and a new one is created.

**Describe alternatives you've considered**
If someone doesn't like this feature, it would be good to have a convar like `ea_resetScreenshotURL`, if this is true, the bot will generate a new webhook on every server boot.

**Additional context**
-

**Comment by Blumlaut** [comment]
basically pointless as you can still read the convar at runtime, it would be better investigating if the bot can upload screenshots itself, without the need of a webhook.
