### ISSUE TITLE
[BUG] Can't set bot commands when using the easyadmin invite link.

### ISSUE THREAD

**Issue by ImboredTech** [Blumlaut/EasyAdmin#478]
**Describe the bug**
I have used the invite link on the easyadmin docs website. And after using this link I get the error in my console.
Error: Failed to set bot commands, you likely didn't invite the bot correctly, please kick the bot and re-invite with the link here:

**To Reproduce**
1. Invite the bot using the easyadmin link.
2. Restart the server.

**Expected behavior**
The commands should set in the discord server.

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.

**Server Infos (please complete the following information):**
 - OS: Ubuntu LTS using TXAdmin
 - FXServer Version 5123
 - EasyAdmin Version LTS

**Additional context**

**Comment by Blumlaut** [comment]
this is not a bug.
