### ISSUE TITLE
Screenshotting issue

### ISSUE THREAD

**Issue by IndigoBerry** [Blumlaut/EasyAdmin#481]
Hello, I am unsure on how to setup the config for the screenshotting. I have screenshot-basic installed and i have this in my server CFG
setr ea_screenshoturl "https://discord.com/api/webhooks/1014972915214729287/dM5NQNAu1Rr84GuhdWGQ5dr8R9l4R5nIvN1kRYTlH-7m6JjOeNmHXayoimKAPbizu7Kw"
setr ea_screenshotfield "files[]"

when i click take screenshot it doesnt come up in the channel.

**Comment by Blumlaut** [comment]
You should check your F8 Console for errors in this case, eEasyAdmin just passes the configured variables directly to screenshot basic, likely if the screenshots arent taken then there's an issue with your screenshot-basic resource
