### ISSUE TITLE
Add possibility to ban offline players via steamid / license

### ISSUE THREAD

**Issue by mcNuggets1** [Blumlaut/EasyAdmin#482]
**Is your feature request related to a problem? Please describe.**
There currently is no possibility to ban a player which hasn't visitted the server this instance.

**Describe the solution you'd like**
A possibility to ban players based on their IDs (license or steam)

**Describe alternatives you've considered**
I don't know honestly

**Additional context**

**Comment by Blumlaut** [comment]
> A possibility to ban players based on their IDs (license or steam)

EasyAdmin itself requires at least 2 matching identifiers before it declines people for being banned, having 1 identifier banned would have no effect for people trying to join.

> There currently is no possibility to ban a player which hasn't visitted the server this instance.

this isn't really a problem though, is it? what use case would you have for banning a user that has never been on your server..?

**Comment by mcNuggets1** [comment]
A user that has played on another server and ban them on easy admin too?
A user that quit, the server restarted and you want to ban them there?
A user that joined on the discord for trolling?

Plenty of reasons.

And if easy admins requires two identifiers, change that?
Offline banning is an extremely important feature that nearly every other admin system has.
Having developers to it themselves because "it isn't really a problem" is not a good argument at all.

**Comment by Blumlaut** [comment]
> A user that has played on another server to ban them on another server?

This would support weird "global ban" systems which i personally do not support as it tends to open up abuse.

> A user that quit, the server restarted and you want to ban them there?

try again later? at this point caching can be configured for so long i dont see how many "chances" i should give admins to ban people..

> A user that trolled on the discord without connecting to the server?

Discord identifiers are not reliable, you can simply not run discord and you would not be affected by the ban.

> And if easy admin requires two identifiers, change that?

EasyAdmin doesn't "require" two identifiers, two is the minimum that will be matched to prevent false positives (LAN IPs, same Household Users, Proxy IPs....), so no.

> Offline banning is an extremely important feature that nearly every other admin system has.

EasyAdmin has a cache that you can configure to however long you want, "offline banning" is useless if identifiers are easily changed or removed entirely.

**Comment by mcNuggets1** [comment]
1. I don't even mean other FiveM servers, I run a multi gaming community and there are just people I can't let on my FiveM server aswell.
2. How would you need to cache anything, if a ban is done via an identifier that can be checked upon connection? Just not a reason.
3. I never was talking about discord identifiers, I was talking about people doing shit on the discord, whom you know their ID aswell on the server.
4. License + SteamID is pretty reliable and not an ip adress to check for.
5. It can be complicated but allow the ban of trustworthy identifiers like a license.

**Comment by Blumlaut** [comment]
Like i already said, the ban system is more complicated than you think, your way to think about this feature is quite naive and simply won't happen as it's not been a modern standard for _years_, single-identifier bans are pointless because most identifiers are easily changed.

There is a reason EasyAdmin's ban system is as reliable as it is, it bans _every_ possible identifier of a player, not just a few specific ones.

**Comment by mcNuggets1** [comment]
A steamid doesnt sound easily to be changed.
A license either.
I can understand that a lot of identifiers can be changed, but some in practice shouldn't be able to.
And if players ban manually with only the identifiers they are given, isn't that their problem, if it isn't a 100% reliable?
It's just weird to strip of this feature and just annoys a lot of players of mine.

**Comment by Blumlaut** [comment]
> A steamid doesnt sound easily to be changed.

you can easily register a new steam account. for free.

> A license either.

buy GTA V again, or a stolen account, and delete FiveM entitlement data.

> I can understand that a lot of identifiers can be changed, but some in practice shouldn't be able to.

and yet they can, figures.

> And if players ban manually with only the identifiers they are given, isn't that their problem, if it isn't a 100% reliable?

And then EasyAdmin will get a bad reputation because people are using i wrong, the way EasyAdmin currently handles bans is _very deliberate_ and _very specific_, for a good reason.

> It's just weird to strip of this feature

It's really not, and it's not "stripped", the feature never existed. and never will, see above for why.
