### ISSUE TITLE
[BUG] Error getaddrinfo ENOTFOUND discord.com in console server FiveM

### ISSUE THREAD

**Issue by Adrian5063** [Blumlaut/EasyAdmin#485]
**Hello**, I noticed a bug in the FiveM server console from time to time. Has anyone found a solution to this problem?
![error](https://user-images.githubusercontent.com/112986097/188742489-1cdc3b67-ecf0-406f-a889-73c2d36c826e.png)
OS: Debian 10.12 (Latest)
FXServer Version: 5848 (Latest)
EasyAdmin Version: 6.9 (Latest)

**Comment by Blumlaut** [comment]
Your server is having issues resolving discords domain, you should check our dns settings

**Comment by Adrian5063** [comment]
It is possible that my VPS is blocking the HTTP and HTTPS port to discord.com?

On VPS I used the following commands:
sudo apt install ufw
sudo ufw allow 30120/udp
sudo ufw allow 30120/tcp
sudo ufw allow 22/tcp
sudo ufw enable

**Comment by robbybaseplate** [comment]
sudo ufw allow 80
sudo ufw allow 443

**Comment by NoobSpielt** [comment]
> sudo ufw allow 80
> sudo ufw allow 443

With that you would just open your own ports. You need to do this if you are hosting e.g a Webserver on these ports. 

Normally ufw is only blocking incoming traffic. As Blü already wrote it's rather a dns problem as a firewall problem.

**Comment by Adrian5063** [comment]
Problem resolved when add set ea_botLogChannel "ChannelId" to the server.cfg.
Apparently, without it, it gets to the error, because suddenly after adding it, the problem with the error disappeared.
Personally, this function is unnecessary to me, but since it gets rid of the error, so be it.
