### ISSUE TITLE
[BUG] Bot needs to be restarted to send message

### ISSUE THREAD

**Issue by Ultra-Meloncrafter** [Blumlaut/EasyAdmin#489]
[    script:EasyAdmin] Error: Failed to configure bot status channel, please make sure the channel id is correct and the bot has read and write access. 
my easyadmin needs to be restarted to send the server status message. anyone know how to fix 
i don't know what to do, to reproduce it i just configured the bot like the guide says

**Comment by Blumlaut** [comment]
> Failed to configure bot status channel

happens if the bot doesnt have permission to see the channel, or the channel you configured does not exist

**Comment by Ultra-Meloncrafter** [comment]
> > Failed to configure bot status channel
> 
> happens if the bot doesnt have permission to see the channel, or the channel you configured does not exist

it hast permission to see the channel, the channel exists and every other bot can interact in the channel
