### ISSUE TITLE
Configuration won't work

### ISSUE THREAD

**Issue by Ultra-Meloncrafter** [Blumlaut/EasyAdmin#490]
Please don't close

`Failed to configure bot status channel, please make sure the channel id is correct and the bot has read and write access.`
`Expected token to be set for this request, but none was present` i also get this error
it has permission to see the channel, the channel exists and every other bot can interact in the channel, my easyadmin needs to be restarted to send the server status message
i don't know what to do, to reproduce it i just configured the bot like the guide says

**Attempted Solutions**
I made a new bot, gave the bot another role, added it directly to the channel, added it to the category and configured it again

**Server Infos:**
 - OS: Debian 10
 - FXServer Version 5879
 - EasyAdmin Version 6.9

The server.cfg configuration looks like this: 
set ea_botToken "asdklklö"
set ea_botGuild "123456789"
set ea_botStatusChannel "101112131416"

**Comment by Blumlaut** [comment]
I cannot replicate this on my end, are you sure you are not configuring the channel twice (once incorrectly and once, later on, correctly) somewhere else? works fine first try here.

**Comment by Ultra-Meloncrafter** [comment]
i searched if the channel is somewhere else defined but it isn't only in the server.cfg but there is another error instead of the second one now `ConnectTimeoutError: Connect Timeout Error`

**Comment by Ultra-Meloncrafter** [comment]
or better said the second error shows up after a few minutes, the bot has all the privileges you provided with the link and has all the Privileged Gateway Intents

**Comment by Ultra-Meloncrafter** [comment]
somehow it sends the message now, but still says not configured

**Comment by Ultra-Meloncrafter** [comment]
> I cannot replicate this on my end, are you sure you are not configuring the channel twice (once incorrectly and once, later on, correctly) somewhere else? works fine first try here.

it works now, but there is still the second error and it doesn't update the message

**Comment by Blumlaut** [comment]
the connect timeout error is related to your internet connection to the discord server, entirely unrelated to easyadmin.
