### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Jarnekeuh** [Blumlaut/EasyAdmin#499]
**Describe the bug**
I recently bought the ESX plugins script to add money, add items, set job,...
If I try to spectate someone when he isn't fully loaded into the server, my menu closes and I can't open it again for a few moments. 
When the player is loaded in, the menu works again. 

**To Reproduce**
1. open easyadmin menu
2. click on a player that is joining the server 
3. easyadmin won't open again after the 2nd step. 

So the problem is that my eaysadmin with the plugin menu can’t receive any data from a player who isn’t fully loaded. 
That’s because the required data from the player only generates when he is fully loaded I think. 

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.
![image](https://user-images.githubusercontent.com/113985730/191586231-aea4c79a-7b2f-45e2-9398-06a4d732376a.png)
This is an error I get in F8. 

other errors in server console. 

[ script:es_extended] SCRIPT ERROR: @es_extended/server/main.lua:641: attempt to index a nil value (local 'xPlayer')
[ script:es_extended] > ? (@es_extended/server/main.lua:641)
[ script:es_extended] > TriggerServerCallback (@es_extended/server/functions.lua:160)
[ script:es_extended] > handler (@es_extended/server/common.lua:124)
[ script:esx_license] SCRIPT ERROR: @esx_license/server/main.lua:45: attempt to index a nil value (local 'xPlayer')
[ script:esx_license] > TriggerServerCallback (@es_extended/server/functions.lua:160)
[ script:esx_license] > handler (@es_extended/server/common.lua:124)
[ script:es_extended] SCRIPT ERROR: error object is not a string

**Server Infos (please complete the following information):**
 - FXServer Version 5848
 - EasyAdmin Version (latest)

**Additional context**
I know that my ESX is providing invalid license data. But without the plugin everything works fine. 
What can I do to fix it?

**Comment by Blumlaut** [comment]
>  What can I do to fix it?

fix your esx, this is not an EasyAdmin bug

**Comment by Jarnekeuh** [comment]
I use esx legacy and I didn't touch the code. Like I said, without the plugin everything works fine. 
It's the second time I ask for help and again you are closing it... 

I am not the only person with this bug. Check the github issue [BUG] Spectating #448. 

You answered his report with this message 

Thanks for the report!
this is very odd indeed, the error you sent seems to happen during menu generation for some reason, instead of being in the spectate code.
**will try and reproduce this myself in a bit.**

**Comment by Blumlaut** [comment]
> I use esx legacy 

"legacy" is about 20 different versions all with different bugs and garbage "refactors" that make no sense.

> without the plugin everything works fine

cool, guess what, easyadmin also works fine without ESX.

> I am not the only person with this bug. Check the github issue [BUG] Spectating https://github.com/Blumlaut/EasyAdmin/issues/448.

so then why are you creating a duplicate issue about it? when apparently an issue about it already exists?

**Comment by Jarnekeuh** [comment]
I make a new one because the bug isn't solved. What legacy version do you think works the best? 
Or on what framework version did you test everything? 
 
Maybe you can edit the code so that the required data will be requested when the player is fully loaded. 

I'm just asking for some help and try to find a solution. My apologies if I bother you with this.

**Comment by Blumlaut** [comment]
> I make a new one because the bug isn't solved

this is not how github issues work.

> What legacy version do you think works the best?

none, ESX is a shitfest.

>  Or on what framework version did you test everything?

last tested ESX version was 1.6.0, anything above that has been entirely broken for me and i genuinely cannot be arsed trying to fix this mess of a "framework"

> Maybe you can edit the code so that the required data will be requested when the player is fully loaded.

what?

**Comment by Jarnekeuh** [comment]
Alright, I will test the ESX version 1.6.0. 
Thanks for your time
