### ISSUE TITLE
Some Errors

### ISSUE THREAD

**Issue by NeiZeOne** [Blumlaut/EasyAdmin#505]
[**Describe] the issue**
The Screenshot tells all

**Attempted Solutions**
I tryed to give some more permission but i didnt work

**Screenshots/Logs**

![Unbenannt](https://user-images.githubusercontent.com/114942743/193631787-f00189a6-435d-48f4-8279-5c04d4b66380.PNG)

**Server Infos (please complete the following information):**
 - OS: Debian 10
 - ESX Legacy 1.6.5
 - FXServer Version  5848
 - EasyAdmin Version newest
 - I used to install the FiveM Server with Pterodactyl Panel for Linux

**Comment by Blumlaut** [comment]
> Pterodactyl Panel 

pterodactyl is generally not supported by FiveM, looking at your server console your server file permissions are also all kinds of messed up.

**Comment by NeiZeOne** [comment]
so there is no way to give it the permissions for it ?

**Comment by Blumlaut** [comment]
that's on you to fix, not related to easyadmin

**Comment by Blumlaut** [comment]
this issue is not related to EasyAdmin, your fivem server has no permissions to write any files in it's own folder anywhere, you need to fix this.
