### ISSUE TITLE
Error: "event EasyAdmin:addBan was not safe for net" when trying to trigger the EasyAdmin:addBan event.

### ISSUE THREAD

**Issue by Chilixxd** [Blumlaut/EasyAdmin#514]
**Describe the issue**
Hey there! Im trying to ban a user from another script. 
I have tried it this way:
```
serverID = GetPlayerServerId(NetworkGetEntityOwner(PlayerPedId()))
TriggerServerEvent("EasyAdmin:addBan", serverID, "test", 10444633200, "test")
```

**Attempted Solutions**
I have tried googling for example "event was not safe for net fivem" etc but not really found anything.

**Screenshots/Logs**
No.

**Server Infos (please complete the following information):**
 - OS: Windows 10
 - FXServer Version: Most recent stable (5848)
 - EasyAdmin Version: 6.91

**Additional context**
No.

**Comment by Chilixxd** [comment]
SOLVED

**Comment by Blumlaut** [comment]
for reference; addBan is a server-only event, you should use `EasyAdmin:banPlayer` when trying to ban someone from a client..
