### ISSUE TITLE
ESX Plugin

### ISSUE THREAD

**Issue by NightCop1** [Blumlaut/EasyAdmin#516]
**Server Infos (please complete the following information):**
 - OS: [Debian 11]
 - FXServer Version [5914]
 - EasyAdmin Version 6.91

**Additional context**
Hi

I just bought the plugin ESX and Trainer
get the following error with the plugin ESX

@EAsyAdmin/plugins/esx/esx_client.lua:177 attempt to concatenate a nil value (field label)
![EasyAdmin](https://user-images.githubusercontent.com/108928185/198002665-95ce45cc-cbae-4d2e-be6d-2c286e727827.png)

**Comment by Blumlaut** [comment]
![image](https://user-images.githubusercontent.com/13604413/198007049-77f01b84-eada-4e32-85e6-c6b7ed150798.png)

**Comment by Blumlaut** [comment]
> what is the picture supposed to tell me?

that this is something broken about ESX but noone bothered to provide **any** infos about their setup so far to be able to fix it?

>  you can't use the plugin the way it is right now

Blame ESX i guess? i still dont know whats even causing the issue and default ESX setups seem to work perfectly fine from my testing, so its likely some custom garbage causing issues.
