### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by garraponi** [Blumlaut/EasyAdmin#517]
**Describe the issue**
I bought 1x ESX Plugin 1x Griefing Plugin 1x Basic Trainer but now I can't download them as the link is down

**Attempted Solutions**
I have looked for the email that came with the purchase, but the link is down

**Screenshots/Logs**
[If applicable, attach screenshots or log files here to help explain your problem.](https://cdn.discordapp.com/attachments/967590065024925697/1034991571025788928/unknown.png)

**Server Infos (please complete the following information):**
 - OS: Debian 10.
 - "version" is "FXServer-master v1.0.0.5975 linux"
 - EasyAdmin Version 6.9

**Additional context**
Transaction ID: I can say it in private

**Comment by Blumlaut** [comment]
there should be a contact email in your tebex order confirmation, email that with your transaction id.
