### ISSUE TITLE
playerConnecting Error 

### ISSUE THREAD

**Issue by PlatinumExclusiveCollections** [Blumlaut/EasyAdmin#519]
**Describe the issue**
We get this error on server console if someone is joining our fivem server

[    script:EasyAdmin] SCRIPT ERROR in event `playerConnecting': ReferenceError: EasyAdmin is not defined
[    script:EasyAdmin] > <unknown> (@EasyAdmin/server/bot/player_events.js:16)
[    script:EasyAdmin] 

**Attempted Solutions**
Nothing

**Screenshots/Logs**
[    script:EasyAdmin] SCRIPT ERROR in event `playerConnecting': ReferenceError: EasyAdmin is not defined
[    script:EasyAdmin] > <unknown> (@EasyAdmin/server/bot/player_events.js:16)
[    script:EasyAdmin] 

**Server Infos (please complete the following information):**
 - OS: Windows Sever 2019
 - FXServer Version 5975
 - EasyAdmin Version 6.91

**Additional context**
Nothing

**Comment by Blumlaut** [comment]
Do you have the discord bot configured? If so, likely there is an issue with the bot that is preventing it from starting properly.

**Comment by PlatinumExclusiveCollections** [comment]
No i have not. I were i can get the discord bot?

**Comment by Blumlaut** [comment]
> No i have not

.. How? the player events only work if `ea_botToken` has been changed.

**Comment by PlatinumExclusiveCollections** [comment]
> > No i have not
> 
> .. How? the player events only work if `ea_botToken` has been changed.

I didnt changed anything. 

set ea_detailNotification "https://discord.com/api/webhooks/962886919769952276/XJC7KLT98tvEbBlE4YPTRSYR5Yx_QBK5PMg96o318WF4AqIPpaK3wwmT230Dv7eUxuUB"
set ea_botToken "OTYwMzA4Mzk1Nzc1MjM0MTQ5.Ykoi4w.yhh71nb8WFA3ff-v3jAOpbA6mYM"
set ea_botGuild "960299896857047090"
set ea_moderationNotification "https://discord.com/api/webhooks/968893207704387644/f43rt5EptlN8wInoSloTF7ZVPPSDU8A14Mz-jajPj9QMvQGeG72vPrdh917PwvBiRDlI"
set ea_reportNotification "https://discord.com/api/webhooks/968893487799996446/acIkDTUBfnPeoMfeKIS3YYpbu0WihX7IcUj6jo0wbaXgOdLozIRcCbDzG5B6Qg5RXnww"

**Comment by Blumlaut** [comment]
.. do you even know what you're doing? you claim you havent set up the discord bot yet have?

Also, you should regenerate all those tokens and webhooks as you just posted them publically for anyone to see and use.
