### ISSUE TITLE
Changing server_status.js for remove Error "You can only bulk delete messages that are under 14 days old."

### ISSUE THREAD

**Issue by Jim1120** [Blumlaut/EasyAdmin#520]
Hi,

If you use discord chanel with other(old) messages, edit server_status.js at line 117 and replace 
`await channel.bulkDelete(messagesToDelete)` 
By
`await channel.bulkDelete(messagesToDelete, true)`

Now your old message don't disturb discord bot and he delete message of server status 👍

**Comment by Blumlaut** [comment]
create a pull request for code improvements.
