### ISSUE TITLE
create getnotified config 

### ISSUE THREAD

**Issue by Tecktorious** [Blumlaut/EasyAdmin#521]
[    script:EasyAdmin] EasyAdmin: You are using a Custom Banlist System, this is not currently supported and WILL cause issues! Only use this if you know what you are doing, otherwise, disable ea_custombanlist.

I get spammed from it ... can you use a config.getnotified = true 
if we wanna get those debugs on console ?
cause they are non stop ...i can disable that but i m talking to people generaly who dont know anything about scripting xd

**Comment by Blumlaut** [comment]
custom database systems are considered "dead" and unsupported, any update may/can break it or remove it entirely, hence the warning message, there won't be an override switch.
