### ISSUE TITLE
Good morning, I wanted to ask if it is possible to change the license of a past discord account to this new one because my account was already deleted, if it is possible, what tests are required to make the change and have the possibility of having the easyadmin license again

### ISSUE THREAD

**Issue by Charls20** [Blumlaut/EasyAdmin#527]
**Describe the issue**
A clear and concise description of what the issue is.

**Attempted Solutions**
Describe what you have done to attempt to fix it.

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

**Server Infos (please complete the following information):**
 - OS: [e.g. Windows Server 2019, Debian 10..]
 - FXServer Version [e.g. 5123]
 - EasyAdmin Version

**Additional context**

**Comment by Blumlaut** [comment]
what
