### ISSUE TITLE
server thread hitch warning.

### ISSUE THREAD

**Issue by V3SC** [Blumlaut/EasyAdmin#529]
Hi, I don't know if you are still developing EasyAdmin, but if you are, will you make an improvement about playerConnecting ban check system?

There are 13K+ ( 3M Lines ) banned players on my server. I think this is a bit much and I keep getting server thread hitch warning.

**Comment by Blumlaut** [comment]
> will you make an improvement about playerConnecting ban check system?

if you actually have constructive feedback to make instead of just saying "improve it", yeah.


> There are 13K+ ( 3M Lines ) banned players on my server. I think this is a bit much and I keep getting server thread hitch warning.

Have you actually [profiled](https://docs.fivem.net/docs/scripting-manual/debugging/using-profiler/) your server and figured out where those hitch warnings are coming from? are you sure those are actually caused by EasyAdmin?

**Comment by V3SC** [comment]
> > will you make an improvement about playerConnecting ban check system?
> 
> if you actually have constructive feedback to make instead of just saying "improve it", yeah.
> 
> > There are 13K+ ( 3M Lines ) banned players on my server. I think this is a bit much and I keep getting server thread hitch warning.
> 
> Have you actually [profiled](https://docs.fivem.net/docs/scripting-manual/debugging/using-profiler/) your server and figured out where those hitch warnings are coming from? are you sure those are actually caused by EasyAdmin?

Yes, you're right, I apologize. 

![image](https://user-images.githubusercontent.com/33003717/200939307-38fd3bd3-f9fc-4652-b0c6-3fa43a9a345c.png)

**Comment by Blumlaut** [comment]
can you upload your banlist file somewhere? I want to test myself, player joins should not be blocking..

**Comment by V3SC** [comment]
> can you upload your banlist file somewhere? I want to test myself, player joins should not be blocking..

I don't want to upload it to public. I sent you a friend invitation on discord. Can you accept it?

**Comment by mcNuggets1** [comment]
It is also very inconvenient to just queue through a huge file to check if a player has been banned instead of a simple key index check.

**Comment by Blumlaut** [comment]
> It is also very inconvenient to just queue through a huge file to check if a player has been banned instead of a simple key index check.

instead of posting pointless comments under every single issue how about you actually contribute via pull requests? you seem to talk awfully confident about open issues but make no effort to fix them.

**Comment by mcNuggets1** [comment]
Your resource, not mine.
I'm not distributing this.

I'm just pointing out issues which apparently makes you mad.
