### ISSUE TITLE
easy admin support

### ISSUE THREAD

**Issue by PJhousing** [Blumlaut/EasyAdmin#530]
**Describe the issue**
so griefmenu isnt working , no clip isnt working and Esx plugin isnt working 

**Attempted Solutions**
nothing ive installed it exactly like the read me said 

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.
![Screenshot (36)](https://user-images.githubusercontent.com/115688503/201456664-5c142527-213a-4d61-b197-01d6936a8777.png)

**Server Infos (please complete the following information):**
 - OS: [e.g. Windows 11 64-bit operating system, x64-based processor
 - FXServer Version ---v4.18.1 / 5990
 - EasyAdmin Version--6.91

**Additional context
nothing

**Comment by Blumlaut** [comment]
Screenshots/Logs
If applicable, attach screenshots or log files here to help explain your problem.

**Comment by PJhousing** [comment]
which log files do you need and how do i get to them 
also i attached a screenshot
