### ISSUE TITLE
easy admin working for all other admins other than myself

### ISSUE THREAD

**Issue by Soundwave2279** [Blumlaut/EasyAdmin#531]
**Describe the issue**
inside the FiveM server i cannot access easy admin... yet i am an admin

**Attempted Solutions**
restart steam, FiveM, remove and reset permissions to character

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

**Server Infos (please complete the following information):**

Dirty Money RP https://discord.gg/FXAtEFaRah
[cfx.re/join/lbdg84](https://cfx.re/join/lbdg84)
i am using windows 11 version 20H2
easy admin version : latest 

FiveM, HEX | steam:1100001047f0f0a

**Additional context**

**Comment by MaliciousSnip3r** [comment]
Make sure you are added to the permissions list
