### ISSUE TITLE
Problem mit EasyAdmin

### ISSUE THREAD

**Issue by WhiteNinja17** [Blumlaut/EasyAdmin#544]
**Describe the issue**
Immer wenn ich den Server starte erscheint der Fehler

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

**Server Infos (please complete the following information):**
 - OS: Debian 10
 - FXServer Version v4.18.1 atop FXServer 6020 
 - EasyAdmin Version Die Neuste

**Additional context**
![grafik](https://user-images.githubusercontent.com/90917962/204900176-277391dd-d74e-410d-a7d7-bf7c5fb15bf4.png)

**Comment by zRxnx** [comment]
Delete the status message manually

**Comment by Blumlaut** [comment]
> Immer wenn ich den Server starte erscheint der Fehler

¿habla Inglés?
