### ISSUE TITLE
 Failed to log message, please make sure you gave the bot permission to write in the log channel!

### ISSUE THREAD

**Issue by RazersIQ2** [Blumlaut/EasyAdmin#546]
**Describe the issue**
A clear and concise description of what the issue is.

**Attempted Solutions**
Describe what you have done to attempt to fix it.

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

**Server Infos (please complete the following information):**
 - OS: [e.g. Windows Server 2019, Debian 10..]
 - FXServer Version [e.g. 5123]
 - EasyAdmin Version

**Additional context**

**Comment by zRxnx** [comment]
?

**Comment by RazersIQ2** [comment]
for some reason this is the error im getting in my console and the bot has every permission in our discord and still keeps saying this error
