### ISSUE TITLE
Easy Admin

### ISSUE THREAD

**Issue by sslezy** [Blumlaut/EasyAdmin#547]
How to remove the "settings" option inside of the menu itself as well as remove "search for players" and "cached players" from the menu. Thank you

**Comment by Blumlaut** [comment]
settings cannot be removed (because why would you remove settings?), the player menu can be removed by not granting any `player` permissions for the specific user

**Comment by sslezy** [comment]
I want certain things out of settings like Easter egg, etc what would be the command to remove those type of things. I want the option search and cached gone, do I use player.search deny or? I am just asking what specific commands need used to deny access.

**Comment by Blumlaut** [comment]
You can't remove the settings because it'd be nonsensical to remove the settings of an admin menu.

as i said, don't grant any permissions in the `player` category, read the docs:
https://easyadmin.readthedocs.io/en/latest/permissions/#available-permission

**Comment by sslezy** [comment]
Okay, How do you remove the Easter Egg option inside of settings?

**Comment by sslezy** [comment]
> Okay, How do you remove the Easter Egg option inside of settings?

that is NOT inside the docs. If it was inside docs I would of not been here.. I obviously utilized docs to install it bro.

**Comment by Blumlaut** [comment]
You **don't**, as i already said 2 times.

**Comment by sslezy** [comment]
alright homie Ill just remove it from the script itself then, thanks.
