### ISSUE TITLE
Esx plugin error - I purchased your esx plugin

### ISSUE THREAD

**Issue by RAXIC7** [Blumlaut/EasyAdmin#554]
![resim](https://user-images.githubusercontent.com/57269411/205956394-82c62f73-d73f-4dd1-89e7-c3ada57fc304.png)
![resim](https://user-images.githubusercontent.com/57269411/205747324-42a330a8-65a9-49be-9c48-230f055b2273.png)
![resim](https://user-images.githubusercontent.com/57269411/205747348-08be8c06-f6fb-4719-9e0e-d05359ffa003.png)

I am getting the error in the images.

I am getting error in this part. My esx version: esx-legacy 1.8.5.

I also purchased your esx plugin and I want you to give a customer role from your discord. 
**MY DISCORD: günther#6331**

 - OS: [Windows 10]
 - FXServer Version [6117]
 - EasyAdmin Version 6.91
 
 @Blumlaut

**Comment by Blumlaut** [comment]
Known issue, as noone provided any way to reproduce the issue it has gone unfixed, the issue is due to your ESX passing invalid license informations.

Also, dont share plugin source code, or risk getting repo-banned.

**Comment by RAXIC7** [comment]
> Known issue, as noone provided any way to reproduce the issue it has gone unfixed, the issue is due to your ESX passing invalid license informations.
> 
> Also, dont share plugin source code, or risk getting repo-banned.

Sorry i won't be sharing code again. 
So how can i fix this error, because I can't use multiple features of esx plugin because of this error
@Blumlaut
