### ISSUE TITLE
How do I change the key of the menu EasyAdmin for all the admins?

### ISSUE THREAD

**Issue by Badaasaaur** [Blumlaut/EasyAdmin#556]
**Describe the issue**
A clear and concise description of what the issue is.

**Attempted Solutions**
Describe what you have done to attempt to fix it.

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

**Server Infos (please complete the following information):**
 - OS: [e.g. Windows Server 2019, Debian 10..]
 - FXServer Version [e.g. 5123]
 - EasyAdmin Version

**Additional context**

**Comment by Blumlaut** [comment]
no.
