### ISSUE TITLE
Discord Webhook dont log

### ISSUE THREAD

**Issue by Yofa233** [Blumlaut/EasyAdmin#563]
**Describe the issue**
My Discord Webhooks dont log anything

**Attempted Solutions**
I made only one Webhook using set ea_moderationNotification "WEBHOOK"
I made three Webhooks using

set ea_reportNotification "WEBHOOK"
set ea_detailNotification "WEBHOOK"
set ea_moderationNotification "WEBHOOK"

**Screenshots/Logs**
No one aviable

**Server Infos (please complete the following information):**
 - OS: Windows Server 2022 Standard Evaluation 21H2
 - FXServer Version v1.0.0.6117
 - EasyAdmin Version 6.91

**Additional context**

**Comment by Blumlaut** [comment]
use `ea_testWebhook` command to test if the webhook works

**Comment by Yofa233** [comment]
Thanks for the fast Response, im just stupid i had a problem with the whole server.cfx and made a bit shit so the file wouldnt load everything right. The Webhook is now working.
