### ISSUE TITLE
ESX Plugin

### ISSUE THREAD

**Issue by RicardoICY** [Blumlaut/EasyAdmin#566]
Hallo I have buy ESX Plugin. Its was all perfect. But today I dont can find esx plugin on my keymaster. pls help me ¬Theヮeal¬#6173 this is my discord.

**Comment by Blumlaut** [comment]
contact tebex support

**Comment by RicardoICY** [comment]
ne its was on my account

**Comment by RicardoICY** [comment]
i have buy at 2 in one account and i have take 1 back but ists was delatet on my account

**Comment by RicardoICY** [comment]
i can you send my traktion number

**Comment by RicardoICY** [comment]
but i have it annoderone

**Comment by RicardoICY** [comment]
can you take it from one to the other account pls

**Comment by RicardoICY** [comment]
![image](https://user-images.githubusercontent.com/120952014/208306453-57536cf3-a513-4812-8351-d04611d3cbe3.png)

**Comment by Blumlaut** [comment]
Status: Chargeback

Disputing a payment immediately removes it from your account, i have no influence over your payments or which account its assigned to, contact tebex.
