### ISSUE TITLE
ea extras menu error

### ISSUE THREAD

**Issue by Animarlly** [Blumlaut/EasyAdmin#568]
**Describe the issue**
A clear and concise description of what the issue is.

When I try to open the ea extras menu, I always get this error

**Attempted Solutions**
Describe what you have done to attempt to fix it.

Reinstalled the ea resource fully.

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

![image](https://user-images.githubusercontent.com/102727791/208307113-774dc012-67e0-4401-931a-45b11815f18d.png)

**Server Infos (please complete the following information):**
 - OS:  Debian 10
 - FXServer Version FXServer 6133
 - EasyAdmin Version 6.91

**Additional context**

**Comment by Blumlaut** [comment]
your ESX is providing invalid license data, either the license label or type is nil
