### ISSUE TITLE
unable to get the discord bot working correctly

### ISSUE THREAD

**Issue by alexvermaning0** [Blumlaut/EasyAdmin#569]
**Describe the issue**
i recently found out that EasyAdmin has an discord bot integration so i started to add it using the EasyAdmin documentation
it starts fine [    script:EasyAdmin] Logged in as BotName#1234! but when i run an command like /playerlist i get an error
the bot status works fine. (as displayed in image)

**Attempted Solutions**
giving the bot all perms

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/17603899/208317278-2bc7721d-4063-45f4-8f4f-3025f4daba94.png)
![image](https://user-images.githubusercontent.com/17603899/208317291-9badf893-d94c-4691-a55e-511b5de46d22.png)
![image](https://user-images.githubusercontent.com/17603899/208317420-514b1bae-23c0-4717-8a64-7881209114d6.png)

**Server Infos (please complete the following information):**
 - OS: Windows 10 (atlasOS)
 - FXServer Version 6115
 - EasyAdmin Version 6.91

**Additional context**
i also get the message im using an unstable release while it points to the version i have.

**Comment by Blumlaut** [comment]
> EasyAdmin Version 5.0.0

easyadmin 5.0 did not even have a discord bot integration, please fill in the form properly..

**Comment by alexvermaning0** [comment]
oh i put the txadmin version in there

**Comment by Blumlaut** [comment]
Another bot is seemingly picking up the interaction before easyadmin can, make sure you don't run 2 bots on the same account, as your other bot seems to be replying with "an error has occured" despite the command not being meant for it
