### ISSUE TITLE
[Chat bridge] add the ability to ignore admin chat

### ISSUE THREAD

**Issue by alexvermaning0** [Blumlaut/EasyAdmin#572]
**Is your feature request related to a problem? Please describe.**
yes i would like to have an server chat open to the public but its not possable without it ignoring admin chat

**Describe the solution you'd like**
an option to ignore the [admin chat] chat messages via an convar or something

**Describe alternatives you've considered**
an snipet of the code to add it. thats disabled by default

**Additional context**
i checked the wiki but i did not find anything about this.

**Comment by alexvermaning0** [comment]
i forgot it was not added by easyadmin

**Comment by Blumlaut** [comment]
Sadly the [chatMessage event](https://github.com/citizenfx/cfx-server-data/blob/master/resources/%5Bgameplay%5D/chat/sv_chat.lua#L187) does not expose the chat mode, so this cannot be implemented.
