### ISSUE TITLE
EasyAdmin aduty

### ISSUE THREAD

**Issue by Zerb3rus01** [Blumlaut/EasyAdmin#573]
Good day. Do you also have a plugin with which you can go into aduty?

**Comment by ChickenDipper1** [comment]
Would be brilliant, if this could only allow access to EA features when "clocked on" as an admin.
Otherwise a normal player. Think I asked about this before though possibly.

**Comment by Blumlaut** [comment]
https://blumlaut.tebex.io/package/4681021 ?
