### ISSUE TITLE
Getting this error when players connect

### ISSUE THREAD

**Issue by davontai99** [Blumlaut/EasyAdmin#577]
[    script:EasyAdmin] SCRIPT ERROR in event `playerConnecting': ReferenceError: EasyAdmin is not defined
[    script:EasyAdmin] > <unknown> (@EasyAdmin/server/bot/player_events.js:16)
[    script:EasyAdmin]

**Comment by KarlHeinz2** [comment]
we have the same Problem

**Comment by cemo0228** [comment]
same!

**Comment by Blumlaut** [comment]
> SCRIPT ERROR in event `playerConnecting': ReferenceError: EasyAdmin is not defined

[Follow](https://github.com/Blumlaut/EasyAdmin/issues/new?assignees=&labels=support&template=support-.md&title=)

> we have the same Problem

[The](https://github.com/Blumlaut/EasyAdmin/issues/new?assignees=&labels=support&template=support-.md&title=)

> same!

[Template](https://github.com/Blumlaut/EasyAdmin/issues/new?assignees=&labels=support&template=support-.md&title=)

Your EasyAdmin bot can't initialize for some reason, however, as you failed to even bother reading your full server log, filling out the issue template or providing any context apart from a random error in your console, and 2 other empty accounts (joined within 2 weeks of eachother, never having done anything on github, ever?) started spamming "me too!!!!" right under it just as you created the issue, i'm considering this spam and closing it.
