### ISSUE TITLE
Easy Admin Error

### ISSUE THREAD

**Issue by RockLukas** [Blumlaut/EasyAdmin#581]
**Describe the issue**
[script:EasyAdmin-6.9] SCRIPT ERROR in event `playerJoining': ReferenceError: EasyAdmin is not defined
[script:EasyAdmin-6.9] > <unknown> (@EasyAdmin-6.91/server/bot/player_events.js:7)
[script:EasyAdmin-6.9] 

**Attempted Solutions**
I just Read the Docs for 5 times, but i still dont know the error

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

**Server Infos (please complete the following information):**
 - Windows 10 Pro Remote
 - FXServer Version [e.g. 5990]
 - EasyAdmin 6.91

**Additional context**
I just happens when a Player is connecting, but if im Manualy Restarting the script, i dont have any Errors

**Comment by Blumlaut** [comment]
your bot isn't ready for some reason, check your server logs when you start easyadmin, it will show you whats wrong.
