### ISSUE TITLE
Still getting yarn issues

### ISSUE THREAD

**Issue by mikwbm** [Blumlaut/EasyAdmin#582]
**Describe the issue**
Just installed EasyAdmin and I'm getting yarn build issues.

**Attempted Solutions**
Updated Yarn recourse and deleted server cache
Reinstalled EasyAdmin

**Screenshots/Logs**
https://imgur.com/a/2dqYtCc

**Server Infos (please complete the following information):**
 - OS: Linux 5.10.0-18-amd64
 - FXServer Version 6181/ZAP
 - EasyAdmin Version 6.91

**Additional context**
Console output:
`
================================================================
======== FXServer Starting - 31.12.2022, 07:22:17               
================================================================

[    c-scripting-core] Creating script environments for _cfx_internal
[ citizen-server-impl] Scanning resources.
[ citizen-server-impl] Found 55 resources.
[ citizen-server-impl] Some resources have an outdated resource manifest:
[ citizen-server-impl]     - NeverWanted
[ citizen-server-impl]     - ocrp_postal_map
[ citizen-server-impl]     - pd_sandy
[ citizen-server-impl] 
[ citizen-server-impl] Please update these resources.
[          svadhesive] Authenticating server license key...
[          svadhesive] Server license key authentication succeeded. Welcome!
[    c-scripting-core] Creating script environments for sessionmanager
[ citizen-server-impl] Started resource sessionmanager
[    c-scripting-core] Creating script environments for monitor
[      script:monitor] [txAdminClient] Version 5.0.1 starting...
[ citizen-server-impl] Started resource monitor
[    c-scripting-core] Creating script environments for mapmanager
[ citizen-server-impl] Started resource mapmanager
[    c-scripting-core] Creating script environments for yarn
[ citizen-server-impl] Started resource yarn
[    c-scripting-core] Creating script environments for webpack
[ citizen-server-impl] Started resource webpack
[    c-scripting-core] Creating script environments for chat
[ citizen-server-impl] Started resource chat
[ citizen-server-impl] Started resource spawnmanager
[   script:mapmanager] Started gametype Freeroam
[ citizen-server-impl] Started resource basic-gamemode
[    c-scripting-core] Creating script environments for hardcap
[ citizen-server-impl] Started resource hardcap
[    c-scripting-core] Creating script environments for staff
[ citizen-server-impl] Started resource staff
[    c-scripting-core] Creating script environments for Badger_Discord_API
[ citizen-server-impl] Started resource Badger_Discord_API
[    c-scripting-core] Creating script environments for Badssentials
[ citizen-server-impl] Started resource Badssentials
[    c-scripting-core] Creating script environments for DiscordAcePerms
[ citizen-server-impl] Started resource DiscordAcePerms
[ citizen-server-impl] Running build tasks on resource EasyAdmin - it'll restart once completed.
[ citizen-server-impl] Couldn't start resource EasyAdmin.
[ citizen-server-impl] Started resource NeverWanted
[    c-scripting-core] Creating script environments for RPC
[ citizen-server-impl] Started resource RPC
[ citizen-server-impl] Started resource RageUI
[    c-scripting-core] Creating script environments for SEM_InteractionMenu
[ citizen-server-impl] Started resource SEM_InteractionMenu
[ citizen-server-impl] Started resource bob74_ipl-2.1.1
[    c-scripting-core] Creating script environments for delallveh
[ citizen-server-impl] Started resource delallveh
[ citizen-server-impl] Started resource fivem-lsm
[ citizen-server-impl] Started resource frfuel
[    c-scripting-core] Creating script environments for helicam
[      script:helicam] Instantiated instance of script Dojrp.Fivem.Common.Server.Events.
[      script:helicam] Instantiated instance of script Dojrp.Fivem.HeliCam.Server.Main.
[ citizen-server-impl] Started resource helicam
[    c-scripting-core] Creating script environments for lvc
[ citizen-server-impl] Started resource lvc
[ citizen-server-impl] Started resource ocrp_postal_map
[ citizen-server-impl] Started resource savewheelpos
[    c-scripting-core] Creating script environments for vMenu
[        script:vMenu] Instantiated instance of script vMenuServer.BanManager.
[        script:vMenu] Instantiated instance of script vMenuServer.MainServer.
[ citizen-server-impl] Started resource vMenu
[ citizen-server-impl] Started resource Maps
[ citizen-server-impl] Started resource MotelSandy
[ citizen-server-impl] Started resource SandyHosp
[ citizen-server-impl] Started resource limeys
[ citizen-server-impl] Started resource paletogas
[ citizen-server-impl] Started resource paletopd
[ citizen-server-impl] Started resource pd_sandy
[ citizen-server-impl] Started resource pshop
[         script:yarn] [yarn] yarn install v1.22.5
[         script:yarn] info No lockfile found.
[         script:yarn] [1/4] Resolving packages...
[         script:yarn] 
[      script:monitor] [txAdminClient] Threads and commands set up. All Ready.
[   script:mapmanager] Started map fivem-map-skater
[ citizen-server-impl] Started resource fivem-map-skater
[         script:yarn] [yarn] [2/4] Fetching packages...
[         script:yarn] 
[         script:yarn] [yarn] [3/4] Linking dependencies...
[         script:yarn] 
[         script:yarn] Error: [yarn] error Could not write file "/home/zap846681/g520001/gta5-fivem-txadmin/CFXDefault_5DC78E.base/resources/[scripts]/EasyAdmin/yarn-error.log": "EACCES: permission denied, open '/home/zap846681/g520001/gta5-fivem-txadmin/CFXDefault_5DC78E.base/resources/[scripts]/EasyAdmin/yarn-error.log'"
[         script:yarn] 
[         script:yarn] Error: [yarn] error An unexpected error occurred: "EACCES: permission denied, mkdir '/home/zap846681/g520001/gta5-fivem-txadmin/CFXDefault_5DC78E.base/resources/[scripts]/EasyAdmin/node_modules'".
[         script:yarn] 
[         script:yarn] [yarn] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[         script:yarn] 
[ citizen-server-impl] Building resource EasyAdmin failed.
[ citizen-server-impl] Error data: yarn failed!

`

**Comment by Blumlaut** [comment]
press the "Set FTP Permissions" button in the FTP browser page in ZAP's interface, then restart the server.

**Comment by mikwbm** [comment]
fixed ty
