### ISSUE TITLE
Yarn

### ISSUE THREAD

**Issue by DeffoNotConnor** [Blumlaut/EasyAdmin#584]
**Describe the issue**
Yarn error when starting recource 

**Attempted Solutions**
Reinstall, update through zap, fresh zap download

**Screenshots/Logs**
![8BD7780F-9033-456B-AB23-BF67ED8B4E1E](https://user-images.githubusercontent.com/115879801/210185240-e70713c2-fb1d-4a3c-8332-819f6ec7214b.png)

**Server Infos (please complete the following information):**
 - OS: Tx admin through zap
 - FXServer Version 6183
 - EasyAdmin Version 6.91

**Additional context**

**Comment by Blumlaut** [comment]
https://github.com/Blumlaut/EasyAdmin/issues/582#issuecomment-1368189901
