### ISSUE TITLE
problem with esx plugin 

### ISSUE THREAD

**Issue by N1cl3s** [Blumlaut/EasyAdmin#585]
i dont now witch problem esx pack has could you help ?

![Screenshot_84](https://user-images.githubusercontent.com/121738051/210273515-4ce9c518-f00e-458d-b80e-1afadc949665.png)

**Comment by Sabqq2020** [comment]
Hello, did you get a solution for the problem?

**Comment by N1cl3s** [comment]
Yeah i used the newest version of esx-framework
