### ISSUE TITLE
Qb_server.lua 7 no such export

### ISSUE THREAD

**Issue by Masonlee1233** [Blumlaut/EasyAdmin#597]
**Describe the issue**
A clear and concise description of what the issue is.
I’ve tried my best you stated to just place in plugins folder which I have done so and still same error qb_server lua 7
**Attempted Solutions**
Describe what you have done to attempt to fix it.

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

**Server Infos (please complete the following information):**
 - OS: [e.g. Windows Server 2019, Debian 10..]
 - FXServer Version [e.g. 5123]
 - EasyAdmin Version

**Additional context**

**Comment by Blumlaut** [comment]
> **Attempted Solutions** Describe what you have done to attempt to fix it.
> 
> **Screenshots/Logs** If applicable, attach screenshots or log files here to help explain your problem.
> 
> **Server Infos (please complete the following information):**
> 
>     * OS: [e.g. Windows Server 2019, Debian 10..]
> 
>     * FXServer Version [e.g. 5123]
> 
>     * EasyAdmin Version
> 
> 
> **Additional context** Add any other context about the problem here.
