### ISSUE TITLE
Easy admin issue with qb_server .lua 7

### ISSUE THREAD

**Issue by Masonlee1233** [Blumlaut/EasyAdmin#598]
**Describe the issue**
I’ve brought this plugin on your tebex for £8 I’ve copied it in the plugins folder and I get the error qb_server.lua 7 no such export getcoreobject in resources qb core.

**Attempted Solutions**
Tried re-downloading the files and the easy admin to sort this and still no luck 

**Screenshots/Logs**

1] Stopping resource EasyAdmin
e] Creating script environments for EasyAdmin n] n] in] in] in]
Version 6.91
01] Started resource EasyAdmin
entalWarning: stream/web is an experimental feature. This feature could change at any time
'ace-warnings
to show where the warning was created)
in] SCRIPT ERROR: @EasyAdmin/plugins/qb_server .lua: 7: No such export GetCoreObject in resource qb p1] server thread hitch warning: timer interval of 1274 milliseconds

**Server Infos (please complete the following information):**
 - OS: Windows Server 2019
 - FXServer Version 6163
 - EasyAdmin Version 6.91

**Additional context**

please help tried my best with this only just purchased also…

**Comment by Blumlaut** [comment]
> no such export getcoreobject in resources qb core.

your qbcore is not exposing required events, likely the resource is missing, not started or broken
