### ISSUE TITLE
Screenshot Feature not working

### ISSUE THREAD

**Issue by tatteddeluxe** [Blumlaut/EasyAdmin#599]
**Describe the issue**
A clear and concise description of what the issue is.

So I was trying to add the screenshot feature and Ive done the steps listed on the support page 

setr ea_screenshoturl "https://discordapp.com/api/webhooks/YOUR_WEBHOOK/URL"
setr ea_screenshotfield "files[]"
 
That string is whats in my server cfg except the webhook is changed.
It just keeps saying Screenshot Failed. 

**Attempted Solutions**
Describe what you have done to attempt to fix it.

Ive tried to make a new webhook. Ive tried to reinstall screenshot basic. I'm at a loss im not sure if I need to configure something with screenshot basic or what im missing

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

**Server Infos (please complete the following information):**
 - OS: [e.g. Windows Server 2019, Debian 10..]
 - FXServer Version [latest]
 - EasyAdmin Version Latest as I reinstalled to see if that was the issue

**Additional context**

**Comment by Blumlaut** [comment]
> **Screenshots/Logs**
> If applicable, attach screenshots or log files here to help explain your problem.

have you tried checking your client or server logs?
