### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Trelluder** [Blumlaut/EasyAdmin#601]
Transaction ID: tbx-446923a72790-95d9d8

Product:

1x ESX Plugin

Total: 8.98 EUR

Sales Tax: 1.43 EUR

Hello, I just bought your ESX Easyadmin but can't download it anywhere.

You have no created assets.

How do I download it ?

**Comment by Blumlaut** [comment]
https://keymaster.fivem.net/asset-grants

and dont share your transaction id in public...

**Comment by Trelluder** [comment]
Hello, didn't know it was going to be public sorry! I have no assets "You
have no granted assets." Tried different emails

Am Di., 10. Jan. 2023 um 22:01 Uhr schrieb Blumlaut <
***@***.***>:

**Comment by Trelluder** [comment]
Hello, didn't know it would be public, sorry! I Have No Assets "You have no
promised assets." Please try checking email

Am Di., 10. Jan. 2023 um 22:20 Uhr schrieb Bildungssystem <
***@***.***>:

**Comment by Trelluder** [comment]
![Screenshot 2023-01-10 222248](https://user-images.githubusercontent.com/122402736/211665278-70f9fb0f-368a-4a16-9e96-fd4f6ce592f8.png)
