### ISSUE TITLE
[                 cmd] Access denied for command add_principal.

### ISSUE THREAD

**Issue by DaddyJakeon** [Blumlaut/EasyAdmin#607]
saying Access denied for command add_principal when trying to set things up

EVERYTHING

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

**Server Infos (please complete the following information):**
 - OS: unknown
 - 6195
 - Version 6.91

**Additional context**
FUCKING CONFUSION

**Comment by Blumlaut** [comment]
the bot has told you twice now to fill out the issue, you end up creating a third issue, filling out Server Specs and nothing else, are you being forreal right now?
