### ISSUE TITLE
Updating EasyAdmin

### ISSUE THREAD

**Issue by Guymcguy420** [Blumlaut/EasyAdmin#609]
I was wondering how I should go about updating EasyAdmin without ruining my permissions that I already have configured? This would be very helpful thanks!

**Comment by Blumlaut** [comment]
https://easyadmin.readthedocs.io/en/latest/updating/

**Comment by Guymcguy420** [comment]
> https://easyadmin.readthedocs.io/en/latest/updating/

I went to this website but it tells me nothing about which files I need to keep and which I should change when updating. I don't want to break my permissions. Is there any file I need to keep in my current EasyAdmin version?

**Comment by Blumlaut** [comment]
you should copy all files from the latest release into your EasyAdmin folders, EasyAdmin will take care of file migrations (if needed) itself.
