### ISSUE TITLE
Ace Perms Live Update Question

### ISSUE THREAD

**Issue by ryanb9038** [Blumlaut/EasyAdmin#610]
Hello, I am very happy with how easily ace perms can be updated with discord roles with this script. I recently switched from badger's DiscordAcePerms script to EasyAdmin since this one live updates. One question I have is if there is any way to force vMenu to read the users new perms once your script adds the perms to completely remove the need to re-join the server for discord based vMenu stuff. Thanks!

**Comment by Blumlaut** [comment]
vMenu probably doesn't refresh the permissions at runtime, this isn't really an EasyAdmin issue.
