### ISSUE TITLE
need help just started 

### ISSUE THREAD

**Issue by spiderthunder88** [Blumlaut/EasyAdmin#612]
script:EasyAdmin] SCRIPT ERROR in promise (unhandled rejection): TypeError: Cannot read properties of undefined (reading 'send')
[    script:EasyAdmin] > logNewReport (@EasyAdmin/server/bot/reports.js:43)

**Comment by ChickenDipper1** [comment]
Hey, did you figure this out? Have the same and can't find the issue, I know related to reports in game going to discord.

Thanks.

**Comment by ChickenDipper1** [comment]
All good, was related to report forwarding
