### ISSUE TITLE
issue with the text on the easyadmin menue

### ISSUE THREAD

**Issue by commandoultra8** [Blumlaut/EasyAdmin#613]
![Screenshot (18)](https://user-images.githubusercontent.com/118610210/214072257-7eb00d83-a83f-4233-9124-cd10eafbe86b.png)

i need to know how i sort this as i overlaps the other parts and i want the numbers and the name of the person on the same tab can u help me to solve this issue

**Comment by Dexxieee** [comment]
skill issue buddy
