### ISSUE TITLE
Griefing menu

### ISSUE THREAD

**Issue by stancednicholas** [Blumlaut/EasyAdmin#617]
**Describe the issue**
just bought the Grief Menu and currently trying to make it work on the server i play on, had the owner do the keymaster part and adding in. but i can't seem to make it work

**Attempted Solutions**
i have tried making permission "True" also have i putten access to the roles that are allowed but yet it don't work

**Screenshots/Logs**
no screenshot needed for this

**Server Infos (please complete the following information):**
 - OS: [e.g. Windows Server 2019, Debian 10..] that is something im not sure about, server is a hosted we pay monthly for 
 - FXServer Version [trying to find but won't be shown]
 - EasyAdmin Version 6.91

**Comment by thecrankytech** [comment]
No screenshot or logs, no support lol ` i can't seem to make it work` doesnt seem to give much
