### ISSUE TITLE
ESX Plugin not working

### ISSUE THREAD

**Issue by giacobranco** [Blumlaut/EasyAdmin#618]
Issue
I purchased three plugins one of which being the esx plugin. I installed it by putting the esx folder in the plugins folder and deleting the fxmanifest.lua. When I go into the game it says I can buy it on the store.
Attempted Solution
I tried re installing the plugin, I tried reinstalling easy admin. I also verified that it was in my cfx asset folder and it was.
**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.
[    script:EasyAdmin] EasyAdmin: You are using an unstable version of EasyAdmin, if this was not your intention, please download the latest stable version from https://github.com/Blumlaut/EasyAdmin/releases/tag/6.91
[    script:EasyAdmin] Logged in as FIVEM API#1062!
[    c-scripting-core] Creating script environments for EasyAdmin
[    script:EasyAdmin] 
[    script:EasyAdmin]  _______ _______ _______ __   __ _______ ______  _______ _____ __   _
[    script:EasyAdmin]  |______ |_____| |______   \_/   |_____| |     \ |  |  |   |   | \  |
[    script:EasyAdmin]  |______ |     | ______|    |    |     | |_____/ |  |  | __|__ |  \_|
[    script:EasyAdmin]                            Version 6.91 (UNSTABLE PRE-RELEASE!)
[ citizen-server-impl] Started resource EasyAdmin
**Server Infos (please complete the following information):**
 - OS: Windows 11
 - FXServer Version 6195
 - EasyAdmin Version 6.91

**Additional context**

**Comment by Blumlaut** [comment]
> When I go into the game it says I can buy it on the store.

is your ESX even running? check the clientside log when joining/opening EA.

**Comment by giacobranco** [comment]
If you mean the servers esx, yes it is loaded and everything esx related is working.

**Comment by giacobranco** [comment]
I just got this Im not sure if it was there before. 
![Screenshot 2023-01-26 212107](https://user-images.githubusercontent.com/78387164/214996718-9eb32597-7e52-4049-8e30-8fa7ccfc0191.png)
