### ISSUE TITLE
[BUG] EasyAdmin crashes

### ISSUE THREAD

**Issue by Daan9222** [Blumlaut/EasyAdmin#620]
**Describe the bug**
When i select a player that isnt fully loaded into the server does the menu crash and i cant open it for a while. I also get it when a player leaves when you spectate him.

**To Reproduce**
1. Open menu
2. Select a player that is joining
3. You get a crash and the menu closes

**Expected behavior**
That there is a explaining or a fix

**Screenshots/Logs**
Dont have it.

**Server Infos (please complete the following information):**
 - OS: linux debian
 - FXServer Version [e.g. 5848]
 - EasyAdmin Version

**Additional context**
No.

**Comment by Blumlaut** [comment]
> **Screenshots/Logs**
> Dont have it.

are you fucking kidding me? try harder.

**Comment by Daan9222** [comment]
Why are u so toxic to me? What screenshot do u need? The me u just closes and i dont get any errors in console

**Comment by Daan9222** [comment]
For real i already created 2 support topics in dc that was not good enough and i dont get a reason why so i headed to githun and its still not good bruh dont you want to fix this or something jesus
