### ISSUE TITLE
[BUG] EasyAdmin Crashes

### ISSUE THREAD

**Issue by Daan9222** [Blumlaut/EasyAdmin#621]
**Describe the bug**
When i select a player that is still loading or not fully loaded closes the menu and cant i open it for a while 

**To Reproduce**
1. Select a loading player
2. Your menu closes
3. You get a notify from ea (see screenshot)

**Expected behavior**
I hope that this can be fixed or it has a explanation why this is happening

**Screenshots/Logs**
https://cdn.discordapp.com/attachments/1060301560367820843/1067551322339033148/image.png
Console:
This error pops out when i select a player and crash
[  script:es_extended] SCRIPT ERROR: @es_extended/server/main.lua:613: attempt to index a nil value (local 'xPlayer')
[  script:es_extended] > ? (@es_extended/server/main.lua:613)
[  script:es_extended] > TriggerServerCallback (@es_extended/server/functions.lua:172)
[  script:es_extended] > handler (@es_extended/server/common.lua:114)

**Server Infos (please complete the following information):**
 - OS: [Linux Server]
 - FXServer Version [e.g. 5848]
 - EasyAdmin Version: 6.91

**Additional context**
Sorry for i think my rude reactions but i try to fix it already for days and i get a little frustrated.

**Comment by Blumlaut** [comment]
your ESX is broken
