### ISSUE TITLE
Screenshot in EasyAdmin panel

### ISSUE THREAD

**Issue by Appeltje333** [Blumlaut/EasyAdmin#627]
**Describe the issue**
Hi! Just downloaded the newest version of EasyAdmin. Before this one i had one of the older versions but this one had the ability to take a screenshot of a player. With the newer version i do not have this option anymore. It is not listed in the EasyAdmin panel. Do you guys have a solution?

 - EasyAdmin Version 6.91

**Comment by Blumlaut** [comment]
screenshots require the `player.screenshot` permission and that screenshot-basic is installed and running

**Comment by Appeltje333** [comment]
Yes, we have screenshot-basic installed and the player.screenshot is granted. We now have the option to take a screenshot. The only thing now is that we dont get the right spot to put the webhook

**Comment by Blumlaut** [comment]
read the docs
