### ISSUE TITLE
2 problems

### ISSUE THREAD

**Issue by Levicootje** [Blumlaut/EasyAdmin#630]
**Describe the issue**
1 I want to turn /report of how can i do that?
2 /spectate and /freeze doesnt work 
 /spectate i spawn under the map and must relog and /freeze is not from easyadmin or something
 
**Attempted Solutions**
i dont know how to fix it 
**Screenshots/Logs**
1 spectate 
![image](https://user-images.githubusercontent.com/66410960/216622251-752bbad7-f024-4954-a621-cf3290db1d71.png)
2 freeze there is no true or false and this is then not from easyadmin
![image](https://user-images.githubusercontent.com/66410960/216622525-56a80e73-fd18-44cb-a94b-246d521e03fc.png)

**Server Infos (please complete the following information):**
 - OS: [e.g. Windows Server 2019, Debian 10..]
 - FXServer Version [e.g. 5123]
 - EasyAdmin Version 6.

**Additional context**

**Comment by Blumlaut** [comment]
provide logs.

**Comment by Levicootje** [comment]
Is nothing in logs that cn tell the problem and the problem on /freeze?
