### ISSUE TITLE
Saving Banlist.jason failed

### ISSUE THREAD

**Issue by OzzyClown** [Blumlaut/EasyAdmin#634]
**Describe the issue**
Saving banlist.jason failed! Please check if easyadmin has permissions to write in its own folder

**Attempted Solutions**
added the permissions for it in the server config 2 times now and deleted easyadmin and installed a fresh one and still does it

**Screenshots/Logs**
https://i.imgur.com/tYGjESr.png

**Server Infos (please complete the following information):**
 - OS: using zaphosting windows
 - FXServer Version = pretty sure its 2699
 - EasyAdmin Version = EasyAdmin-6.91

**Additional context**
![FiveM_b2699_GTAProcess_IieGa3x3x9](https://user-images.githubusercontent.com/103995664/217817838-aa2be87e-5f89-440f-a417-02020802663c.png)

**Comment by Blumlaut** [comment]
Set the FTP Permissions in the ZAP-Hosting FTP Page.
