### ISSUE TITLE
ESX Deprecation Notice

### ISSUE THREAD

**Issue by SFASLY** [Blumlaut/EasyAdmin#642]
**Describe the issue**
easyadmin does not start in game because it accesses the esx:getSharedObject

**Attempted Solutions**
[ script:es_extended] [WARNING] EasyAdmin used esx:getSharedObject, this method is deprecated and should not be used, On 30/11/2022 esx:getSharedObject will come to EOL and be fully removed! Refer to https://docs.esx-framework.org/tutorials/sharedevent for more info! I went to the site and tried to paste it into easy admin but couldn't find it

**Screenshots/Logs**
unfortunately no picture

**Server Infos (please complete the following information):**
 - Windows Server 2019
 - FXServer Version 6283
 - EasyAdmin Version 6.9
 - legacy 1.8.5

**Additional context**
it would be nice if you could help with that

**Comment by Blumlaut** [comment]
i updated the ESX plugin, redownload it from your keymaster and check if it works.
