### ISSUE TITLE
getSharedObject error

### ISSUE THREAD

**Issue by TBosstradamus** [Blumlaut/EasyAdmin#643]
**Describe the issue**
The ESX plugin does not start due to the new ESX 1.9 version.
F8 ErrorCode: Resource ^5EasyAdmin^7 Used the ^5getSharedObject^7 Event, this event ^1no longer exists!^7 Visit https://documentation.esx-framework.org/tutorials/sharedevent for how to fix!

**Attempted Solutions**
Nothing, since I do not know how to adjust it.

**Screenshots/Logs**
[    454063] [b2699_GTAProce]             MainThrd/ [^1ERROR^7] Resource ^5EasyAdmin^7 Used the ^5getSharedObject^7 Event, this event ^1no longer exists!^7 Visit https://documentation.esx-framework.org/tutorials/sharedevent for how to fix!

**Server Infos (please complete the following information):**
 - OS: Windows Server 2019
 - FXServer Version 6281
 - EasyAdmin Version: 6.1.9

**Additional context**
[Add any other context about the problem here.](https://documentation.esx-framework.org/tutorials/sharedevent)

**Comment by Blumlaut** [comment]
duplicate of https://github.com/Blumlaut/EasyAdmin/issues/642
