### ISSUE TITLE
[BUG] On some server startups/server restarts EasyAdmin Bot does not activate

### ISSUE THREAD

**Issue by ChickenDipper1** [Blumlaut/EasyAdmin#644]
**Describe the bug**
Sometimes on server startup or on server restarts the EasyAdmin Discord Bot will not initialize.

I will then get the follow server console errors when a player join the server:

[    script:EasyAdmin] SCRIPT ERROR in event `playerConnecting': ReferenceError: EasyAdmin is not defined
[    script:EasyAdmin] > <unknown> (@EasyAdmin/server/bot/player_events.js:16)
[    script:EasyAdmin] 
[ script:connectqueue] QUEUE: ChickenDipper[steam:1100001058ec982] was placed 1/1 in queue
[ script:connectqueue] QUEUE: ChickenDipper[steam:1100001058ec982] is loading into the server
[    script:EasyAdmin] SCRIPT ERROR in event `playerJoining': ReferenceError: EasyAdmin is not defined
[    script:EasyAdmin] > <unknown> (@EasyAdmin/server/bot/player_events.js:7)
[    script:EasyAdmin] 

**To Reproduce**
1. Nothing specific, just restart the server or boot from turned up, seems quite random.

**Expected behavior**
Discord bot should initialize every time.

**Screenshots/Logs**
N/A

**Server Infos (please complete the following information):**
 - OS: Windows Server 2022
 - FXServer Version 6230
 - EasyAdmin Version : 6.91
 - 
**Additional context**
N/A

**Comment by Blumlaut** [comment]
> **Screenshots/Logs**
> N/A

Please provide a repro case and/or a full server log, "it sometimes doesnt work" doesn't provide any infos.

**Comment by ChickenDipper1** [comment]
Hello,

I just wanted to let you know that moving EasyAdmin to the very last ensured script seems to have stopped this from happening.

Thanks.
