### ISSUE TITLE
Connect error

### ISSUE THREAD

**Issue by ReconReaper** [Blumlaut/EasyAdmin#649]
**Describe the issue**
cant connect to local when script is running it requires to see steam open even thoe i have. 

**Attempted Solutions**
make sure steam is on. i also stop the script and now i can get in. but soon it start i cant

**Screenshot
![FiveM_b2802_GTAProcess_7CDxIXVF90](https://user-images.githubusercontent.com/43545113/219974766-aaf0cbc4-a51c-4fc8-a92d-66a7320c0b7c.png)
[s/Logs**](url)

**Server Infos (please complete the following information):**
 - OS: [e.g. Windows Server 2019, Debian 10..]
 - FXServer Version [e.g. 5123]
 - EasyAdmin Version

**Additional context**
![FiveM_b2802_GTAProcess_7CDxIXVF90](https://user-images.githubusercontent.com/43545113/219974776-ceed6e77-bbc9-4124-bdb6-2917ec3ac395.png)

**Comment by Blumlaut** [comment]
have you done what the error tells you and read the server log?

**Comment by ReconReaper** [comment]
there no error. nor in the server console or my log.
![FiveM_b2802_GTAProcess_0PRHE5FDtc](https://user-images.githubusercontent.com/43545113/220172892-cf9c2461-7bd5-4258-9284-1682917a66ba.png)

**Comment by Blumlaut** [comment]
not a rottenv issue then.
