### ISSUE TITLE
Discord Sync

### ISSUE THREAD

**Issue by Amok53** [Blumlaut/EasyAdmin#651]
**Describe the issue**
Discord Perms - Connection...
I link my discord with my server and there are no sync with the roles i have 
I do it in the easyadmin_permissions.cfg 
e.g - add_principal role:32423424342 group.dev

**Server Infos (please complete the following information):**
 - OS: [Windows Server 2019]
 - FXServer Version [6279]
 - EasyAdmin Version 6.91
![image](https://user-images.githubusercontent.com/118230599/220818776-2e70ef19-a36f-4016-9746-15ea3d39a803.png)

**Comment by Blumlaut** [comment]
fill out the template.
