### ISSUE TITLE
backups folder permissions

### ISSUE THREAD

**Issue by ggoodell2** [Blumlaut/EasyAdmin#653]
**Describe the issue**
i get this in my server consoleEasyAdmin: Saving banlist backup failed! Please check if EasyAdmin has Permission to write in the backups folder!

**Attempted Solutions**
looked through readm e for clues.

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

**Server Infos (please complete the following information):**
 - OS: zap hosting
 - FXServer Version 6287
 - EasyAdmin Version current

**Additional context**

**Comment by Blumlaut** [comment]
you should fix your easyadmin folders permissions, likely your fxserver user cant write into the resources directory.

**Comment by ggoodell2** [comment]
i dont know how to do that
