### ISSUE TITLE
Quick Question Regarding EasyAdmin integration with Discord

### ISSUE THREAD

**Issue by darthmedic** [Blumlaut/EasyAdmin#658]
**Describe the issue**
I attempted to create a ticket in your discord but was referred to here to create an issue ticket. We are using EasyAdmin(which is amazing!) but was wondering if there is a way to make the report bot ping Server Staff in discord when someone makes a report. 

**Server Infos (please complete the following information):**
 - OS: Windows
 - FXServer Version 6288
 - EasyAdmin Version 7.0

**Comment by Blumlaut** [comment]
you'd have to change the code for that.
