### ISSUE TITLE
SCRIPT ERROR in promise (unhandled rejection): DiscordAPIError[10008]: Unknown Message

### ISSUE THREAD

**Issue by Vannsa** [Blumlaut/EasyAdmin#659]
**The issue:**
Getting this error spammed in the Server Console

![Screenshot_5](https://user-images.githubusercontent.com/93377560/222262418-0b8925ba-91c7-4ebf-9555-1ae59b8ec285.png)

**Attempted Solutions:**
Looked into the Docs 

**Server Infos:**
 - OS: Windows Server 2019 Standard Evaluation
 - FXServer Version: 6285
 - EasyAdmin Version: 6.9

We changed the Script Name from Easyadmin to somenthing else. Don't know if it's relevant.

**Comment by Blumlaut** [comment]
> We changed the Script Name from Easyadmin to somenthing else. Don't know if it's relevant.

probably not, this looks like some ticked action, did you delete the "server status" message while the bot was running?

**Comment by Vannsa** [comment]
I don't think so. We got the error for months now. Let's say we did that, what would be the solution for that problem?

**Comment by Blumlaut** [comment]
restarting easyadmin should do, do you have the server status enabled? If so try disabling it and see if the error dissapears.
