### ISSUE TITLE
EasyAdmin Permissions not working 

### ISSUE THREAD

**Issue by UserBlame21** [Blumlaut/EasyAdmin#660]
**Describe the issue**
Why I try and do EasyAdmin permissions for seperate ranks e.g just group.staff then h.admin im trying to make it so staff dont have access to like ban people but group.hadmins do. Same with like teleporting everyone and more permissions but I have tried a lot of things but dont know how to get it so one role has permission to ban but the other one dont. Like if I give permission to hadmin somehow staff get the permission as well and I dont know how to fix it.

**Attempted Solutions**
I have tried to do add_ace group.staff easyadmin.player.teleport.everyone deny  and add_ace group.hadmin easyadmin.player.teleport.everyone allow	but in game staff still have permission. I also tried removing the teleport everyone deny and just left the allow one for the head admin.

**Screenshots/Logs**
https://i.imgur.com/gNJldjc.png

**Comment by thecrankytech** [comment]
Don't deny permissions, either allow the permission or don't include it at all, documentation clearly states that.

You're assigning `easyadmin allow` to the groups at the top, this will give them all permissions regardless of what you put below it.
