### ISSUE TITLE
Error: Error: Received one or more errors

### ISSUE THREAD

**Issue by IIROD** [Blumlaut/EasyAdmin#662]
Good morning,

I have this error which appears at startup and while using the server

[ script:EasyAdmin] Error: Error: Received one or more errors
[ script:EasyAdmin] at ObjectValidator.handleIgnoreStrategy (C:\Users\Jarod\Desktop\XeddaV2\resources\[essential]\EasyAdmin\node_modules\@sapphire\shapeshift\dist\index.js:1252:70)
[ script:EasyAdmin] at ObjectValidator.handleStrategy (C:\Users\Jarod\Desktop\XeddaV2\resources\[essential]\EasyAdmin\node_modules\@sapphire\shapeshift\dist\index.js:1105:47)
[ script:EasyAdmin] at ObjectValidator.handle (C:\Users\Jarod\Desktop\XeddaV2\resources\[essential]\EasyAdmin\node_modules\@sapphire\shapeshift\dist\index.js:1205:17)
[ script:EasyAdmin] at ObjectValidator.parse (C:\Users\Jarod\Desktop\XeddaV2\resources\[essential]\EasyAdmin\node_modules\@sapphire\shapeshift\dist\index.js:201:88)
[ script:EasyAdmin] at EmbedBuilder.setAuthor (C:\Users\Jarod\Desktop\XeddaV2\resources\[essential]\EasyAdmin\node_modules\@discordjs\builders\dist\index.js:223:26)
[script:EasyAdmin] at getServerStatus (@EasyAdmin/server/bot/server_status.js:64:19)
[script:EasyAdmin] at async updateServerStatus (@EasyAdmin/server/bot/server_status.js:125:19)

I haven't done anything to try to solve this problem I can't find a solution on google

thank you in advance for your help

**Comment by Blumlaut** [comment]
Looks like your server name, owner avatar or cfx.re join url couldn't be determined by EasyAdmin
https://github.com/Blumlaut/EasyAdmin/blob/846923ced9bd6f72afd8475fc5016eaddd515344/server/bot/server_status.js#L64

**Comment by IIROD** [comment]
ok thank you very much that's fixed
