### ISSUE TITLE
My EayAdmin Bot Isn't Going Online I've Read The Docs 5 Times And I Still Don't Understand Why It Won't Go Online Please Help

### ISSUE THREAD

**Issue by TrapYung** [Blumlaut/EasyAdmin#665]
**Describe the issue**
A clear and concise description of what the issue is.

**Attempted Solutions**
Im trying to get my easyadmin bot to work but it wont go online ive looked at the docs trying to figure it out

**Screenshots/Logs**
![Screenshot_20230310_122939](https://user-images.githubusercontent.com/127544027/224395408-f3734baa-6ccc-48fd-bfd6-ce64d49d4ee8.png)

**Server Infos (please complete the following information):**
Zap Hosting EasyAdmin 

**Additional context**
I put set ea_botToken "botToken" in my server.cfg with my bot token but where do I put [    script:EasyAdmin] Logged in as BotName#1234!?

**Comment by Blumlaut** [comment]
> **Screenshots/Logs**

Provide actual server logs.

**Comment by TrapYung** [comment]
> 

ok

**Comment by TrapYung** [comment]
![Screenshot_20230310_122939](https://user-images.githubusercontent.com/127544027/224447470-35da6400-637a-442f-94f5-fd8e36fc79a8.png)
