### ISSUE TITLE
Menu not appearing for mods

### ISSUE THREAD

**Issue by harrydarnell** [Blumlaut/EasyAdmin#666]
**Describe the issue**
For some reason after adding the ace perms for moderators the actual UI itself will not open for them after typing in the easyadmin command

**Attempted Solutions**
I've made adjustment with ace perms and groups

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

![image](https://user-images.githubusercontent.com/107180761/224498397-27652568-ba04-4210-836f-da28b2659df1.png)

**Server Infos (please complete the following information):**

 - FXServer Version v5.2.0 atop FXServer 6231
 - EasyAdmin Version

**Additional context**

**Comment by Blumlaut** [comment]
most of your add_ace and add_principal calls is wrong, read the fivem docs 
https://docs.fivem.net/docs/server-manual/server-commands/#add_ace-principal-object-allowdeny

**Comment by harrydarnell** [comment]
I'm having some major trouble with this and somewhat short on time (got a crying baby in my arms IRL lol). Could I possibly pay you to restructure ours? I'll send over the cnfg

**Comment by harrydarnell** [comment]
# Voice config
setr voice_useNativeAudio true
setr voice_useSendingRangeOnly true
setr voice_defaultCycle "GRAVE"
setr voice_defaultVolume 0.3
setr voice_enableRadioAnim 1
setr voice_enableSubmix 1
setr voice_syncData 1

setr chat_showQuits 0
setr chat_showJoins 0

set mysql_slow_query_warning 250

# FiveM Appearance
setr fivem-appearance:locale "en"
add_ace resource.fivem-appearance command.list_aces allow

# QBCore locale config
setr qb_locale "en"

# QBCore UseTarget
setr UseTarget true

# These resources will start by default.
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure basic-gamemode
ensure hardcap
ensure baseevents

# QBCore & Extra stuff
ensure WTFAdminPanel
ensure qb-core
#ensure PolyZone
ensure qb-target
ensure gfx-base
ensure qb-blackjack
ensure [qb]
ensure [EUP]
ensure [housing]
ensure [standalone]
ensure [voice]
ensure skiddsounds
ensure gks_gotur
ensure gks_racing
ensure xsound
ensure gks_ebay
ensure gksphone
ensure gks_rentacar
ensure nearest-postal
ensure [defaultmaps]
ensure [custommaps]
ensure ch_lightshow_assets
ensure ch_lightshow_fiv3devs_asgard
ensure [carpack]
ensure [qb-addons]
ensure [trucking]
ensure [ebujimscripts]
ensure [fire]
ensure [police]
##ensure [senora]
ensure [customweapons]
ensure [hospital]
##ensure [drift]
ensure [phone]
ensure sd_lib
ensure [criminal]
ensure [casino]
ensure utk_hackdependency
ensure utk_fingerprint
ensure sonoranradio
ensure smartsigns_sonoran
ensure advanced_drugs_creator
ensure BakiTelli_itemsell
ensure [newbaby]
ensure [derby]
ensure [arcade]


## Permissions ##
add_ace group.admin command allow # allow all commands

## Resource Permissions - ox_lib ##
add_ace resource.ox_lib command.add_ace allow
add_ace resource.ox_lib command.remove_ace allow
add_ace resource.ox_lib command.add_principal allow
add_ace resource.ox_lib command.remove_principal allow

##Ace Permissions for Asgard LightShow [Currently set to anyone can control it. Admin only option is commented out.]
#add_ace group.admin "ch_lightshow_fiv3devs_asgard.designer" allow
#add_ace group.admin "ch_lightshow_fiv3devs_asgard.console" allow
add_ace builtin.everyone "ch_lightshow_fiv3devs_asgard.designer" allow
add_ace builtin.everyone "ch_lightshow_fiv3devs_asgard.console" allow

#add_principal identifier.{{principalMasterIdentifier}} qbcore.god <- doesn't exist yet, change the generated one below to qbcore.god


add_principal identifier.discord:652779477088206880 qbcore.god qbadmin.join## Darnell
add_principal identifier.discord:357343060444839947 qbcore.god qbadmin.join## Outlaw
add_principal identifier.discord:360117913925058562 qbcore.god qbadmin.join## Bella
add_principal identifier.discord:272913289938337792 qbcore.god qbadmin.join## Jason


# Resources
add_ace resource.qb-core command allow # Allow qb-core to execute commands

# Gods
add_ace qbcore.god command allow # Allow all commands
add_ace qbcore.dev command allow
add_ace group.dev command allow
add_ace group.admin easyadmin allow # Easy admin

# Commands
add_ace group.admin command.muteply allow # Allow Adims to mute players with command: /muteply (tgtPly) (duration)

# Inheritance
add_principal qbcore.god group.admin # Allow gods access to the main admin group used to get all default permissions
add_principal qbcore.god qbcore.admin # Allow gods access to admin commands
add_principal qbcore.dev group.admin
add_principal qbcore.dev qbcore.admin
add_principal identifier.discord:357343060444839947 group.admin ## Outlaw
add_principal identifier.discord:652779477088206880 group.admin ## Darnell
add_principal identifier.discord:619492992041877505 group.admin ## Chris Hamo
add_principal identifier.discord:360117913925058562 group.admin ## Bella
add_principal identifier.discord:401931603116294169 group.admin ## Jose
add_principal identifier.discord:631733035683020800 group.admin ## Hannah (Mikes Wife)
add_principal identifier.discord:531342957270401064 group.admin ## Woods
add_principal identifier.discord:456513717635645441 group.admin ## Copperson
add_principal identifier.discord:272913289938337792 group.admin ## Jason
add_principal identifier.discord:448420788580646913 group.admin ## James Marshall Webb
add_principal identifier.discord:713610768188178473 group.admin ## Chuck Walker
add_principal identifier.discord:296689092220026910 group.admin ## Chuck 
add_principal identifier.discord:635165059823435856 group.admin ## D00mster 

################################################################# EASY - SCRIPTS ###################################################

add_ace resource.zdiscord command allow ##FOR WHITELISTING SCRIPT
add_ace group.zdiscordstaff zdiscord.staffchat allow ##FOR WHITELISTING SCRIPT

add_ace group.admin easy_allowlist allow # Add permission to group
add_principal identifier.c4d1e4863112f939c4d96d262bd34f90dd4c8d70 group.admin # Add player to the group
# add_principal identifier.discord:357343060444839947 group.admin ## Outlaw
# add_principal identifier.discord:652779477088206880 group.admin ## Darnell
# add_principal identifier.discord:360117913925058562 group.admin ## Bella



add_ace group.admin advanced_drugs_creator allow # Add permission to group
add_principal identifier.license:52b38f31c77011a76d0c143e015bab9ab0720143 group.admin # Add player to the group
# add_principal identifier.discord:357343060444839947 group.admin ## Outlaw
# add_principal identifier.discord:652779477088206880 group.admin ## Darnell
# add_principal identifier.discord:360117913925058562 group.admin ## Bella


add_ace group.admin robberies_creator allow # Add permission to group
add_principal identifier.license:f35e240648bfa1e401aa1ae7276aded60c3c34f2 group.admin # Add player to the group
# add_principal identifier.discord:357343060444839947 group.admin ## Outlaw
# add_principal identifier.discord:652779477088206880 group.admin ## Darnell
# add_principal identifier.discord:360117913925058562 group.admin ## Bella

add_ace group.admin doors_creator allow # Add permission to Unknown Steam account


add_ace group.dev doors_creator allow
# add_ace identifier.license:e12cf2f640178bd15c64d9813de527bf5bc78b4b doors_creator allow
add_ace identifier.license:f35e240648bfa1e401aa1ae7276aded60c3c34f2 doors_creator allow # Add permission to Unknown Rockstar license
# add_principal identifier.discord:357343060444839947 group.admin ## Outlaw
# add_principal identifier.discord:652779477088206880 group.admin ## Darnell
# add_principal identifier.discord:360117913925058562 group.admin ## Bella


add_ace group.admin blipcreator allow # Add permission to group
# Can also be identifier.steam:steamid
add_principal identifier.license:1260e6efd3271584d7ed05n45cbf41575252acbc group.admin # Add player to the group
# add_principal identifier.discord:357343060444839947 group.admin ## Outlaw
# add_principal identifier.discord:652779477088206880 group.admin ## Darnell
# add_principal identifier.discord:360117913925058562 group.admin ## Bella

################################# MODERATOR STUFF #######################################################

add_ace group.moderator easyadmin.player.kick allow
add_ace group.moderator easyadmin.player.spectate allow
add_ace group.moderator easyadmin.player.teleport allow
add_ace group.moderator easyadmin.player.slap allow
add_ace group.moderator easyadmin.player.freeze allow
add_ace group.moderator easyadmin.player.ban.temporary
add_ace group.moderator easyadmin.player.ban.permanent
add_ace group.moderator easyadmin.player.ban.view
add_ace group.moderator easyadmin.player.ban.edit
add_ace group.moderator easyadmin.player.ban.remove
add_ace group.moderator easyadmin.player.kick
add_ace group.moderator easyadmin.player.spectate
add_ace group.moderator easyadmin.player.teleport.single
add_ace group.moderator easyadmin.player.warn
add_ace group.moderator easyadmin.player.screenshot
add_ace group.moderator easyadmin.player.reports.view
add_ace group.moderator easyadmin.player.reports.claim
add_ace group.moderator easyadmin.player.reports.process
add_ace group.moderator easyadmin.server.shortcut.add
add_ace group.moderator easyadmin.server.cleanup.peds
add_ace group.moderator easyadmin.server.cleanup.props
add_ace group.moderator easyadmin.server.cleanup.cars
add_ace group.moderator easyadmin.server.chat

# Inheritance
add_principal identifier.discord:290973589534932992 group.moderator easyadmin ## Anita
add_principal identifier.discord:1009572829680902256 group.moderator easyadmin ## BigDiry#3488
add_principal identifier.discord:629454710604169217 group.moderator easyadmin ## Jax Teller
add_principal identifier.discord:701883278025818223 group.moderator easyadmin ## Murf#6866
add_principal identifier.discord:477848422825852937 group.moderator easyadmin ## Samt#1385
add_principal identifier.discord:679197955697147915 group.moderator easyadmin ## Michael Stone#1100


set ea_moderationNotification "https://discord.com/api/webhooks/1084133052881584238/KxFCGwPK1jUdf_n6ebfZbb6yww0vyiqF50Bo0AJHXBcA_MbWsCnEQdtxXR7MISzGKetG"
set ea_enableReportScreenshots "true"
ea_logIdentifier

exec easyadmin_permissions.cfg

exec @pmms/permissions.cfg

**Comment by harrydarnell** [comment]
![image](https://user-images.githubusercontent.com/107180761/224503469-f332f045-af30-40e0-8d77-bdab46a06081.png)
Still wrong?

**Comment by harrydarnell** [comment]
Or 
![image](https://user-images.githubusercontent.com/107180761/224504056-0b47ceca-b738-4e10-9552-06d9f8cd1b42.png)
