### ISSUE TITLE
[BUG] SCRIPT ERROR in promise (unhandled rejection): Error: Unknown Member - On new player join only

### ISSUE THREAD

**Issue by ChickenDipper1** [Blumlaut/EasyAdmin#667]
**Describe the bug**
When a player that has never joined the server before joins, the following error is printed in the txadmin server console:

SCRIPT ERROR in promise (unhandled rejection): Error: Unknown Member

Once the player has joined the server once this message will never appear for that player again.
This doesn't appear to stop EA from functioning normally, I was just wondering if you may have any way to prevent it or any suggestions on what I could check that may be mis-configured.

Thanks.

**Server Infos (please complete the following information):**
 - OS: Server 2019
 - FXServer Version 6293
 - EasyAdmin Version 7.0

**Comment by Blumlaut** [comment]
provide full logs.

**Comment by robert4049** [comment]
I've got the same issue, it seems to be a regression in the latest version.

**Comment by robert4049** [comment]
[     script:x-status] [STATUS SYSTEM INFO] Saved Player(92)
[  script:es_extended] [INFO] Saved player "Ming Wu"
[      script:hardcap] Connecting: lamon
[          script:pac] [Info] [PhoenixAC] [Connection Manager]: Player lamon (No SteamID found.) has connected.
[    script:EasyAdmin] SCRIPT ERROR in promise (unhandled rejection): Error: Unknown Member
[    script:EasyAdmin] 
[    script:qs-crypto] [qs-smartphone] BTC changed its price from 22329.1 to 22321.1
[     script:visn_are] [Warning] 	Tried to get player identifier but player doesnt have a framework player?	91
[     script:visn_are] [Information] 	6 players saved.

**Comment by ChickenDipper1** [comment]
I didn't provide logs because there was nothing in the logs except player connecting. So didn't think there was much point.

It does however seem to be related to the player not being in Discord after some testing.

**Comment by Blumlaut** [comment]
> I've got the same issue, it seems to be a regression in the latest version.

might be due to https://github.com/Blumlaut/EasyAdmin/commit/e9f435266abcd7fff812c7193fdc791b9cac7af4#diff-da138ee0e63cb746e7892e8958a575d183c9273055809587a48b12a485639fcdR26 then, it's great that DJS throws an error instead of returning false or whatever..

**Comment by ChickenDipper1** [comment]
> > I've got the same issue, it seems to be a regression in the latest version.
> 
> might be due to [e9f4352#diff-da138ee0e63cb746e7892e8958a575d183c9273055809587a48b12a485639fcdR26](https://github.com/Blumlaut/EasyAdmin/commit/e9f435266abcd7fff812c7193fdc791b9cac7af4#diff-da138ee0e63cb746e7892e8958a575d183c9273055809587a48b12a485639fcdR26) then, it's great that DJS throws an error instead of returning false or whatever..

Is it actually great though? Or would it be better if it returned false?

**Comment by ChickenDipper1** [comment]
Cool thanks.
