### ISSUE TITLE
ESX Options Bug

### ISSUE THREAD

**Issue by benzyYT** [Blumlaut/EasyAdmin#668]
**Describe the issue**
When I open txAdmin, go to a player and open the ESX options there's only the option for "view player data"

**Attempted Solutions**
Reinstalling multiple times and clean.

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/70480686/224515470-e4914a57-38ab-4d00-b393-240c43e1f6db.png)

**Server Infos (please complete the following information):**
 - OS: Linux Debian 10
 - FXServer Version: No Idea
 - EasyAdmin Version: Newest Release

**Additional context**
This applies to every user on the EasyAdmin

**Comment by Blumlaut** [comment]
provide logs.
