### ISSUE TITLE
EasyAdmin ExperimentalWarning

### ISSUE THREAD

**Issue by J3reezy** [Blumlaut/EasyAdmin#671]
**Describe the issue**
Hey, i installed EasyAdmin version 7.0 and i have a warning

**Attempted Solutions**
i cant figured it out

**Screenshots/Logs**
![Unbenannt](https://user-images.githubusercontent.com/126194626/224808703-61bd7e1a-88e0-4928-9472-ec33bea30585.PNG)

**Server Infos (please complete the following information):**
 - Debian 10
 - FXServer Version [e.g. 6298]
 - EasyAdmin Version 7.9

**Additional context**
would be nice if someone can help me to fix this please

**Comment by Blumlaut** [comment]
The error is self-explainitory, it's a warning because an EasyAdmin dependency uses an experimental feature, its entirely unproblematic and nothing you need (or can) fix

**Comment by J3reezy** [comment]
ah ok thanks
