### ISSUE TITLE
Grief Menu Plugin Error

### ISSUE THREAD

**Issue by seemlly** [Blumlaut/EasyAdmin#675]
**Describe the issue**
The Grief Menu Plugin is giving me the error shown in the image below. I have tried changing up the code a bit but that did not fix it and i dont know what the error is anymore. Any help would be appreciated.

**Attempted Solutions**
Tried changing up the code but that didn't help.

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/124917905/225699367-cac26c2c-9ce9-49ee-a77c-b34c0d126f8c.png)

**Server Infos (please complete the following information):**
OS: Windows Server 2022
FXServer Version 5848
EasyAdmin Version 6.202

**Additional context**
Nothing

**Comment by Blumlaut** [comment]
> EasyAdmin Version 6.202

Update EasyAdmin before attempting any other troubleshooting steps maybe? You are using a version from `Jul 11, 2021`

**Comment by seemlly** [comment]
Witch files do i need to switch out. I dont want to redo everything thats why i havent updated.

**Comment by Blumlaut** [comment]
> Witch files do i need to switch out. I dont want to redo everything thats why i havent updated.

read the docs.
