### ISSUE TITLE
Grief Menu Error

### ISSUE THREAD

**Issue by seemlly** [Blumlaut/EasyAdmin#676]
Describe the issue
The Grief Menu Plugin is giving me the error shown in the image below. I have tried changing up the code a bit but that did not fix it and i dont know what the error is anymore. Any help would be appreciated.

Attempted Solutions
Tried changing up the code but that didn't help.

Screenshots/Logs
![image](https://user-images.githubusercontent.com/124917905/225700903-03b8ca9b-3de4-4f63-bc94-c602b74caa89.png)

Server Infos (please complete the following information):
OS: Windows Server 2022
FXServer Version 5848
EasyAdmin Version 6.202

Additional context
I know you just replied about u updating but witch files do i need to replace. I dont want to redo everything i have done.

**Comment by Blumlaut** [comment]
Don't create new issues about the same issue. https://github.com/Blumlaut/EasyAdmin/issues/675
