### ISSUE TITLE
/calladmin

### ISSUE THREAD

**Issue by Poptarts4Real** [Blumlaut/EasyAdmin#679]
**Describe the issue**
When a player /calladmin it doesn't show up on an admins screen to notify them a report has been created.

**Attempted Solutions**
I've had 4 sets of eyes [Paid Developers] look this over and we cannot figure it out. This has been an issue for a long time.

**Screenshots/Logs**
it doesn't say there are any errors. 

**Server Infos (please complete the following information):**
 - OS : **Linux 5.10.0-20-amd64**
 - FXServer Version : **FXServer-master v1.0.0.6347 linux**
 - EasyAdmin Version : **6.91**

**Additional context**

I currently run a Vmenu server hosted by ZAP. I am the owner. If a screen shot of my diagnostics page is necessary, Let me know!

Thank you,
   -Anthony-

**Comment by Blumlaut** [comment]
> When a player /calladmin it doesn't show up on an admins screen to notify them a report has been created.

are you talking about the notification? These are handled by the [notification plugins](https://github.com/Blumlaut/EasyAdmin/tree/master/plugins/notifications), likely you have one of those and its broken.

**Comment by Poptarts4Real** [comment]
Yes im talking about the notification. 

I use pNotify, and all that looks like its good. 

i also cant seem to find any videos on this anywhere or anyone else even having this issue either. just stopped working one day.

Further help would be appreciated.
