### ISSUE TITLE
Yarn issue

### ISSUE THREAD

**Issue by mikwbm** [Blumlaut/EasyAdmin#680]
**Describe the issue**
Setup and configured my easyadmin for my server and on startup it gives me this error
**Attempted Solutions**
running easyadmin fresh with no configuration 
**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/84595855/226323103-ed063529-4066-4c39-b45b-3ed4cb04e7bb.png)

**Server Infos (please complete the following information):**
 - CPU Model: Intel Xeon® E5-2680 v2
 - Node: v16.9.1
 - OS: Linux 5.10.0-19-amd64
 - FXServer Version {Version: FXServer-master v1.0.0.6352 linux
Resources: 253
OneSync: enabled
Max Clients: 10
txAdmin Version: 5.2.0}
 - EasyAdmin Version 7.0

**Additional context**cc

**Comment by Blumlaut** [comment]
Your FiveM Server does not have permissions to write into EasyAdmin's resource folder, make sure folder permissions allow read and write and the owner of your resources folder is the user your FiveM Server runs under, also, do not run NPM manually.

**Comment by mikwbm** [comment]
its a new zap server. I found the fix u have to "Set FTP permissions" under zap
