### ISSUE TITLE
Setting Admin Perms

### ISSUE THREAD

**Issue by LoadeD223** [Blumlaut/EasyAdmin#683]
**Describe the issue**
Want to know if i can set different type´s of admin groups such as: Moderator; Senior Moderator; Admin; Senior Admin; Staff Manager, etc...

**Attempted Solutions**
Want to know if i can set different type´s of admin groups such as: Moderator; Senior Moderator; Admin; Senior Admin; Staff Manager, etc...

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

**Server Infos (please complete the following information):**
 - OS: [e.g. Windows Server 2019, Debian 10..]
 - FXServer Version [e.g. 5123]
 - EasyAdmin Version

**Additional context**

**Comment by Blumlaut** [comment]
> Want to know if i can set different type´s of admin groups 

yes, refer to the docs.
