### ISSUE TITLE
Everything gets said

### ISSUE THREAD

**Issue by Lenny3003** [Blumlaut/EasyAdmin#686]
**Describe the issue**
Hello!
If i open ingame the EasyAdmin menu a Voice reads everything from the Menu...

**Attempted Solutions**
I reinstalled EasyAdmin, Reinstalled my FiveM, i went into the Settings.

**Screenshots/Logs**
https://streamable.com/71mo46

**Server Infos:**
 - OS: Linux Debian 10 RootServer
 - FXServer Version : 6247 
 - EasyAdmin Version 7.0

**Comment by Blumlaut** [comment]
.. stop messing with random settings and turn of the screen reader??

**Comment by Lenny3003** [comment]
And how do i turn it off? It was just random on
