### ISSUE TITLE
Unable to download EasyAdmin ESX plugin

### ISSUE THREAD

**Issue by Lightstormm** [Blumlaut/EasyAdmin#690]
Describe the issue
Dear team,

After purchasing the ESX plugin on the blumlaut.tebex.io site, I did not receive an email to download it or find a link on the site. I'm sorry for my english, i'm french :)

Best regards

Attempted Solutions
Be able to download the plugin I bought.

**Comment by SlimJim2119** [comment]
you would download it from your keymaster

**Comment by Lightstormm** [comment]
Perfect, thanks a lot for your help :)
