### ISSUE TITLE
Please Help me i release my server in 2 hours (Perms Problem)

### ISSUE THREAD

**Issue by DonEnes** [Blumlaut/EasyAdmin#697]
**Describe the issue**
the following problem, i entered "add_ace group.mod easyadmin allow" in the server.cfg but my team members can't open easyadmin i release in 2 hours and expect a big rush that's very problematic please help!

**Attempted Solutions**
As I said before, I tried to enter "add_ace group.mod easyadmin allow" but that didn't work and I also don't want to enter the only steam hex ids of my team members because it would be very stupid if someone left the team and it would take far too long last

**Screenshots/Logs**
https://i.imgur.com/d1tPdsF.png

**Server Infos (please complete the following information):**
 - Windows
 - newest
 - newest

**Additional context**
/

**Comment by DonEnes** [comment]
nice sup

**Comment by Cloxxxx** [comment]
Hello its because you rename the ressource
