### ISSUE TITLE
Easy Admin Discord Bot Doesn't Respond

### ISSUE THREAD

**Issue by JPryer123** [Blumlaut/EasyAdmin#698]
**Describe the issue**
Easy Admin Bot is Online and shows when people join/leave the server and also shows the server status in its channel, but when trying to run commands like /playerlist or /kick it comes back with 

**Screenshots/Logs**
https://imgur.com/HIvQpER
https://imgur.com/wXK0ApM
https://imgur.com/FRobH95
https://imgur.com/n8QXTro

**Server Infos (please complete the following information):**
 - OS: Zap Hosting Windows Server
 - EasyAdmin Version 7.0

**Additional context**
Only started happening after upgrading to 7.0, was fine on 6.9

**Comment by Blumlaut** [comment]
Provide server logs.

**Comment by JPryer123** [comment]
![Screenshot_58](https://user-images.githubusercontent.com/130216311/230767779-af6ec114-c63d-4839-a081-0abe90988228.png)
![Screenshot_59](https://user-images.githubusercontent.com/130216311/230767780-aacf2764-9407-40c4-939f-85fdedb981a6.png)
