### ISSUE TITLE
Banlist backup

### ISSUE THREAD

**Issue by VoidTechCG** [Blumlaut/EasyAdmin#700]
**Describe the issue**
My Easyadmin says that "saving banlist backup failed!" in my live console and in game

**Attempted Solutions**
Easyadmin Folder has ALL permissions in ALL groups

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/130710786/231897084-fc746602-d4ea-4f4d-8328-836427df0a46.png)
![image](https://user-images.githubusercontent.com/130710786/231897168-5ff32b23-998f-4837-a6aa-0cd4c7b04bf9.png)
Banlist.json permissions : 
![image](https://user-images.githubusercontent.com/130710786/231897792-51753a2b-be10-4b5a-adf6-ad15ddf8923f.png)

**Server Infos (please complete the following information):**
ZAP Hosting CFX-Default Server
 - FXServer Version : 6383
 - EasyAdmin Version : 7.0

**Additional context**
No Other Context

**Comment by Blumlaut** [comment]
You cant set permissions via FTP on ZAP, you have to use the "Set FTP Permissions" button in ZAP's FTP browser page.
