### ISSUE TITLE
Error: [yarn] warning Ignored scripts due to flag.

### ISSUE THREAD

**Issue by ArkadiCSGO** [Blumlaut/EasyAdmin#702]
**Describe the issue**
I install EasyAdmin on my Dev Server and its work but on me Main Server Public is doesn't

**Attempted Solutions**

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/17646201/232464935-8b071653-ca16-4875-b935-07390093f8f6.png)

**Server Infos (please complete the following information):**
 - OS: Debian 10
 - FXServer Version 6383
 - EasyAdmin Version 7.0

**Additional context**

**Comment by Blumlaut** [comment]
looks like you have corrupt KVP Data, rename the "db" folder in your server-data folder and see if the server works then.

**Comment by ArkadiCSGO** [comment]
Thanks you it's work. But i have this now 
![image](https://user-images.githubusercontent.com/17646201/232466324-a128a79c-c48f-4807-a8a5-6af9a2693dbf.png)

**Comment by Blumlaut** [comment]
that's not an error.

**Comment by ArkadiCSGO** [comment]
Thanks for your help !
