### ISSUE TITLE
SCRIPT ERROR in promise (unhandled rejection): Error: Unknown Member[BUG]

### ISSUE THREAD

**Issue by ODOJRP** [Blumlaut/EasyAdmin#711]
Started receiving this message in the console recently around the same time I cleared my servers cache ( not sure if it's due to that) the message is "SCRIPT ERROR in promise (unhandled rejection): Error: Unknown Member"

It appears this message is generated when a user joins the server without the discord application opened. 

![Screenshot 2023-04-24 160502](https://user-images.githubusercontent.com/131712751/234103911-e956b188-2651-4746-ae72-7667cbf938f6.png)

 - OS: [Linux 4.19.0-23-amd64]
 - FXServer Version [v5.2.0 / 6405/ZAP]
 - EasyAdmin Version (7.0)

**Comment by ItssJxstnDe** [comment]
Same

**Comment by Blumlaut** [comment]
https://github.com/Blumlaut/EasyAdmin/issues/667

**Comment by ItssJxstnDe** [comment]
no not closed
any of my members has to do /refreshperms before they join if they dont they dont have perms

**Comment by ItssJxstnDe** [comment]
Fix It Pls
the sync to disord is very very bad

**Comment by Blumlaut** [comment]
that error is not related to the issue you're describing, create a new issue with proper repro steps.

this error is because the player that joined is not in the guild, it's not problematic.

**Comment by ItssJxstnDe** [comment]
"this error is because the player that joined is not in the guild, it's not problematic." He is!
