### ISSUE TITLE
Ace perms for Easyadmin Qb core integration 

### ISSUE THREAD

**Issue by itzWave** [Blumlaut/EasyAdmin#713]
**Describe the issue**
A clear and concise description of what the issue is.
im very confused on how to setup ace perms 
**Attempted Solutions**
Describe what you have done to attempt to fix it.
i have tried setting up ace perms the normal way, but it still doesn't work. 

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.
![image](https://user-images.githubusercontent.com/131832941/234441434-fc104577-2af4-4189-a61d-f47210b7b958.png)

**Server Infos (please complete the following information):**
 - OS: [e.g. Windows Server 2019, Debian 10..] Windows
 - FXServer Version [e.g. 5123] 2372
 - EasyAdmin Version 7.0

**Additional context**

**Comment by DmkKpln** [comment]
Hey, if you have set up QBCore permissions then use qb.core(Group)
Here is a small example:

Instead of 
add_ace group.Owner easyadmin.qb.setjob allow

use
add_ace qbcore.Owner easyadmin.qb.setjob allow
