### ISSUE TITLE
I Dont get all admin options in Redm

### ISSUE THREAD

**Issue by q8tywolf** [Blumlaut/EasyAdmin#715]
**Describe the issue**
I Dont get all admin options in Redm 

for example teleportation.

**Attempted Solutions**
I have given my self 
`add_ace group.admin easyadmin allow
`
but I only see some of the items for RedM is there a cut down version in RedM

**Server Infos (please complete the following information):**
 - OS: [Windows]
 - FXServer Version 1491
 - EasyAdmin Version 7.0

Am using it with rsg-core

**Comment by Blumlaut** [comment]
Screenshots for what you're seeing/missing would be helpful.
