### ISSUE TITLE
Easy Admin Issue

### ISSUE THREAD

**Issue by adorne1** [Blumlaut/EasyAdmin#721]
**Describe the issue**
Easy admin recently started spewing errors at me and i can not seem to stop it. The bot is online, but i can not configure it. The menu works fine in game.

**Attempted Solutions**
Kicked bot and invited in way shown in documentation, made sure everything was updated token wise.

**Screenshots/Logs**
If applicable, attach screenshots or log files here to help explain your problem.

**Server Infos (please complete the following information):**
 - OS: [linux]
 - FXServer Version [6427]
 - EasyAdmin Version 7.0

**Additional context**
N/a
![image](https://user-images.githubusercontent.com/132327825/235774267-57a1e4fd-31fd-4fde-ab93-efbc98f88ca4.png)
![image](https://user-images.githubusercontent.com/132327825/235774312-e84fb19b-c3c0-497c-96c3-8a3641717cf4.png)

**Comment by adorne1** [comment]
Also this error is printed upon running /configure in the discord 
![image](https://user-images.githubusercontent.com/132327825/235781103-03c6c31b-06bd-49ed-907a-424d6c261f71.png)

**Comment by adorne1** [comment]
SCRIPT ERROR in promise (unhandled rejection): TypeError: isJSONEncodable is not a function

**Comment by adorne1** [comment]
Im now on ver6431 and downgraded to 6.7 and im still getting the error. Im not sure what more i can really do. I cant configure the discord integration at all - however the ingame part works fine. Im starting to think maybe i installed it wrong, but thats impossible seeing how the ingame part works fine.

**Comment by Blumlaut** [comment]
The issue is that you installed incorrect versions of dependencies, you should not run yarn or npm inside the easyadmin folder manually, if you did then wipe the folder and start over.

**Comment by adorne1** [comment]
> The issue is that you installed incorrect versions of dependencies, you should not run yarn or npm inside the easyadmin folder manually, if you did then wipe the folder and start over.

After starting a fresh download, i get these errors on my first time launching the resource.

![image](https://user-images.githubusercontent.com/132327825/236329506-4ec6532e-585e-4012-b50f-35330cd24ec6.png)

**Comment by adorne1** [comment]
This discord application is not responding either - further more after restarting it again i still get JSONnotencodable. 

![image](https://user-images.githubusercontent.com/132327825/236329829-3193e28c-2128-45d5-a562-b11cd906c1f2.png)

**Comment by Blumlaut** [comment]
I just pushed a Release 7.01, try using that instead:
https://github.com/Blumlaut/EasyAdmin/releases/tag/7.01

**Comment by adorne1** [comment]
YES IT WORKS NOW BLU THANKS SO MUCH MWAH!!!!!
