### ISSUE TITLE
7.0.1 

### ISSUE THREAD

**Issue by adorne1** [Blumlaut/EasyAdmin#722]
**Describe the issue**
After 7.0.1 discord integration works fine, however following the update my console is printing a new error, and not posting certain logs.. currently the only log i can get to print anything to discord is calladmin logs, these reset after each server restart as well. The error is pasted below.

**Attempted Solutions**
Reinstall, reconfigured bot, cleared EA config. 

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/132327825/236344888-bce64f09-3e96-4f31-82ac-2d3e7dea3328.png)
Whats shows up below the error is simply me resetting the configuration for the calladmin log, further more - when a player is dropped, the same error is shown but instead of 'send' it shows 'edit.' **See Below**
![image](https://user-images.githubusercontent.com/132327825/236345041-57c26954-339d-460a-be4f-5596398e7cf2.png)

**Server Infos (please complete the following information):**
 - OS: [Linux]
 - FXServer Version [6431]
 - EasyAdmin Version 7.0.1

**Additional context**
N/A

**Comment by adorne1** [comment]
Sorry for being back so soon lol..

**Comment by Blumlaut** [comment]
one of your configured channels is invalid

**Comment by adorne1** [comment]
![image](https://user-images.githubusercontent.com/132327825/236346035-7d601a39-3350-4a2f-b7e3-4269c33de304.png)
I've wiped my config so that i exclusively can test channel by channel - i can not see how a channel is invalid when done this way.

See config: 
![image](https://user-images.githubusercontent.com/132327825/236346401-3abcc19b-6778-4c78-8d31-f60f45614509.png)

**Comment by Blumlaut** [comment]
does the bot have read and write permissions for the channel?

**Comment by adorne1** [comment]
> does the bot have read and write permissions for the channel?

I've given the bot administrator since I thought that could be an issue as well.

**Comment by Blumlaut** [comment]
https://github.com/Blumlaut/EasyAdmin/blob/master/server/bot/reports.js#L40

channel is fetched from cache, maybe try sending a message into the channel and see if the bot picks the channel up from there?

**Comment by adorne1** [comment]
Doesn't seem to be working either, I'm clearing my cache atm, i'll let you know if that works. But it might be an issue with channel or message object. It only stops working everytime i restart EA.

**Comment by Blumlaut** [comment]
that'd point at it being a cache issue indeed, what happens if you replace `client.channels.cache.get` with `client.channels.fetch` on lines 36-41?

**Comment by Blumlaut** [comment]
... and the console?

**Comment by adorne1** [comment]
Same exact message.

**Comment by adorne1** [comment]
Uh, didnt scroll lol..
![image](https://user-images.githubusercontent.com/132327825/236351229-0d1be0e7-33a2-471f-ad43-f27e808a0333.png)

**Comment by adorne1** [comment]
Going to clear my cache again, and redo the process with the edited stuff since it still thinks that the channel does not exist/is invalid

**Comment by Blumlaut** [comment]
404 not found = discord API error, channel unknown, not an EasyAdmin issue.
