### ISSUE TITLE
[BUG] BUG AS YOU CAN SEE

### ISSUE THREAD

**Issue by ItssJxstnDe** [Blumlaut/EasyAdmin#724]
No handler available for this interaction (ApplicationCommand > refreshperms)

WHEN I do /refreshperms in DISCORD

PLS LEARN READ!

**Comment by ItssJxstnDe** [comment]
THIS IS CLEARLY A BUG

**Comment by ItssJxstnDe** [comment]
Btw Txadmin:
[    script:EasyAdmin] Error: DiscordAPIError[10062]: Unknown interaction
[    script:EasyAdmin]     at handleErrors (C:\Users\Administrator\Desktop\FiveM\txData\QBCoreFramework_43F875.base\resources\[ea]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:640:13)
[    script:EasyAdmin]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[    script:EasyAdmin]     at async BurstHandler.runRequest (C:\Users\Administrator\Desktop\FiveM\txData\QBCoreFramework_43F875.base\resources\[ea]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:736:23)
[    script:EasyAdmin]     at async REST.request (C:\Users\Administrator\Desktop\FiveM\txData\QBCoreFramework_43F875.base\resources\[ea]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1387:22)
[    script:EasyAdmin]     at async ChatInputCommandInteraction.reply (C:\Users\Administrator\Desktop\FiveM\txData\QBCoreFramework_43F875.base\resources\[ea]\EasyAdmin\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:111:5)
[    script:EasyAdmin]     at async Object.execute (C:\Users\Administrator\Desktop\FiveM\txData\QBCoreFramework_43F875.base\resources\[ea]\EasyAdmin\server\bot\commands\refreshperms.js:28:3)
[    script:EasyAdmin]     at async Client.<anonymous> (@EasyAdmin/server/bot/bot.js:102:17)
[    script:EasyAdmin] SCRIPT ERROR in promise (unhandled rejection): DiscordAPIError[40060]: Interaction has already been acknowledged.
[    script:EasyAdmin] > handleErrors (C:\Users\Administrator\Desktop\FiveM\txData\QBCoreFramework_43F875.base\resources\[ea]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:640)
[    script:EasyAdmin] > processTicksAndRejections (node:internal/process/task_queues:96)
[    script:EasyAdmin] > async BurstHandler.runRequest (C:\Users\Administrator\Desktop\FiveM\txData\QBCoreFramework_43F875.base\resources\[ea]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:736)
[    script:EasyAdmin] > async REST.request (C:\Users\Administrator\Desktop\FiveM\txData\QBCoreFramework_43F875.base\resources\[ea]\EasyAdmin\node_modules\@discordjs\rest\dist\index.js:1387)
[    script:EasyAdmin] > async ChatInputCommandInteraction.reply (C:\Users\Administrator\Desktop\FiveM\txData\QBCoreFramework_43F875.base\resources\[ea]\EasyAdmin\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:111)
[    script:EasyAdmin]

**Comment by NoobSpielt** [comment]
> PLS LEARN READ!

PLS LEARN HOW TO USE TEMPLATES
lmao
