### ISSUE TITLE
Reports not giving player id

### ISSUE THREAD

**Issue by lemonpepz** [Blumlaut/EasyAdmin#735]
# WARNING: IF YOU DO NOT FILL OUT OR REMOVE THE TEMPLATE YOUR ISSUE WILL GET LOCKED!

## Describe the issue
The report logs are showing the ids labeled in order instead of giving the actual player ids.  It just numbers them in  order 1, 2, 3, 4, 5 etc with no regard for the persons id

## Attempted Solutions
I went through the configs and couldn't see anything that would help me, same with docs
## Screenshots/Logs
![image](https://github.com/Blumlaut/EasyAdmin/assets/134451393/b400c1fa-c1ec-4c2e-9548-e56267573f4a)
the 3 4 5 shown above are not the players ids

## Server Infos (please complete the following information):
 - OS: Windows Server
 - FXServer Version 6461
 - EasyAdmin Version: latest build

**Comment by Blumlaut** [comment]
those are report ids, not user ids

**Comment by lemonpepz** [comment]
right it used to display user ids is there a way to do that
