### ISSUE TITLE
[BUG] Missing features on first login

### ISSUE THREAD

**Issue by iSentrie** [Blumlaut/EasyAdmin#739]
## Describe the bug
Many features from addons are missing and shows up only after reconnecting to the server.

## To Reproduce
1. Get in the server
2. Check menu and see there are many features missing (troll options, change vehicle plate...)
3. Quit
4. Get in the server again and features are there now

## Expected behavior
Should be there from first login.

## Server Infos (please complete the following information):
 - OS: Win11
 - FXServer Version: 6472
 - EasyAdmin Version: 7.01

**Comment by Blumlaut** [comment]
Make sure your plugin is up to date, and you arent using some bad custom permissions system like ESX or whatever, build happens when the menu is generated, not before, so reconnecting would not have an effect, likely you are missing permissions or the plugin is outdated.

**Comment by iSentrie** [comment]
Everything was up to date, however I you were right about ESX and I think it's fixed by adding permissions directly on player identifiers, without adding these to ESX `users` group table in database.
