### ISSUE TITLE
Unexpected Token Error

### ISSUE THREAD

**Issue by UrbanGamerz1505** [Blumlaut/EasyAdmin#758]
![image](https://github.com/Blumlaut/EasyAdmin/assets/141143556/b27ba6e5-6c9c-4ed0-91d3-9942c29099c8)
 
 
 I keep getting this error when EA starts. I have tried a fresh install following the docs, with no luck. I have tried with and without discord bot, neither has worked and the bot won't connect to discord. I am posting here because the Discord invite link for your Support Discord is invalid.

**Comment by bsk193** [comment]
happening to me too, after tree fresh installations of it didn't work. always the same error
https://i.yetanotherdude.xyz/brave_5TauOUpd6H.png

**Comment by Blumlaut** [comment]
looks like Discord.js decided to break itself again, looking into it.
