### ISSUE TITLE
discord bot error

### ISSUE THREAD

**Issue by Veno2uw** [Blumlaut/EasyAdmin#761]
## Describe the issue
A clear and concise description of what the issue is.
i cant use the discord bot
it says
 [    script:EasyAdmin] Error: Failed to log message, please make sure you gave the bot permission to write in the log channel!
[    script:EasyAdmin] 
[    script:EasyAdmin] 
[    script:EasyAdmin] Error: TypeError: isJSONEncodable is not a function
[    script:EasyAdmin]     at /home/zap1096890/g573678/gta5-fivem-txadmin/ESXLegacy_BA643D.base/resources/EasyAdmin/node_modules/discord.js/src/structures/MessagePayload.js:201:9
[    script:EasyAdmin]     at Array.map (<anonymous>)
[    script:EasyAdmin]     at MessagePayload.resolveBody (/home/zap1096890/g573678/gta5-fivem-txadmin/ESXLegacy_BA643D.base/resources/EasyAdmin/node_modules/discord.js/src/structures/MessagePayload.js:200:36)
[    script:EasyAdmin]     at TextChannel.send (/home/zap1096890/g573678/gta5-fivem-txadmin/ESXLegacy_BA643D.base/resources/EasyAdmin/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:171:61)
[    script:EasyAdmin]     at LogDiscordMessage (@EasyAdmin/server/bot/logging.js:38:17)
[    script:EasyAdmin] Error: Failed to set bot commands, you likely didn't invite the bot correctly, please kick the bot and re-invite with the link here:
[    script:EasyAdmin] https://easyadmin.readthedocs.io/en/latest/discordbot/#inviting-the-bot
[    script:EasyAdmin] 
[    script:EasyAdmin] 
[    script:EasyAdmin] Error: DiscordAPIError[0]: 404: Not Found
[    script:EasyAdmin]     at SequentialHandler.runRequest (/home/zap1096890/g573678/gta5-fivem-txadmin/ESXLegacy_BA643D.base/resources/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:743:15)
[    script:EasyAdmin]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[    script:EasyAdmin]     at async SequentialHandler.queueRequest (/home/zap1096890/g573678/gta5-fivem-txadmin/ESXLegacy_BA643D.base/resources/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:549:14)
[    script:EasyAdmin]     at async REST.request (/home/zap1096890/g573678/gta5-fivem-txadmin/ESXLegacy_BA643D.base/resources/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:988:22)
## Attempted Solutions
Describe what you have done to attempt to fix it.
restarting the server
## Screenshots/Logs
If applicable, attach screenshots or log files here to help explain your problem.
none

## Server Infos (please complete the following information):
 - OS: [e.g. Windows Server 2019, Debian 10..] zap hosting txAdmin server
 - FXServer Version [e.g. 5123] 6594
 - EasyAdmin Version 7.0

## Additional context
nah

**Comment by Blumlaut** [comment]
> EasyAdmin Version 7.0

update easyadmin.
