### ISSUE TITLE
Discord bot error V7.02

### ISSUE THREAD

**Issue by Veno2uw** [Blumlaut/EasyAdmin#763]
## Describe the issue 
A clear and concise description of what the issue is.
says 
[    script:EasyAdmin] Logged in as EasyAdmin#1547!
[    script:EasyAdmin] Error: Failed to log message, please make sure you gave the bot permission to write in the log channel!
[    script:EasyAdmin] 
[    script:EasyAdmin] 
[    script:EasyAdmin] Error: DiscordAPIError[50001]: Missing Access
[    script:EasyAdmin]     at SequentialHandler.runRequest (/home/zap1096890/g573678/gta5-fivem-txadmin/ESXLegacy_BA643D.base/resources/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:933:15)
[    script:EasyAdmin]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[    script:EasyAdmin]     at async SequentialHandler.queueRequest (/home/zap1096890/g573678/gta5-fivem-txadmin/ESXLegacy_BA643D.base/resources/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:712:14)
[    script:EasyAdmin]     at async REST.request (/home/zap1096890/g573678/gta5-fivem-txadmin/ESXLegacy_BA643D.base/resources/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:1321:22)
[    script:EasyAdmin]     at async TextChannel.send (/home/zap1096890/g573678/gta5-fivem-txadmin/ESXLegacy_BA643D.base/resources/EasyAdmin/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:162:15)
[    script:EasyAdmin] Error: Failed to configure server status channel, please make sure you gave the bot permission to write in the channel!
[    script:EasyAdmin] 
[    script:EasyAdmin] 
[    script:EasyAdmin] Error: DiscordAPIError[50001]: Missing Access
[    script:EasyAdmin]     at SequentialHandler.runRequest (/home/zap1096890/g573678/gta5-fivem-txadmin/ESXLegacy_BA643D.base/resources/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:933:15)
[    script:EasyAdmin]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[    script:EasyAdmin]     at async SequentialHandler.queueRequest (/home/zap1096890/g573678/gta5-fivem-txadmin/ESXLegacy_BA643D.base/resources/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:712:14)
[    script:EasyAdmin]     at async REST.request (/home/zap1096890/g573678/gta5-fivem-txadmin/ESXLegacy_BA643D.base/resources/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:1321:22)
[    script:EasyAdmin]     at async GuildMessageManager._fetchMany (/home/zap1096890/g573678/gta5-fivem-txadmin/ESXLegacy_BA643D.base/resources/EasyAdmin/node_modules/discord.js/src/managers/MessageManager.js:108:18)
[    script:EasyAdmin]     at async updateServerStatus (@EasyAdmin/server/bot/server_status.js:98:18)
[    script:EasyAdmin] Caught exception:  TypeError: Cannot read properties of undefined (reading 'values')
[    script:EasyAdmin]     at updateServerStatus (@EasyAdmin/server/bot/server_status.js:103:32)
[    script:EasyAdmin]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
## Attempted Solutions
Describe what you have done to attempt to fix it.
updated EasyAdmin to 7.02
## Screenshots/Logs
If applicable, attach screenshots or log files here to help explain your problem.
no

## Server Infos (please complete the following information):
 - OS: [e.g. Windows Server 2019, Debian 10..] Zap Hosting txAdmin server
 - FXServer Version [e.g. 5123] 6594
 - EasyAdmin Version 7.02

## Additional context
nah

**Comment by Blumlaut** [comment]
read the error easyadmin gives you..





> Error: Failed to log message, please make sure you gave the bot permission to write in the log channel!
> Error: DiscordAPIError[50001]: Missing Access

**Comment by Blumlaut** [comment]
do you? read the error, it tells you exactly what to do, I won't spoonfeed you a step by step because it's obvious.
