### ISSUE TITLE
"easy admin failed to configure bot status channel please make sure the channel id is correct and the bot has read and write access" I need support

### ISSUE THREAD

**Issue by bAiLeYidek** [Blumlaut/EasyAdmin#770]
![Screenshot 2023-08-06 132251](https://github.com/Blumlaut/EasyAdmin/assets/114604793/fa793775-3911-41cf-988e-e57191bc2118)
![Screenshot 2023-08-06 132251](https://github.com/Blumlaut/EasyAdmin/assets/114604793/36ac3b23-7472-4b08-9096-a63719a52883)
![Screenshot 2023-08-06 132343](https://github.com/Blumlaut/EasyAdmin/assets/114604793/f1f3a790-37e2-4a73-b521-a1794bc92422)

These are the only errors i get and i followed all the documentation and i don't know what i did wrong.

**Comment by Blumlaut** [comment]
read the error and read the docs.

**Comment by Blumlaut** [comment]
https://easyadmin.readthedocs.io/en/latest/discordbot/#creating-the-bot-user
