### ISSUE TITLE
permissions all say true even after following all the steps

### ISSUE THREAD

**Issue by ENT3R45** [Blumlaut/EasyAdmin#773]
Describe the issue
when i set up and follow the steps that easy admin provide all players that join have access to everything in the easy admin menu i have tried all i can this is my last place to see if sombody can help 

## Attempted Solutions
read through many git hub links and went over the wiki and still couldn't find the solution 

## Screenshots/Logs
![image](https://github.com/Blumlaut/EasyAdmin/assets/141791536/d020ce6e-5882-4f3e-a275-0334f8b5e20b)
![image](https://github.com/Blumlaut/EasyAdmin/assets/141791536/9ebcb61e-c5d6-4f09-aab5-a0df17eab129)

## Server Infos 
 - unsure hosting of a company 
 - 6594
 - latest (7.02)

**Comment by Blumlaut** [comment]
provide your full server.cfg and easyadmin_permissions.cfg file (redact license keys, steam api keys or other private information where required.)
