### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by dfuzeyyy** [Blumlaut/EasyAdmin#776]
[    script:EasyAdmin] Logged in as HTXRP | EasyAdmin#1690!
[ citizen-server-impl] Authenticated with Tebex: Houston Texas Roleplay
[    script:EasyAdmin] Caught exception:  DiscordAPIError[50035]: Invalid Form Body
[    script:EasyAdmin] name[APPLICATION_NAME_INVALID_CONTAINS]: Application name cannot contain ":"
[    script:EasyAdmin]     at SequentialHandler.runRequest (/home/container/_cfx/htxrp/resources/[server-base]/[scripts]/[menus]/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:933:15)
[    script:EasyAdmin]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[    script:EasyAdmin]     at async SequentialHandler.queueRequest (/home/container/_cfx/htxrp/resources/[server-base]/[scripts]/[menus]/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:712:14)
[    script:EasyAdmin]     at async REST.request (/home/container/_cfx/htxrp/resources/[server-base]/[scripts]/[menus]/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:1321:22)
[    script:EasyAdmin]     at async RegisterClientCommands (@EasyAdmin/server/bot/bot.js:46:2)
(node:139) UnhandledPromiseRejectionWarning: DiscordAPIError[
![image](https://github.com/Blumlaut/EasyAdmin/assets/136627966/de4eebb8-7ac6-4308-8edc-8034b3bbc5d4)
50035]: Invalid Form Body
name[APPLICATION_NAME_INVALID_CONTAINS]: Application name cannot contain ":"
    at SequentialHandler.runRequest (/home/container/_cfx/htxrp/resources/[server-base]/[scripts]/[menus]/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:933:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/container/_cfx/htxrp/resources/[server-base]/[scripts]/[menus]/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:712:14)
    at async REST.request (/home/container/_cfx/htxrp/resources/[server-base]/[scripts]/[menus]/EasyAdmin/node_modules/@discordjs/rest/dist/index.js:1321:22)
    at async RegisterClientCommands (@EasyAdmin/server/bot/bot.js:46:2)
(node:139) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
![image](https://github.com/Blumlaut/EasyAdmin/assets/136627966/24444131-27d8-4e38-9980-33e96c434f61)

**Comment by Blumlaut** [comment]
Your Discord Application contains an illegal character, you will have to fix this in your Discord Developer page.
