### ISSUE TITLE
permissions all say true even after following all the steps

### ISSUE THREAD

**Issue by ENT3R45** [Blumlaut/EasyAdmin#777]
## Describe the issue
when i set up and follow the steps that easy admin provide all players that join have access to everything in the easy admin menu i have tried all i can this is my last place to see if sombody can help

## Attempted Solutions
read through many git hub links and went over the wiki and still couldn't find the solution

## Screenshots/Logs
![image](https://github.com/Blumlaut/EasyAdmin/assets/141791536/e6194100-4f59-4df3-9bca-856767152c70)
![image](https://github.com/Blumlaut/EasyAdmin/assets/141791536/44b783fc-ab6f-4e11-970e-8690ef5aa253)

## Server Infos (please complete the following information):
. unsure hosting of a company
. 6594
. latest (7.02)

## Additional context
full server cfg and permissions 
[easy.admin.perms.txt](https://github.com/Blumlaut/EasyAdmin/files/12379209/easy.admin.perms.txt)
[server.cfg.txt](https://github.com/Blumlaut/EasyAdmin/files/12379210/server.cfg.txt)

**Comment by Blumlaut** [comment]
most likely one of your discord roles have permissions they shouldnt have?

**Comment by ENT3R45** [comment]
well yah some of the roles have admin perms is that not allowed?

**Comment by ENT3R45** [comment]
@Blumlaut well yah some of the roles have admin perms is that not allowed?

**Comment by ENT3R45** [comment]
@Blumlaut tried everything its still gives everybody ever single perm like i need help man
