### ISSUE TITLE
config help.

### ISSUE THREAD

**Issue by Jcvidal11** [Blumlaut/EasyAdmin#785]
Im trying to add this command 
![image](https://github.com/Blumlaut/EasyAdmin/assets/93454382/252759e3-b6e6-4b15-b402-c239eb5d1d65)
but I dont know whare to put it and if i shud put commands like this.

**Comment by thecrankytech** [comment]
https://easyadmin.readthedocs.io/en/latest/shortcuts/#:~:text=server%27s%20config%20file
