### ISSUE TITLE
easyadmin .bin not empty wont delete 

### ISSUE THREAD

**Issue by russvargas** [Blumlaut/EasyAdmin#787]
# WARNING: IF YOU DO NOT FILL OUT OR REMOVE THE TEMPLATE YOUR ISSUE WILL GET LOCKED!

## Describe the issue
when we went to delete easyadmin shows us this /g579754/gta5-fivem-txadmin/CFXDefaultFiveM_E730FB.base/DO_NOT_TOUCH/file lol/eslint/node_modules/.bin: Directory not empty. how can i delete this i am the server owner as well. its messing with server files and perms on fivem please help 

## Attempted Solutions
Describe what you have done to attempt to fix it.
placed files into a new locations and no luck reinstalled easyadmin to redo everything and no luck we went on to zap hosting and had no luck 
## Screenshots/Logs
If applicable, attach screenshots or log files here to help explain your problem.

![image_2023-09-02_031855160](https://github.com/Blumlaut/EasyAdmin/assets/143874261/3fea238b-ab0f-4ce1-bcdb-d6f0553db749)

![image_2023-09-02_031823804](https://github.com/Blumlaut/EasyAdmin/assets/143874261/e4ae3941-00c8-42c0-89ed-87743dc16cc0)

## Server Infos (please complete the following information):
 - OS: [e.g. Windows Server 2019, Debian 10..]
 - FXServer Version [e.g. 5123]
 - EasyAdmin Version

**Comment by Blumlaut** [comment]
ZAP-Hosting has a feature to remove node modules and yarn cache, check the settings page, you should also remove any spaces from your folder names first, as those will cause problems as well.

**Comment by russvargas** [comment]
ive tried that through the zap settings and still no luck and ill try the removes spaces and hopefully that works

**Comment by russvargas** [comment]
> ZAP-Hosting has a feature to remove node modules and yarn cache, check the settings page, you should also remove any spaces from your folder names first, as those will cause problems as well.

ive tried that through the zap settings and still no luck and i tried removing spaces but no luck just says bin not empty but shows empty

**Comment by Blumlaut** [comment]
contact ZAP Hositng support.

**Comment by russvargas** [comment]
> contact ZAP Hositng support.

i have im waiting on a reply was just hoping if yall had a solution as well
