### ISSUE TITLE
[BUG] Spectate when different buckets

### ISSUE THREAD

**Issue by iSentrie** [Blumlaut/EasyAdmin#788]
## Describe the bug
When you spectate someone who's in different bucket, you will keep hanging and won't be able to cancel that.

## To Reproduce
1. Spectate someone who's in different bucket 
2. Get stucked

## Expected behavior
Get bucket of player and get set to it until you exit/cancel spectating, also keep updating the bucket in case player exits it, so you would keep spectating him.

## Server Infos (please complete the following information):
 - OS: Win11
 - FXServer Version 6681
 - EasyAdmin Version 7.02

**Comment by Blumlaut** [comment]
changed the tag, hopefully stale will leave this open now

**Comment by Gravxd** [comment]
Fixed / addressed with a solution in the above pull request :)
