### ISSUE TITLE
HWID BANS Possible?

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [Blumlaut/EasyAdmin#790]
**Describe the solution you'd like**
HWID Bans (like what txAdmin does)

**Describe alternatives you've considered**
txAdmin but basically we are banning on EasyAdmin and then also txAdmin its a bit of a pain

**Additional context**
It would simply be great if it was possible with EasyAdmin.
I understand the project is not really supposed to be getting more features. But it would really solidify the menu.

**Comment by Blumlaut** [comment]
I assume you mean "tokens", EasyAdmin has supported that for [over 2 years now](https://github.com/Blumlaut/EasyAdmin/commit/4b30b9ad4913779e0fc24f28fa11dfb395e2b717)
