### ISSUE TITLE
yarn error with discord.js

### ISSUE THREAD

**Issue by Rubthecat88** [Blumlaut/EasyAdmin#791]
# WARNING: IF YOU DO NOT FILL OUT OR REMOVE THE TEMPLATE YOUR ISSUE WILL GET LOCKED!

## Describe the issue
[         script:yarn] Error: [yarn]	warning Waiting for the other yarn instance to finish (pid undefined, inside undefined)
[         script:yarn] error @discordjs/collection@1.5.3: The engine "node" is incompatible with this module. Expected version ">=16.11.0". Got "16.9.1"
[         script:yarn] error Found incompatible module.
[         script:yarn] Error: [yarn]	error @discordjs/collection@1.5.3: The engine "node" is incompatible with this module. Expected version ">=16.11.0". Got "16.9.1"
[         script:yarn] error Found incompatible module.

## Attempted Solutions
install the newest fivem Server files

## Screenshots/Logs
[         script:yarn] Error: [yarn]	warning Waiting for the other yarn instance to finish (pid undefined, inside undefined)
[         script:yarn] error @discordjs/collection@1.5.3: The engine "node" is incompatible with this module. Expected version ">=16.11.0". Got "16.9.1"
[         script:yarn] error Found incompatible module.
[         script:yarn] Error: [yarn]	error @discordjs/collection@1.5.3: The engine "node" is incompatible with this module. Expected version ">=16.11.0". Got "16.9.1"
[         script:yarn] error Found incompatible module.

## Server Infos (please complete the following information):
 - OS: [Windows Server 2022 Standard.]
 - FXServer Version 6683
 - EasyAdmin Version

## Additional context
Pin Discord.js dependencies to prevent build error as FiveM uses an outdated node version.
Wont work can i take a older Easyadminversion?
[fxserver_1694448983.log](https://github.com/Blumlaut/EasyAdmin/files/12578367/fxserver_1694448983.log)

**Comment by fowummmmm** [comment]
how did you fix this
