### ISSUE TITLE
Permissions Being Denied for commands/access

### ISSUE THREAD

**Issue by kaidenD166** [Blumlaut/EasyAdmin#793]
hello, There So, Here is my current Permissions from my server.cfg folder 
I Do Use Badgers Ace perms system (its fully working) 
So, Upon Joining The Server I get A Print Out Displaying This 
https://cdn.discordapp.com/attachments/1145707381691519016/1156337341573648444/image.png?ex=65149a91&is=65134911&hm=c23ed447a83a2a11fed99feb4e767649ca3019a992af85265496650a174c08ec&

Could Someone Re-Write This Or Give Me A Heads Up/Hint On Where I'm Going Wrong As i Know It ISNT The Resource.

ensure [Badgers]
exec @vMenu/config/permissions.cfg
ensure vMenu
ensure NativeUI
ensure screenshot-basic
ensure EasyAdmin
add_ace resource.essentialmode command.sets allow
setr ea_LanguageName "en"
set ea_minIdentifierMatches 2
set ea_moderationNotification "HAS BEEN SET NOT EXPOSING TO THE PUBLIC"
set ea_reportNotification "HAS BEEN SET NOT EXPOSING TO THE PUBLIC"
set ea_detailNotification "HAS BEEN SET NOT EXPOSING TO THE PUBLIC"
setr ea_dateFormat "%d/%m/%Y %H:%M:%S"
set ea_enableReportScreenshots "true"
set ea_logIdentifier "discord,steam,license"
set ea_enableCallAdminCommand "true"
set ea_enableReportCommand "true"
set ea_callAdminCommandName "calladmin"
set ea_reportCommandName "report"
set ea_callAdminCooldown 60
set ea_defaultMinReports 3
set ea_ReportBanTime 86400
set ea_MinReportModifierEnabled "true"
set ea_MinReportPlayers 12
set ea_MinReportModifier 4
set ea_maxWarnings 3
set ea_warnAction "kick"
set ea_warningBanTime 604800
setr ea_IpPrivacy "true"
set ea_botToken "TOKEN IS SET JUST NOT EXPOSING IT TO THE PUBLIC"
set ea_botLogChannel "1156318713864265739"
set ea_botStatusChannel "1156318713864265739"
set ea_botChatBridge "1156318713864265739"
set ea_staffDutyNotification "1156318713864265739"
set ea_backupFrequency 24
set ea_maxBackupCount 10
set ea_chatReminderTime 5
set ea_addReminder "Online Admins: ^3@admins^7"
set ea_enableChat "false"
setr ea_logLevel 3
set ea_useTokenIdentifiers "true"
ensure Badger_Discord_API
ensure DiscordAcePerms
ensure PoliceEMSActivity
ensure BadgerCopChat
ensure DiscordTagIDs
ensure DiscordChatRoles
ensure DiscordPedPerms
ensure VehicleTrustSystem
ensure Badger_Tackle

## Add system admins
add_ace group.admin command allow # allow all commands
add_ace group.admin command.quit deny # but don't allow quit
add_principal identifier.discord:1134101869665456189 group.ownership
add_principal identifier.discord:1136599979901857872 group.ownership 
add_principal identifier.discord:1134102770169942156 group.management
add_principal identifier.discord:1135871370035732550 group.development
add_principal identifier.discord:1134102776247504987 group.staff
add_principal identifier.discord:1154814090066280539 group.tstaff 
exec easyadmin_permissions.cfg

add_ace group.tstaff easyadmin allow
add_ace group.tstaff easyadmin.player.ban.view allow
add_ace group.tstaff easyadmin.player.kick allow
add_ace group.tstaff easyadmin.player.spectate allow
add_ace group.tstaff easyadmin.player.teleport.single allow
add_ace group.tstaff easyadmin.player.slap allow
add_ace group.tstaff easyadmin.player.freeze allow
add_ace group.tstaff easyadmin.player.mute allow
add_ace group.tstaff easyadmin.player.warn allow
add_ace group.tstaff easyadmin.player.screenshot allow
add_ace group.tstaff easyadmin.player.reports.view allow
add_ace group.tstaff easyadmin.player.reports.claim allow
add_ace group.tstaff easyadmin.player.reports.process allow
add_ace group.tstaff easyadmin.player.allowlist allow
add_ace group.tstaff easyadmin.server.shortcut.add allow
add_ace group.tstaff easyadmin.server.reminder.add allow
add_ace group.tstaff easyadmin.server.cleanup.cars allow
add_ace group.tstaff easyadmin.server.cleanup.props allow
add_ace group.tstaff easyadmin.server.cleanup.peds allow
add_ace group.tstaff easyadmin.server.announce allow
add_ace group.tstaff easyadmin.server.chat allow
add_ace group.tstaff easyadmin.immune allow
add_ace group.tstaff easyadmin.bot.baninfo allow
add_ace group.tstaff easyadmin.bot.warn allow
add_ace group.tstaff easyadmin.bot.kick allow
add_ace group.tstaff easyadmin.bot.mute allow
add_ace group.tstaff easyadmin.bot.unmute allow
add_ace group.tstaff easyadmin.bot.freeze allow
add_ace group.tstaff easyadmin.bot.unfreeze allow
add_ace group.tstaff easyadmin.bot.slap allow
add_ace group.tstaff easyadmin.bot.cleanup allow
add_ace group.tstaff easyadmin.bot.playerinfo allow
add_ace group.tstaff easyadmin.bot.playerlist allow
add_ace group.tstaff easyadmin.bot.announce allow
add_ace group.tstaff easyadmin.bot.refreshperms allow
add_ace group.tstaff easyadmin.bot.screenshot allow

add_ace group.staff easyadmin allow
add_ace group.staff easyadmin.player.ban.temporary allow
add_ace group.staff easyadmin.player.ban.permanent allow
add_ace group.staff easyadmin.player.ban.view allow
add_ace group.staff easyadmin.player.ban.edit allow
add_ace group.staff easyadmin.player.kick allow
add_ace group.staff easyadmin.player.spectate allow
add_ace group.staff easyadmin.player.teleport.single allow
add_ace group.staff easyadmin.player.slap allow
add_ace group.staff easyadmin.player.freeze allow
add_ace group.staff easyadmin.player.mute allow
add_ace group.staff easyadmin.player.warn allow
add_ace group.staff easyadmin.player.screenshot allow
add_ace group.staff easyadmin.player.reports.view allow
add_ace group.staff easyadmin.player.reports.claim allow
add_ace group.staff easyadmin.player.reports.process allow
add_ace group.staff easyadmin.player.allowlist allow
add_ace group.staff easyadmin.server.shortcut.add allow
add_ace group.staff easyadmin.server.reminder.add allow
add_ace group.staff easyadmin.server.cleanup.cars allow
add_ace group.staff easyadmin.server.cleanup.props allow
add_ace group.staff easyadmin.server.cleanup.peds allow
add_ace group.staff easyadmin.server.announce allow
add_ace group.staff easyadmin.server.chat allow
add_ace group.staff easyadmin.immune allow
add_ace group.staff easyadmin.bot.ban allow
add_ace group.staff easyadmin.bot.unban allow
add_ace group.staff easyadmin.bot.baninfo allow
add_ace group.staff easyadmin.bot.warn allow
add_ace group.staff easyadmin.bot.kick allow
add_ace group.staff easyadmin.bot.mute allow
add_ace group.staff easyadmin.bot.unmute allow
add_ace group.staff easyadmin.bot.freeze allow
add_ace group.staff easyadmin.bot.unfreeze allow
add_ace group.staff easyadmin.bot.slap allow
add_ace group.staff easyadmin.bot.cleanup allow
add_ace group.staff easyadmin.bot.playerinfo allow
add_ace group.staff easyadmin.bot.playerlist allow
add_ace group.staff easyadmin.bot.announce allow
add_ace group.staff easyadmin.bot.refreshperms allow
add_ace group.staff easyadmin.bot.screenshot allow

add_ace group.development easyadmin allow
add_ace group.development easyadmin.player.ban.temporary allow
add_ace group.development easyadmin.player.ban.permanent allow
add_ace group.development easyadmin.player.ban.view allowallow
add_ace group.development easyadmin.player.ban.edit allow
add_ace group.development easyadmin.player.ban.remove allow
add_ace group.development easyadmin.player.kick allow
add_ace group.development easyadmin.player.spectate allow
add_ace group.development easyadmin.player.teleport.single allow
add_ace group.development easyadmin.player.teleport.everyone allow
add_ace group.development easyadmin.player.slap allow
add_ace group.development easyadmin.player.freeze allow
add_ace group.development easyadmin.player.mute allow
add_ace group.development easyadmin.player.warn allow
add_ace group.development easyadmin.player.screenshot allow
add_ace group.development easyadmin.player.reports.view
add_ace group.development easyadmin.player.reports.claim
add_ace group.development easyadmin.player.reports.process allow
add_ace group.development easyadmin.player.allowlist allow
add_ace group.development easyadmin.server.shortcut.add allow
add_ace group.development easyadmin.server.reminder.add allow
add_ace group.development easyadmin.server.cleanup.cars allow
add_ace group.development easyadmin.server.cleanup.props allow
add_ace group.development easyadmin.server.cleanup.peds allow
add_ace group.development easyadmin.server.announce allow
add_ace group.development easyadmin.server.chat allow
add_ace group.development easyadmin.immune allow
add_ace group.development easyadmin.bot.ban allow
add_ace group.development easyadmin.bot.unban allow
add_ace group.development easyadmin.bot.baninfo allow
add_ace group.development easyadmin.bot.warn allow
add_ace group.development easyadmin.bot.kick allow
add_ace group.development easyadmin.bot.mute allow
add_ace group.development easyadmin.bot.unmute allow
add_ace group.development easyadmin.bot.freeze allow
add_ace group.development easyadmin.bot.unfreeze allow
add_ace group.development easyadmin.bot.slap allow
add_ace group.development easyadmin.bot.cleanup allow
add_ace group.development easyadmin.bot.playerinfo allow
add_ace group.development easyadmin.bot.playerlist allow
add_ace group.development easyadmin.bot.announce allow
add_ace group.development easyadmin.bot.configure allow
add_ace group.development easyadmin.bot.refreshperms allow
add_ace group.development easyadmin.bot.screenshot allow

add_ace group.management easyadmin allow
add_ace group.management easyadmin.player.ban.temporary allow
add_ace group.management easyadmin.player.ban.permanent allow
add_ace group.management easyadmin.player.ban.view allow
add_ace group.management easyadmin.player.ban.edit allow
add_ace group.management easyadmin.player.ban.remove allow
add_ace group.management easyadmin.player.kick allow
add_ace group.management easyadmin.player.spectate allow
add_ace group.management easyadmin.player.teleport.single allow
add_ace group.management easyadmin.player.teleport.everyone allow
add_ace group.management easyadmin.player.slap allow
add_ace group.management easyadmin.player.freeze allow
add_ace group.management easyadmin.player.mute allow
add_ace group.management easyadmin.player.warn allow
add_ace group.management easyadmin.player.screenshot allow
add_ace group.management easyadmin.player.reports.view allow
add_ace group.management easyadmin.player.reports.claim allow
add_ace group.management easyadmin.player.reports.process allow
add_ace group.management easyadmin.player.allowlist allow
add_ace group.management easyadmin.server.shortcut.add allow
add_ace group.management easyadmin.server.reminder.add allow
add_ace group.management easyadmin.server.cleanup.cars allow
add_ace group.management easyadmin.server.cleanup.props allow
add_ace group.management easyadmin.server.cleanup.peds allow
add_ace group.management easyadmin.server.announce allow
add_ace group.management easyadmin.server.chat allow
add_ace group.management easyadmin.immune allow
add_ace group.management easyadmin.anon allow
add_ace group.management easyadmin.bot.ban allow
add_ace group.management easyadmin.bot.unban allow
add_ace group.management easyadmin.bot.baninfo allow
add_ace group.management easyadmin.bot.warn allow
add_ace group.management easyadmin.bot.kick allow
add_ace group.management easyadmin.bot.mute allow
add_ace group.management easyadmin.bot.unmute allow
add_ace group.management easyadmin.bot.freeze allow
add_ace group.management easyadmin.bot.unfreeze allow
add_ace group.management easyadmin.bot.slap allow
add_ace group.management easyadmin.bot.cleanup allow
add_ace group.management easyadmin.bot.playerinfo allow
add_ace group.management easyadmin.bot.playerlist allow
add_ace group.management easyadmin.bot.announce allow
add_ace group.management easyadmin.bot.refreshperms allow
add_ace group.management easyadmin.bot.screenshot allow

add_ace group.ownership easyadmin allow
add_ace group.ownership easyadmin.player.ban.temporary allow
add_ace group.ownership easyadmin.player.ban.permanent allow
add_ace group.ownership easyadmin.player.ban.view allow
add_ace group.ownership easyadmin.player.ban.edit allow
add_ace group.ownership easyadmin.player.ban.remove allow
add_ace group.ownership easyadmin.player.kick allow
add_ace group.ownership easyadmin.player.spectate allow
add_ace group.ownership easyadmin.player.teleport.single allow
add_ace group.ownership easyadmin.player.teleport.everyone allow
add_ace group.ownership easyadmin.player.slap allow
add_ace group.ownership easyadmin.player.freeze allow
add_ace group.ownership easyadmin.player.mute allow
add_ace group.ownership easyadmin.player.warn allow
add_ace group.ownership easyadmin.player.screenshot allow
add_ace group.ownership easyadmin.player.reports.view allow
add_ace group.ownership easyadmin.player.reports.claim allow
add_ace group.ownership easyadmin.player.reports.process allow
add_ace group.ownership easyadmin.player.allowlist allow
add_ace group.ownership easyadmin.server.shortcut.add allow
add_ace group.ownership easyadmin.server.reminder.add allow
add_ace group.ownership easyadmin.server.permissions.read
add_ace group.ownership easyadmin.server.permissions.write
add_ace group.ownership easyadmin.server.cleanup.cars allow
add_ace group.ownership easyadmin.server.cleanup.props allow
add_ace group.ownership easyadmin.server.cleanup.peds allow
add_ace group.ownership easyadmin.server.announce allow
add_ace group.ownership easyadmin.server.convars allow
add_ace group.ownership easyadmin.server.resources.start allow
add_ace group.ownership easyadmin.server.resources.stop allow
add_ace group.ownership easyadmin.server.chat allow
add_ace group.ownership easyadmin.immune allow
add_ace group.ownership easyadmin.anon allow
add_ace group.ownership easyadmin.bot.add_ace allow
add_ace group.ownership easyadmin.bot.add_group allow
add_ace group.ownership easyadmin.bot.remove_ace allow
add_ace group.ownership easyadmin.bot.remove_group allow
add_ace group.ownership easyadmin.bot.ban allow
add_ace group.ownership easyadmin.bot.unban allow
add_ace group.ownership easyadmin.bot.baninfo allow
add_ace group.ownership easyadmin.bot.warn allow
add_ace group.ownership easyadmin.bot.kick allow
add_ace group.ownership easyadmin.bot.mute allow
add_ace group.ownership easyadmin.bot.unmute allow
add_ace group.ownership easyadmin.bot.freeze allow
add_ace group.ownership easyadmin.bot.unfreeze allow
add_ace group.ownership easyadmin.bot.slap allow
add_ace group.ownership easyadmin.bot.cleanup allow
add_ace group.ownership easyadmin.bot.playerinfo allow
add_ace group.ownership easyadmin.bot.playerlist allow
add_ace group.ownership easyadmin.bot.announce allow
add_ace group.ownership easyadmin.bot.configure allow
add_ace group.ownership easyadmin.bot.refreshperms allow
add_ace group.ownership easyadmin.bot.screenshot allow

**Comment by Blumlaut** [comment]
set `ea_logLevel 4` (https://easyadmin.readthedocs.io/en/latest/config/#advanced-configuration) and check if EA even manages to fetch the user, sounds to me like the discord identifier for "Kaiden D" are missing.
