### ISSUE TITLE
Random errors

### ISSUE THREAD

**Issue by ODOJRP** [Blumlaut/EasyAdmin#799]
These errors seem to randomly come and go. The bot status channel was working perfectly fine yesterday. Today it has decided to take the day off. I don't blame it. It is saturday after all. 
![ea](https://github.com/Blumlaut/EasyAdmin/assets/131712751/5d617847-1444-4ab0-82a9-3b93c0f2cf50)

**Comment by Blumlaut** [comment]
"EasyAdmin is not defined" means `ready` never fired, most likely your screenshot is missing earlier errors.

**Comment by ODOJRP** [comment]
> "EasyAdmin is not defined" means `ready` never fired, most likely your screenshot is missing earlier errors.
![Capture1](https://github.com/Blumlaut/EasyAdmin/assets/131712751/8a52607d-9b7c-4d06-b01c-e18817babe61)

sorry.

**Comment by ODOJRP** [comment]
We added Fire Anticheat recently. Could that be conflicting?

**Comment by Blumlaut** [comment]
if that meddles with other resources that would be likely.
