### ISSUE TITLE
@discordjs/collection@1.5.3: The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by Zakwizor** [Blumlaut/EasyAdmin#801]
Hello, I have a small strange error because when starting easyadmin, a strange error appears related to the discord bot which is contained in the menu files, I am sending the error here and waiting for quick and effective help.
answer

Bug/report
[         script:yarn] [yarn]	yarn install v1.22.5
[         script:yarn] [yarn]	info No lockfile found.
[         script:yarn] [yarn]	[1/4] Resolving packages...
[         script:yarn] [yarn]	[2/4] Fetching packages...
[         script:yarn] Error: [yarn]	error @discordjs/collection@1.5.3: The engine "node" is incompatible with this module. Expected version ">=16.11.0". Got "16.9.1"
[         script:yarn] Error: [yarn]	error Found incompatible module.
[         script:yarn] [yarn]	info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[ citizen-server-impl] Building resource EasyAdmin failed.
[ citizen-server-impl] Error data: yarn failed!

**Comment by Blumlaut** [comment]
discordjs/collection should be pinned at 1.5.3:
https://github.com/Blumlaut/EasyAdmin/blob/master/package.json#L22C1-L22C1

make sure you didn't update these manually or run any yarn/npm commands inside your easyadmin folder.

**Comment by Zakwizor** [comment]
I don't know why it doesn't work, I didn't change anything and I didn't do anything to npm

**Comment by Blumlaut** [comment]
unable to reproduce on 7.02 on ZAP-Hosting.
