### ISSUE TITLE
[BUG] getSharedObject deprecated - this event no longer exists

### ISSUE THREAD

**Issue by duckysuck** [Blumlaut/EasyAdmin#809]
## Describe the bug
Dependencies for ESX have changed and now get this error
[ERROR] Resource EasyAdmin Used the getSharedObject Event, this event no longer exists! Visit https://documentation.esx-framework.org/tutorials/tutorials-esx/sharedevent for how to fix! 

## To Reproduce
1. Use with latest ESX
2. Monitor Server for errors
3. observe error

## Expected behavior
No errors and getSharedObject is fixed.

**Comment by Blumlaut** [comment]
>  [ERROR] Resource EasyAdmin Used the getSharedObject Event, this event no longer exists! Visit https://documentation.esx-framework.org/tutorials/tutorials-esx/sharedevent for how to fix!

Obvious lie because ESX is listening for it.

**Comment by duckysuck** [comment]
ha I think the error would be better written as'
getSharedObject is no longer supported, see bla for how to fix.

**Comment by Blumlaut** [comment]
the same way ESX is allergic to good code its to using actual coding terms (deprecated would be the correct wording for it).

anyway i'll probably look at it after work, unlike ESX i prefer not breaking backwards compatibility so i'll have to see if there is a way to make it work with both ESX versions cleanly.

**Comment by duckysuck** [comment]
ha yes you're right.

I think its actually the esx plugin. Going to see if I can fix it my end and report back.

**Comment by duckysuck** [comment]
Actually I'm stuck on plugins/esx/esx_server.lua line 13-20
The other parts are just deleting lines, you've got a couple of things here I'm not sure on.

**Comment by Blumlaut** [comment]
try this for me: 
```Lua
Citizen.CreateThread(function()
	function setESXObj(obj)
		ESX = obj
	end
	function setLicenses(licenses)
		globalLicenses = licenses
		collectgarbage()
	end

	pcall(function()
		ESX = exports["es_extended"]:getSharedObject()
	end)

	if not ESX then
		repeat
			ESX = exports["es_extended"]:getSharedObject()
			Citizen.Wait(10000)
			if not ESX then
				TriggerEvent('esx:getSharedObject', setESXObj)
			else
				TriggerEvent("esx_license:getLicensesList", setLicenses)
			end
		until ESX
	end
end)
```


it should work for both the new and old methods.
