### ISSUE TITLE
[BUG] Latest sapphire shapeshift issue

### ISSUE THREAD

**Issue by lily-de-vries** [Blumlaut/EasyAdmin#812]
## Describe the bug
Latest sapphire shapeshift wont support the 16.x node version of FiveM anymore. 

## To Reproduce
re-create the node packages after 15 december 2023

## Additional context
fixed by adding and older version of sapphire shapeshift in the package.json
![image](https://github.com/Blumlaut/EasyAdmin/assets/91761401/455d6f04-471c-4d33-806c-0aabe4d9aaae)

**Comment by Blumlaut** [comment]
> fixed by adding and older version of sapphire shapeshift in the package.json

in this case a [pull request](https://github.com/Blumlaut/EasyAdmin/pulls) would probably be the better way to address this, i'll push a fix soon.
