### ISSUE TITLE
EasyAdmin will not start!

### ISSUE THREAD

**Issue by VoidTechCG** [Blumlaut/EasyAdmin#814]
## Describe the issue
The issue is that EasyAdmin won't start, im guessing this is due to the fact that yarn is not building EasyAdmin as it should be, its giving me a whole bunchof errors (provided in screenshot below)

## Attempted Solutions
I've tried to re-install my older version of EasyAdmin and that works just fine! Im guessing this is because its already been built. Other than that I am absolutely clueless

## Screenshots/Logs
![image](https://github.com/Blumlaut/EasyAdmin/assets/130710786/61bd9002-511f-4f5f-b3c2-94febe7012af)

## Server Infos (please complete the following information):
 - OS: Not 100% sure what to put here :  FXServer 7257/ZAP (hope thats right!)
 - FXServer Version - v6.0.2 
 - Newest (7.11)

## Additional context
This has happened before but our dev team just reverted back to our old version. Our older version of EasyAdmin is starting to have other issues so we would love to update! Please help!

**Comment by Blumlaut** [comment]
fxserver doesn't have permission to write into the node_modules folder, try setting the FTP Permissions from the ZAP Panel (in the FTP Browser page)

**Comment by VoidTechCG** [comment]
Thank you so so much! You are amazing!
