### ISSUE TITLE
Discord Ace Permissions via Discord Bot

### ISSUE THREAD

**Issue by oMunchieso** [Blumlaut/EasyAdmin#815]
# WARNING: IF YOU DO NOT FILL OUT OR REMOVE THE TEMPLATE YOUR ISSUE WILL GET LOCKED!

## Describe the issue
So going through the documentation, I am trying to configure the bot to register discord roles properly for EasyAdmin integration. But I am struggling to distinguish whether or not I need to post these permissions.

## Attempted Solutions
I have tried in both the server.cfg and easyadminpermissions.cfg, but still have not gotten it to work.

## Screenshots/Logs
I have the full list prepped and ready to go, I just need a little help on where to put the role to the setGroup, and where the allow perms go.

## Server Infos (please complete the following information):
 - OS: Linux 5.15.0-73-generic
 - FXServer-master v1.0.0.7130 linux
 - EasyAdmin Version 7.02

**Comment by Blumlaut** [comment]
i'm not sure how you're expecting any help here considering you didn't post any logs or what you configured at all.

**Comment by oMunchieso** [comment]
![Screenshot 2023-12-31 024826](https://github.com/Blumlaut/EasyAdmin/assets/154095911/f61e1086-07e5-4cf2-b5f1-32b195a186b1)

**Comment by Blumlaut** [comment]
lots of your permissions are just plain incorrect, refer to the docs: https://easyadmin.readthedocs.io/en/latest/permissions/

**Comment by oMunchieso** [comment]
So it is in the right place and it's just wrong because I was referencing this part
![Screenshot 2023-12-31 025600](https://github.com/Blumlaut/EasyAdmin/assets/154095911/e57f092a-7681-4bee-8b6c-539fb4a34ae1)
![Screenshot 2023-12-31 025648](https://github.com/Blumlaut/EasyAdmin/assets/154095911/64b4e99e-7437-42a3-8aac-d6b5701f6ffa)
After I had the role registered to the setGroup, I listed the permissions.

**Comment by oMunchieso** [comment]
> lots of your permissions are just plain incorrect, refer to the docs: https://easyadmin.readthedocs.io/en/latest/permissions/

Is there a way I can get some assistance for the discord perms syncing, maybe the easyadmin cord or a personal cord?
