### ISSUE TITLE
Error data: yarn failed when trying to start easyadmin

### ISSUE THREAD

**Issue by Profas123433** [Blumlaut/EasyAdmin#818]
![Screenshot_20240110-114009142](https://github.com/Blumlaut/EasyAdmin/assets/156127581/2da2a80e-bcef-47d0-b1f3-aec2c4e36c8f)

I have no idea what could be wrong. I tried reinstalling yarn, deleted server cache and still gives me the same error.

**Comment by Blumlaut** [comment]
again - - fill in the template and provide proper logs.

**Comment by Profas123433** [comment]
What's the template, I don't see it anywhere.

**Comment by Profas123433** [comment]
And I also provided the logs with photo
