### ISSUE TITLE
[BUG] Yarn Error/Warning

### ISSUE THREAD

**Issue by Archimoon** [Blumlaut/EasyAdmin#822]
# WARNING: IF YOU DO NOT FILL OUT OR REMOVE THE TEMPLATE YOUR ISSUE WILL GET LOCKED!

## Describe the bug
yarn error while building EA.

## To Reproduce
Clear server cache and db, install new EA version.

## Expected behavior
No build error

## Screenshots/Logs
cfx> restart EasyAdmin
[           resources] Stopping resource EasyAdmin
[ citizen-server-impl] Running build tasks on resource EasyAdmin - it'll restart once completed.
[ citizen-server-impl] Couldn't start resource EasyAdmin.
cfx> [         script:yarn] [yarn]      yarn install v1.22.5
[         script:yarn] Error: [yarn]    warning package.json: No license field
[         script:yarn] [yarn]   info No lockfile found.
[         script:yarn] Error: [yarn]    warning No license field
[         script:yarn] [yarn]   [1/4] Resolving packages...
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/util@0.3.1" is incompatible with requested version "@discordjs/util@.2.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/rest@1.6.0" is incompatible with requested version "@discordjs/rest@.7.1"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/ws@0.8.1" is incompatible with requested version "@discordjs/ws@.8.2"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/rest@1.6.0" is incompatible with requested version "@discordjs/rest@.7.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/util@0.3.1" is incompatible with requested version "@discordjs/util@.2.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/builders@1.6.3" is incompatible with requested version "@discordjs/builders@.6.4"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/collection@1.5.1" is incompatible with requested version "@discordjs/collection@.5.2"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/rest@1.6.0" is incompatible with requested version "@discordjs/rest@.0.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/util@0.3.1" is incompatible with requested version "@discordjs/util@.0.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/ws@0.8.1" is incompatible with requested version "@discordjs/ws@.0.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/util@0.3.1" is incompatible with requested version "@discordjs/util@.2.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/ws@0.8.1" is incompatible with requested version "@discordjs/ws@.8.2"
[         script:yarn] [yarn]   [2/4] Fetching packages...
[         script:yarn] [yarn]   [3/4] Linking dependencies...
[         script:yarn] [yarn]   [4/4] Building fresh packages...
[         script:yarn] Error: [yarn]    warning Ignored scripts due to flag.
[         script:yarn] [yarn]   success Saved lockfile.
[         script:yarn] [yarn]   Done in 15.60s.
[ citizen-server-impl] Build tasks completed - starting resource EasyAdmin.

## Server Infos (please complete the following information):
 - OS: [Windows Server 2022]
 - FXServer Version [7401]
 - EasyAdmin Version 7.1

**Comment by Blumlaut** [comment]
see [package.json](https://github.com/Blumlaut/EasyAdmin/blob/master/package.json), this is not a bug and very much intentional.
