### ISSUE TITLE
Easy Admin won't start

### ISSUE THREAD

**Issue by thalittle** [Blumlaut/EasyAdmin#823]
# WARNING: IF YOU DO NOT FILL OUT OR REMOVE THE TEMPLATE YOUR ISSUE WILL GET LOCKED!

## Describe the issue
A clear and concise description of what the issue is.
EasyAdmin won't start with the FXServer, I'm getting issues with yarn. 
## Attempted Solutions
Describe what you have done to attempt to fix it.
I've cleared server cache and updated my artifacts
## Screenshots/Logs
If applicable, attach screenshots or log files here to help explain your problem.
[              Little] ensure "EasyAdmin"
[ citizen-server-impl] Running build tasks on resource EasyAdmin - it'll restart once completed.
[ citizen-server-impl] Couldn't start resource EasyAdmin.
[             TXADMIN] txaReportResources
[      script:monitor] [txAdmin] Sending resources list to txAdmin.
[         script:yarn] [yarn]   yarn install v1.22.5
[         script:yarn] [yarn]   [1/4] Resolving packages...
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/util@0.3.1" is incompatible with requested version "@discordjs/util@.2.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/rest@1.6.0" is incompatible with requested version "@discordjs/rest@.7.1"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/ws@0.8.1" is incompatible with requested version "@discordjs/ws@.8.2"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/rest@1.6.0" is incompatible with requested version "@discordjs/rest@.7.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/util@0.3.1" is incompatible with requested version "@discordjs/util@.2.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/builders@1.6.3" is incompatible with requested version "@discordjs/builders@.6.4"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/collection@1.5.1" is incompatible with requested version "@discordjs/collection@.5.2"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/rest@1.6.0" is incompatible with requested version "@discordjs/rest@.0.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/util@0.3.1" is incompatible with requested version "@discordjs/util@.0.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/ws@0.8.1" is incompatible with requested version "@discordjs/ws@.0.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/util@0.3.1" is incompatible with requested version "@discordjs/util@.2.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/ws@0.8.1" is incompatible with requested version "@discordjs/ws@.8.2"
[         script:yarn] [yarn]   success Already up-to-date.
[         script:yarn] [yarn]   Done in 0.30s.
[         script:yarn] SCRIPT ERROR in timer: Error: EPERM: operation not permitted, open 'C:\txData\CFXDefault_9E49EA.base\resources\[scripts]\EasyAdmin\.yarn.installed'
[         script:yarn] > Object.openSync (node:fs:585)
[         script:yarn] > Object.writeFileSync (node:fs:2153)
[         script:yarn] > <unknown> (@yarn/yarn_builder.js:67)
[         script:yarn] 
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/util@0.3.1" is incompatible with requested version "@discordjs/util@.2.0"
[         script:yarn] Error: [yarn]    warning Resolution field "@discordjs/ws@0.8.1" is incompatible with requested version "@discordjs/ws@.8.2"
[         script:yarn] [yarn]   success Already up-to-date.
[         script:yarn] [yarn]   Done in 0.30s.
[         script:yarn] SCRIPT ERROR in timer: Error: EPERM: operation not permitted, open 'C:\txData\CFXDefault_9E49EA.base\resources\[scripts]\EasyAdmin\.yarn.installed'
[         script:yarn] > Object.openSync (node:fs:585)
[         script:yarn] > Object.writeFileSync (node:fs:2153)
[         script:yarn] > <unknown> (@yarn/yarn_builder.js:67)
[         script:yarn] 

## Server Infos (please complete the following information):
 - OS: [e.g. Windows Server 2019, Debian 10..] 2022 Windows Server
 - FXServer Version [e.g. 5123]  7406
 - EasyAdmin Version Latest

**Comment by Blumlaut** [comment]
```
Error: EPERM: operation not permitted, open 'C:\txData\CFXDefault_9E49EA.base\resources[scripts]\EasyAdmin.yarn.installed'
```

Your file permissions are incorrect.

**Comment by Blumlaut** [comment]
read the errors you are given, your file permissions are wrong.
