### ISSUE TITLE
EasyAdmin ESX Plugin

### ISSUE THREAD

**Issue by OberMarcLP** [Blumlaut/EasyAdmin#826]
As soon i buy a Magazin (clip) in my shop i get follwing error, when i open the esx plugin in the easyadmin menu and i don't see alll options (see screenshot):

EasyAdmin^7: Error in plugin ESX Plugin: 
@EasyAdmin/plugins/esx/esx_client.lua:180: attempt to concatenate a nil value (field 'label')

![Medal_xA4tFJ1nHs](https://github.com/Blumlaut/EasyAdmin/assets/95079459/64ac3eac-f393-4215-bc58-a841e9c7a24a)

OS: Debian 12
 - FXServer Version: b7375/Ptero
 - EasyAdmin Version: 7.11

**Comment by Blumlaut** [comment]
Is your ESX Plugin up to date? i remember there being a fix pushed for this already, unsure.

**Comment by OberMarcLP** [comment]
Yes, I have the newest Version

**Comment by Blumlaut** [comment]
provide a link to the esx variant you are using, I will check if I can write a patch.

**Comment by OberMarcLP** [comment]
What do you mean with esx variant?
