### ISSUE TITLE
Screenshot Function Failure

### ISSUE THREAD

**Issue by kplutus** [Blumlaut/EasyAdmin#828]
# WARNING: IF YOU DO NOT FILL OUT OR REMOVE THE TEMPLATE YOUR ISSUE WILL GET LOCKED!

## Describe the issue
Screenshot function not working, due to the script calling for a nil value, unsure how to resolve. The script outputs the discord log of "Screenshot of [user] game taken" but then never outputs the screenshot itself. 

## Attempted Solutions
Attempting to reissue the discord webhook url, (on standby until server restart) verified image file type is correct, and attempting to resolve reference issue in the logs below to no avail. 

## Screenshots/Logs
EA Console Log
[    script:EasyAdmin] SCRIPT ERROR: @EasyAdmin/server/admin_server.lua:555: attempt to concatenate a nil value (global 'res')
[    script:EasyAdmin] > handler (@EasyAdmin/server/admin_server.lua:555)

Line of code referenced above. 
![image](https://github.com/Blumlaut/EasyAdmin/assets/81929924/ca92b95d-f657-4282-aef8-5d21dce75fd8)

## Server Infos (please complete the following information):
 - OS: Windows Server 2022
 - FXServer Version  b7479
 - EasyAdmin Version: 7.0.0

## Additional context
It worked before someone with a .lua executor found a way to reply to the script, or abused the webhook to reply to the discord channel. and has not functioned since. 
Image showing modder's abuse of the bot:
![image](https://github.com/Blumlaut/EasyAdmin/assets/81929924/d6f17dab-9975-47e1-8285-74b664daf80a)

**Comment by Blumlaut** [comment]
according to the error no image URL was found in the response of the webhook, likely the Webhook URL is invalid or the data sent is invalid, you can add a `print(result)` after the if result == "ERROR" line to see what the result text was.
