### ISSUE TITLE
Not sure why i cant see the other tab

### ISSUE THREAD

**Issue by azjoey15** [Blumlaut/EasyAdmin#834]
# WARNING: IF YOU DO NOT FILL OUT OR REMOVE THE TEMPLATE YOUR ISSUE WILL GET LOCKED!

## Describe the issue
After applying the perms for some reason, I can not view the server management tab any help??

## Attempted Solutions
I have tried to restart the server and refresh the roles

## Screenshots/Logs
![image](https://github.com/Blumlaut/EasyAdmin/assets/164584163/2fcba808-cd74-4bac-b338-4cef9fa999b1)

## Server Infos (please complete the following information):
 - OS: [Zap Hosting ]
 - FXServer Version [7878]
 - EasyAdmin Version 7.2

**Comment by Blumlaut** [comment]
https://easyadmin.readthedocs.io/en/latest/permissions/
