### ISSUE TITLE
The EA menu doesnt work on REDM

### ISSUE THREAD

**Issue by Brunodare-coder** [Blumlaut/EasyAdmin#843]
# WARNING: IF YOU DO NOT FILL OUT OR REMOVE THE TEMPLATE YOUR ISSUE WILL GET LOCKED!

## Describe the issue
I have done all correctly and the error code appeared as  lua49: attempt to call a nil value (global registerkeymapping)

## Attempted Solutions
the key bind is not working on REDM, I have set the key on the server.ctg and it hasn't worked

## Screenshots/Logs
If applicable, attach screenshots or log files here to help explain your problem.
setr ea_defaultKey "PhotoModePc"
<img width="1144" alt="error" src="https://github.com/Blumlaut/EasyAdmin/assets/122196960/82df6fce-6be1-4b97-bc1e-ac8b590013d7">

## Server Infos (please complete the following information):
Live Console
FIVE: RedM (Linux) #628142

**Comment by Blumlaut** [comment]
https://github.com/Blumlaut/EasyAdmin/blob/master/client/admin_client.lua#L48

this is probably getting triggered too early as the rdr3 test only happens once the resource has fully started

can you try adding
```Lua
if CompendiumHorseObserved then -- https://www.youtube.com/watch?v=r7qovpFAGrQ
    RedM = true
    settings.button = "PhotoModePc"
end
```

above it? does the error disappear then?

**Comment by Brunodare-coder** [comment]
<img width="596" alt="code" src="https://github.com/Blumlaut/EasyAdmin/assets/122196960/8b04d7ea-be28-49a1-b0e5-31236364166e">

Is it correct like that ? 

if not RedM then
	RegisterKeyMapping('easyadmin', 'Open EasyAdmin', 'keyboard', "")
end

if CompendiumHorseObserved then 
    RedM = true
    settings.button = "PhotoModePc"
end

**Comment by Brunodare-coder** [comment]
<img width="1235" alt="error03" src="https://github.com/Blumlaut/EasyAdmin/assets/122196960/8d067d25-13db-4fa0-9a1c-f319ce2c43ed">
I got this error now put it above like that:
<img width="459" alt="photo03" src="https://github.com/Blumlaut/EasyAdmin/assets/122196960/0bb20328-8995-40c8-907a-d60e3e59cee5">

**Comment by Blumlaut** [comment]
ah right, settings are initialised later, that code should probably be moved elsewhere, I'll look at rewriting that bit once I get near an rdr3 install.

**Comment by Blumlaut** [comment]
Please test this commit:
https://github.com/Blumlaut/EasyAdmin/commit/7ce86e5ec9162bc6ede94aebc1205f132535efe0
@Brunodare-coder, it registers the keybind later, which should fix the issue.

**Comment by Blumlaut** [comment]
reminder -- @Brunodare-coder please test the commit above or I will revert it, I don't have a machine capable of running rdr3 currently.

**Comment by Blumlaut** [comment]
closing this as assumed fixed, author abandoned the issue.
