### ISSUE TITLE
Problems with the plugins

### ISSUE THREAD

**Issue by Honeybee-Systems** [Blumlaut/EasyAdmin#844]
## Describe the issue
I bought the Plugins Trainer (Full) Griefing Plugin ESX Plugin and have only problems with it.

## Attempted Solutions
I have reinstalled Easy admin and the plugins.

## Screenshots/Logs
https://bienenschwarm.honeybee.systems/koMA1/ceKAWema61.mp4/raw
Here is a video of the problem.

## Server Infos (please complete the following information):
 - OS Windows Server 2022,
 - FXServer Version 7290
 - EasyAdmin 7.2

**Comment by Honeybee-Systems** [comment]
Good, as I can't get any help either here or in the Discord. I will now forward the whole thing to Tebex Support.

**Comment by Blumlaut** [comment]
your ESX is not returning valid item data (the "label" property is missing), please note that the ESX plugin **only** supports official esx-legacy versions
