### ISSUE TITLE
[BUG] Wrong bucket after specating 2 players

### ISSUE THREAD

**Issue by iSentrie** [Blumlaut/EasyAdmin#845]
## Describe the bug
Correct bucket is lost if admin spectates 2 players one after another who's in different bucket than admin was.

## To Reproduce
1. Open menu and spectate a player who's in other bucket
2. Now spectate another one player who's in different bucket than you was at first
3. Stop spactating
4. See error, you will be in wrong bucket

## Server Infos (please complete the following information):
 - FXServer Version [8552]
 - EasyAdmin Version 7.2

**Comment by Blumlaut** [comment]
I believe this was part of your PR @Gravxd

**Comment by Gravxd** [comment]
Should fix itself with #847

> Quote reply
