### ISSUE TITLE
EasyAdmin not wanting to start

### ISSUE THREAD

**Issue by dylangoetz** [Blumlaut/EasyAdmin#846]
# WARNING: IF YOU DO NOT FILL OUT OR REMOVE THE TEMPLATE YOUR ISSUE WILL GET LOCKED!

## Describe the issue
A clear and concise description of what the issue is. EasyAdmin Will not start. I've tried changing file perms but when I didn't it just wouldn't find the resource.

## Attempted Solutions
Describe what you have done to attempt to fix it.  Changing file perms.

## Screenshots/Logs
If applicable, attach screenshots or log files here to help explain your problem. 
![image](https://github.com/Blumlaut/EasyAdmin/assets/102833763/6bf1bff9-5f19-4336-bd2a-e9d63a9fba32)

## Server Infos (please complete the following information):
 - OS: [e.g. Windows Server 2019, Debian 10..] Ubuntu 22.04.
 - FXServer Version [e.g. 5123] 2802.
 - EasyAdmin Version 7.2.

**Comment by Blumlaut** [comment]
your FiveM Server does not have permission to write into the resources folder, this is required for resources using yarn.
