### ISSUE TITLE
[BUG] Easyadmin broken on the newest ESX Legacy update

### ISSUE THREAD

**Issue by pep021** [Blumlaut/EasyAdmin#851]
## Describe the bug
I updated to the newest ESX version and i also updated to the latest easyadmin version and easyadmin just doenst seems to work. They changed something with the events  or smthing. Please roll out a patch for this issue! If its from me let me know but i dont think so since i updated both scripts to the latest versions 

[  script:es_extended] [ERROR] Resource EasyAdmin Used the getSharedObject Event, this event no longer exists! Visit https://documentation.esx-framework.org/tutorials/tutorials-esx/sharedevent for how to fix!

## To Reproduce
.

## Screenshots/Logs

Heres a picture
![image](https://github.com/user-attachments/assets/92b95856-508f-4369-a4ae-e3a47297c2af)

## Server Infos (please complete the following information):

 - EasyAdmin Version 7.2

**Comment by Blumlaut** [comment]
This was already addressed a while back, please redownload the plugin from your keymaster.
