### ISSUE TITLE
[BUG] Terminal Prints using unstable release error

### ISSUE THREAD

**Issue by rco-titus** [Blumlaut/EasyAdmin#852]
# WARNING: IF YOU DO NOT FILL OUT OR REMOVE THE TEMPLATE YOUR ISSUE WILL GET LOCKED!

## Describe the bug
The EasyAdmin resource is printing in the servers console that the current version is unstable and to download the latest release, despite being on the latest version 7.2

## To Reproduce
1. Install latest version of easyadmin
2. Configured resource accordingly
3. Started Server
4. Observed console for warnings/errors
5. EasyAdmin warning occurs for unstable version

## Expected behavior
Throw no errors/warnings in server console

## Screenshots/Logs
[    script:EasyAdmin] EasyAdmin: You are using an unstable version of EasyAdmin, if this was not your intention, please download the latest stable version from https://github.com/Blumlaut/EasyAdmin

## Server Infos (please complete the following information):
 - OS: Unknown (server through zap)
 - FXServer-master v1.0.0.9231 linux
 - EasyAdmin Version: 7.2

## Additional context
First time installing EasyAdmin, downloaded latest version earlier today

**Comment by Blumlaut** [comment]
you presumably cloned EasyAdmin directly and didn't check out the 7.2 tag, EasyAdmin detects if it has been cloned directly from the is_master tag in fxmanifest.
