### ISSUE TITLE
[BUG] [script:EasyAdmin-7.2] Error: Failed to configure bot status channel

### ISSUE THREAD

**Issue by rco-titus** [Blumlaut/EasyAdmin#854]
# WARNING: IF YOU DO NOT FILL OUT OR REMOVE THE TEMPLATE YOUR ISSUE WILL GET LOCKED!

## Describe the bug
Receiving this error message in my server console about the bot being unable to configure the status channel, I have log forwarding set up as well and this all seems to be working, including the status embed message as the footer keeps updating with when it last updated.
So the status channel is working properly, but the script prints this error.

## To Reproduce
1. Start/restart server through txadmin
2. Click on Live Console
3. Search for easyadmin

## Expected behavior
No errors printed

## Screenshots/Logs
[script:EasyAdmin-7.2] EasyAdmin-7.21: Onesync is Infinity
[script:EasyAdmin-7.2] Error: Failed to configure bot status channel, please make sure the channel id is correct and the bot has read and write access.
[script:EasyAdmin-7.2] Logged in as Server Administration#8650!

## Server Infos (please complete the following information):
 - OS: Unknown (server through zap)
 - FXServer-master v1.0.0.9231 linux
 - EasyAdmin Version: 7.21

## Additional context
Seems to be working absolutely fine, just printing an error when there is no issue

**Comment by ChickenDipper1** [comment]
Was driving me mad too, make EasyAdmin the last resource loaded and you don't get this error message anymore!
