### ISSUE TITLE
[BUG] Searching on a REGEX character will break die highlighting filter

### ISSUE THREAD

**Issue by kees-hoogerheide-teampeak** [Blumlaut/EasyAdmin#857]
## Describe the bug
When you only enter a `+` sign in the searchbar, the regex which is used to highlight the search result will error, breaking the javascript on the page.

## To Reproduce
1. Go to any of the index pages of easy admin
2. Enter a `+` in the search bar and press on search
3. In the console you will see a error `
4. See error `[Uncaught SyntaxError: nothing to repeat](app.18be9a54.js:2 Uncaught SyntaxError: Invalid regular expression: /+/i: Nothing to repeat (at app.18be9a54.js:2:154890))`

## Expected behavior
What should happen is, the page should reload and highlight all `+` characters in the found results.

## Screenshots/Logs
```
app.18be9a54.js:2 Uncaught SyntaxError: Invalid regular expression: /+/i: Nothing to repeat (at app.18be9a54.js:2:154890)
    at new RegExp (<anonymous>)
    at t.rt (app.18be9a54.js:2:154890)
    at new t (app.18be9a54.js:2:152255)
    at HTMLDocument.<anonymous> (app.18be9a54.js:2:151550)
rt @ app.18be9a54.js:2
t @ app.18be9a54.js:2
(anonymous) @ app.18be9a54.js:2
```

## Server Infos (please complete the following information):
 - OS: Windows 11, Chrome (Version 130.0.6723.70 (Official Build) (64-bit)) 
 - EasyAdmin Version: v4.13.5

## Additional context
The error comes from "easycorp\easyadmin-bundle\assets\js\autocomplete.js" line 184.
Inside the method `#createSearchHighlight()` where the characters aren't being escaped and directly taken from the input field:
```
#createSearchHighlight() {
    ...
    const searchQueryTerms = tokenizeString(searchElement.value);
    const searchQueryTermsHighlightRegexp = new RegExp(searchQueryTerms.join('|'), 'i');
    ...
}
```

**Comment by Blumlaut** [comment]
Your EasyAdmin is [in another castle](https://github.com/EasyCorp/EasyAdminBundle).
